-- corllt
-- armllt Arm LLT
-- armanni Pulsar
-- cordoomt3 Epic Bulwark



corllt = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 32000,
	energycost = 700,
	metalcost = 90,
	buildpic = "CORLLT.DDS",
	buildtime = 2720,
	canrepeat = false,
	cantbetransported = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 1 0",
	collisionvolumescales = "32 72 32",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 5100,
	health = 650,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/CORLLT.s3o",
	script = "Units/CORLLT.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 494,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corllt_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
	},
	weapondefs = {
		cor_lightlaser = {
			areaofeffect = 12,
			avoidfeature = false,
			beamtime = 0.12,
			corethickness = 0.175,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 20,
			explosiongenerator = "custom:laserhit-small-red",
			firestarter = 100,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			laserflaresize = 7,
			name = "Light g2g laser",
			noselfdamage = true,
			range = 435,
			reloadtime = 0.46667,
			rgbcolor = "1 0 0",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "lasrfir3",
			soundtrigger = 1,
			targetmoveerror = 0.1,
			thickness = 2,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 2250,
			damage = {
				commanders = 112.5,
				default = 75,
				subs = 5,
				vtol = 5,
			},
		},
	},
	weapons = {
		[1] = {
			def = "COR_LIGHTLASER",
			onlytargetcategory = "NOTSUB",
			fastautoretargeting = true,
		},
	},
},

    --Arm LLT

armllt = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 32768,
	energycost = 680,
	metalcost = 85,
	buildpic = "ARMLLT.DDS",
	buildtime = 2660,
	canrepeat = false,
	cantbetransported = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 5 0",
	collisionvolumescales = "32 77 32",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 5100,
	health = 620,
	maxslope = 14,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/ARMLLT.s3o",
	script = "Units/ARMLLT.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 494,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armllt_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	weapondefs = {
		arm_lightlaser = {
			areaofeffect = 12,
			avoidfeature = false,
			beamtime = 0.12,
			corethickness = 0.175,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 20,
			explosiongenerator = "custom:laserhit-small-red",
			firestarter = 30,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			laserflaresize = 7,
			name = "Light g2g laser turret",
			noselfdamage = true,
			range = 430,
			reloadtime = 0.46667,
			rgbcolor = "1 0 0",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "lasrfir3",
			soundtrigger = 1,
			targetmoveerror = 0.1,
			thickness = 2,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 2250,
			damage = {
				commanders = 112.5,
				default = 75,
				subs = 5,
				vtol = 5,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "ARM_LIGHTLASER",
			onlytargetcategory = "NOTSUB",
			fastautoretargeting = true,
		},
	},
},


    -- Arm Epic Pulsar

armannit3 = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 450000,
	metalcost = 13500,
	buildpic = "ARMANNIT3.DDS",
	buildtime = 190000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 15 0",
	collisionvolumescales = "81 122 81",
	collisionvolumetype = "BoxY",
	corpse = "DEAD",
	damagemodifier = 0.25,
	energystorage = 3000,
	explodeas = "fusionExplosion",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 72,
	health = 28000,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/scavbuildings/ARMANNIT3.s3o",
	onoffable = true,
	radardistance = 1500,
	radaremitheight = 72,
	script = "Units/ARMANNI.cob",
	seismicsignature = 0,
	selfdestructas = "fusionExplosion",
	sightdistance = 900,
	yardmap = "oooooo oooooo oooooo oooooo oooooo oooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armannit3_aoplane.dds",
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 3,
	},
	weapondefs = {
		ata = {
			areaofeffect = 16,
			avoidfeature = false,
			beamtime = 1,
			collidefriendly = false,
			corethickness = 0.5,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.30,
			energypershot = 7000,
			explosiongenerator = "custom:laserhit-large-blue",
			firestarter = 90,
			impulseboost = 0,
			impulsefactor = 0,
			largebeamlaser = true,
			laserflaresize = 8,
			name = "Heavy long-range g2g tachyon accelerator beam",
			noselfdamage = true,
			range = 1800,
			reloadtime = 15,
			rgbcolor = "0 0 1",
			scrollspeed = 5,
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "annigun1",
			soundtrigger = 1,
			targetmoveerror = 0.3,
			texture3 = "largebeam",
			thickness = 10,
			tilelength = 150,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 3100,
			damage = {
				commanders = 480,
				default = 48000,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "ATA",
			onlytargetcategory = "SURFACE",
		},
	},
},


    -- Core Epic Bulwark - Includes EMP

cordoomt3 = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 400000,
	metalcost = 12000,
	buildpic = "CORDOOMT3.DDS",
	buildtime = 170000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0.0 -7.5 0.0",
	collisionvolumescales = "72.0 165.0 72.0",
	collisionvolumetype = "box",
	corpse = "DEAD",
	damagemodifier = 0.25,
	energystorage = 1000,
	explodeas = "fusionExplosion",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 2,
	idletime = 1800,
	sightemitheight = 80,
	health = 39000,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "VTOL",
	objectname = "Units/scavbuildings/CORDOOMT3.s3o",
	onoffable = true,
	radardistance = 1200,
	radaremitheight = 80,
	script = "Units/CORDOOM.cob",
	seismicsignature = 0,
	selfdestructas = "fusionExplosion",
	sightdistance = 900,
	yardmap = "yyooyy oooooo oooooo oooooo oooooo yyooyy",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cordoomt3_aoplane.dds",
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		paralyzemultiplier = 0.4,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 3,
	},
	weapondefs = {
		armagmheat = {
			areaofeffect = 72,
			avoidfeature = false,
			beamtime = 0.6,
			cameraShake = 350,
			corethickness = 0.40,
			craterareaofeffect = 72,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 1200,
			explosiongenerator = "custom:genericshellexplosion-medium-beam",
			impulseboost = 0,
			impulsefactor = 0,
			largebeamlaser = true,
			laserflaresize = 8.8,
			name = "Armageddon Heat Ray",
			noselfdamage = true,
			range = 1350,
			reloadtime = 4,
			rgbcolor = "1 0.8 0",
			rgbcolor2 = "0.8 0 0",
			scrollspeed = 5,
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "heatray2xl",
			soundtrigger = 1,
			targetmoveerror = 0.1,
			thickness = 7,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 1800,
			damage = {
				commanders = 1350,
				default = 7500,
				vtol = 3000,
			},
		},
		armageddon_blue_laser = {
			areaofeffect = 12,
			avoidfeature = false,
			beamtime = 0.3,
			corethickness = 0.32,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 500,
			explosiongenerator = "custom:laserhit-large-blue",
			firestarter = 90,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			largebeamlaser = true,
			laserflaresize = 8.8,
			name = "Long-range g2g tachyon accelerator",
			noselfdamage = true,
			paralyzer = true,--false
			paralyzetime = 5,
			proximitypriority = 0,
			range = 950,
			reloadtime = 6,
			rgbcolor = "0 0 1",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "annigun1",
			soundtrigger = 1,
			targetmoveerror = 0.3,
			texture3 = "largebeam",
			thickness = 5.5,
			tilelength = 150,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 1500,
			damage = {
				commanders = 999,
				default = 4500,
			},
		},
		armageddon_green_laser = {
			areaofeffect = 12,
			avoidfeature = false,
			beamtime = 0.25,
			corethickness = 0.2,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 50,
			explosiongenerator = "custom:laserhit-medium-green",
			firestarter = 90,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			laserflaresize = 7.7,
			name = "High energy g2g laser",
			noselfdamage = true,
			proximitypriority = 0,
			range = 650,
			reloadtime = 0.26,
			rgbcolor = "0 1 0",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "lasrhvy3",
			soundtrigger = 1,
			targetmoveerror = 0.15,
			thickness = 2.6,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 800,
			damage = {
				default = 247,
				vtol = 65,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "ARMAGMHEAT",
			onlytargetcategory = "SURFACE",
		},
		[2] = {
			def = "ARMAGEDDON_BLUE_LASER",
			onlytargetcategory = "NOTSUB",
		},
		[3] = {
			def = "ARMAGEDDON_GREEN_LASER",
			onlytargetcategory = "NOTSUB",
		},
	},
},