-- armbeamer
-- armhlt Arm Dual Laser HLT
-- armannit3 Epic Pulsar
-- legbastion 

-- Constant Fire laser, low damge, short-medium range.
armbeamer = {
	buildcostenergy = 1500,
	buildcostmetal = 190,
	buildtime = 5324,
	cantbetransported = false,
	mass = 7500,
	maxdamage = 1430,
	sightdistance = 475,
	weapondefs = {
		armbeamer_weapon = {
			areaofeffect = 8,
			beamdecay = 0.05,
			beamtime = 0.1,
			beamttl = 1,
			corethickness = 0.233,
			edgeeffectiveness = 0.15,
			energypershot = 6,
			explosiongenerator = "custom:laserhit-beamer",
			firestarter = 30,
			laserflaresize = 9.35,
			name = "Anti-swarm constant wave g2g laser",
			range = 480,
			reloadtime = 0.1,
			rgbcolor = "0 0 1",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "beamershot2",
			soundtrigger = 1,
			targetmoveerror = 0.05,
			thickness = 2.4,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 1000,
			damage = {
				bombers = 2,
				default = 26.6,
				fighters = 2,
				vtol = 2,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "armbeamer_WEAPON",
			onlytargetcategory = "NOTSUB",
			fastautoretargeting = true,
		},
	},
},

armhlt = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 8192,
	energycost = 4700,
	metalcost = 440,
	buildpic = "ARMHLT.DDS",
	buildtime = 12500,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 11 0",
	collisionvolumescales = "36 88 36",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 2600,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/ARMHLT.s3o",
	script = "Units/ARMHLT.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 494,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armhlt_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	weapondefs = {
		arm_laserh1 = {
			areaofeffect = 14,
			avoidfeature = false,
			beamtime = 0.15,
			corethickness = 0.25,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 75,
			explosiongenerator = "custom:laserhit-medium-green",
			firestarter = 90,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			laserflaresize = 9.9,
			name = "Heavy g2g high energy laser",
			noselfdamage = true,
			range = 620,
			reloadtime = 1.8,
			rgbcolor = "0 1 0",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "Lasrmas2",
			soundtrigger = 1,
			targetmoveerror = 0.2,
			thickness = 3,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 2250,
			damage = {
				commanders = 580.5,
				default = 387,
				vtol = 35,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "ARM_LASERH1",
			onlytargetcategory = "NOTSUB",
			fastautoretargeting = true,
		},
	},
},

-- Epic Pulsar - Includes EMP

armannit3 = {
	energycost = 450000,
	metalcost = 13500,
	buildtime = 190000,
	damagemodifier = 0.25,
	energystorage = 3000,
	explodeas = "fusionExplosion",
	footprintx = 6,
	footprintz = 6,
	sightemitheight = 72,
	health = 28000,
	onoffable = true,
	radardistance = 1500,
	radaremitheight = 72,
	sightdistance = 900,
	customparams = {
		techlevel = 3,
	},
	weapondefs = {
		ata = {
			areaofeffect = 16,
			avoidfeature = false,
			beamtime = 1,
			collidefriendly = false,
			corethickness = 0.5,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.30,
			energypershot = 7000,
			explosiongenerator = "custom:laserhit-large-blue",
			firestarter = 90,
			impulseboost = 0,
			impulsefactor = 0,
			largebeamlaser = true,
			laserflaresize = 8,
			name = "Heavy long-range g2g tachyon accelerator beam",
			noselfdamage = true,
			paralyzer = true,--false
			paralyzetime = 5,
			range = 1800,
			reloadtime = 15,
			rgbcolor = "0 0 1",
			scrollspeed = 5,
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "annigun1",
			soundtrigger = 1,
			targetmoveerror = 0.3,
			texture3 = "largebeam",
			thickness = 10,
			tilelength = 150,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 3100,
			damage = {
				commanders = 480,
				default = 48000,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "ATA",
			onlytargetcategory = "SURFACE",
		},
	},
},

-- Constant high damage heatray beam, short range

legbastion = {
	buildangle = 4096,
	energycost = 58000,
	metalcost = 4200,
	buildtime = 79000,
	damagemodifier = 0.25,
	energystorage = 1000,
	explodeas = "largeBuildingexplosiongeneric",
	losemitheight = 80,
	health = 15000,
	onoffable = true,
	radardistance = 1200,
	radaremitheight = 80,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 780,
	customparams = {
		maxrange = 1125,
		techlevel = 2,
	},
	weapondefs = {
		pineappleofdoom = {
			areaofeffect = 120,
			avoidfeature = false,
			avoidfriendly = true,
			beamtime = 1,
			camerashake = 0.1,
			collidefriendly = false,
			corethickness = 0.4,
			craterareaofeffect = 120,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.45,
			energypershot = 500,
			explosiongenerator = "custom:genericshellexplosion-medium-beam",
			firestarter = 90,
			firetolerance = 300,
			impulseboost = 0,
			impulsefactor = 0,
			laserflaresize = 6,
			name = "Cleansing Light",
			noselfdamage = true,
			predictboost = 0.3,
			proximitypriority = 1,
			range = 1100,
			reloadtime = 2.5,
			rgbcolor = "1 0.5 0",
			rgbcolor2 = "0.9 1.0 0.5",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "heatray3",
			soundstartvolume = 38,
			soundtrigger = 1,
			sweepfire = true,
			targetmoveerror = 0.001,
			thickness = 5.5,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 1500,
			damage = {
				default = 4500,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "pineappleofdoom",
			onlytargetcategory = "SURFACE",
			fastautoretargeting = true,
		}
	},
},


