-- armpb Arm Pitbull T2 [popup] Gauss cannon
-- LegMG
-- armminivulc Mini rag
--  armvulc Rag

-- Arm Pitbull Small Popup Gauss Canmon.  Medium damge, rate of fire and range.
armpb = {
	buildcostenergy = 14000,
	buildcostmetal = 680,
	buildtime = 14961,
	cloakcost = 16,
	damagemodifier = 0.5,
	maxdamage = 2800,
	mincloakdistance = 55,
	sightdistance = 598,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		armpb_weapon = {
			areaofeffect = 24,
			edgeeffectiveness = 0.15,
			name = "Pop-up heavy g2g gauss cannon",
			range = 730,
			reloadtime = 1.6,
			separation = 1.8,
			nogap = false,
			sizeDecay = 0.06,
			stages = 14,
			alphaDecay = 0.08,
			targetmoveerror = 0.2,
			tolerance = 8000,
			turret = true,
			weapontype = "Cannon",
			weaponvelocity = 800,
			damage = {
				bombers = 26,
				default = 675,
				fighters = 26,
				hvyboats = 472.5,
				subs = 300,
				vtol = 26,
			},
		},
	},
},


    -- Legion Machine Gun

legmg = {
	maxacc = 0,
	airsightdistance = 650,
	maxdec = 0,
	buildangle = 32768,
	energycost = 5500,
	metalcost = 420,
	buildpic = "legmg.DDS",
	buildtime = 8400,
	canrepeat = false,
	cantbetransported = false,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "36 80 36",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 7500,
	health = 2350,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/LEGMG.s3o",
	script = "Units/LEGMG.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 525,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armmg_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weaponaa',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	weapondefs = {
		armmg_weapon = {
			accuracy = 7,
			areaofeffect = 16,
			avoidfeature = false,
			burst = 6,
			burstrate = 0.0675,
			burnblow = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			duration = 0.038,
			edgeeffectiveness = 0.85,
			explosiongenerator = "custom:plasmahit-sparkonly",
			fallOffRate = 0.2,
			firestarter = 0,
			impulseboost = 0.4,
			impulsefactor = 1.5,
			intensity = 0.8,
			name = "Rapid-fire a2g machine guns",
			noselfdamage = true,
			ownerExpAccWeight = 4.0,
			proximitypriority = 3,
			range = 575,
			reloadtime = 0.4,
			rgbcolor = "1 0.95 0.4",
			--size = 2.25,
			soundhit = "bimpact3",
			soundhitwet = "splshbig",
			soundstart = "minigun3",
			soundstartvolume = 4.5,
			sprayangle = 968,
			thickness = 0.91,
			tolerance = 6000,
			turret = true,
			--weapontimer = 1,
			weapontype = "LaserCannon",
			weaponvelocity = 958,
			damage = {
				commanders = 5,
				default = 18,
				vtol = 18,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "armmg_WEAPON",
			onlytargetcategory = "NOTSUB",
		},
	},
},

    -- Arm mini Ragnarok

armminivulc = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 29096,
	energycost = 60000,
	metalcost = 2000,
	buildpic = "ARMMINIVULC.DDS",
	buildtime = 65000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -6 0",
	collisionvolumescales = "32 64 32",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "hugeBuildingexplosiongeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 6700,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/scavbuildings/armminivulc.s3o",
	script = "Units/scavbuildings/armminivulc.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 700,
	--usepiececollisionvolumes = 1,
	yardmap = "ooo ooo ooo",
	customparams = {
		usebuildinggrounddecal = false,
		buildinggrounddecaltype = "decals/armminivulc_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	weapondefs = {
		armminivulc_weapon = {
			accuracy = 700,
			areaofeffect = 44.8,
			avoidfeature = false,
			avoidfriendly = true,
			avoidground = true,
			cegtag = "arty-heavy",
			collidefriendly = false,
			craterboost = 0.02,
			cratermult = 0.02,
			edgeeffectiveness = 0.9,
			energypershot = 1000,
			explosiongenerator = "custom:genericshellexplosion-medium-bomb",
			gravityaffected = "true",
			impulseboost = 0.1,
			impulsefactor = 0.1,
			name = "Mini Rapid-fire long-range plasma cannon",
			noselfdamage = true,
			range = 1300,
			reloadtime = 0.4,
			rgbcolor = "1, 0.4, 0",
			soundhit = "xplomed3",
			soundhitwet = "splshbig",
			soundstart = "cannon2",
			turret = true,
			weapontimer = 14,
			weapontype = "Cannon",
			weaponvelocity = 660,
			damage = {
				default = 210,
				shields = 105,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "ARMMINIVULC_WEAPON",
			onlytargetcategory = "SURFACE",
		},
	},
},

-- Rapidfire Ultra high damage and long range railgun.  Huge metal cost.
--Arm Ragnarok

armvulc = {
	energycost = 752000,
	metalcost = 63000,
	buildtime = 1400000,
	explodeas = "advancedFusionExplosion",
	firestate = 0,
	footprintx = 8,
	footprintz = 8,
	health = 32000,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 700,
	customparams = {
		buildinggrounddecalsizey = 7.5,
		buildinggrounddecalsizex = 7.5,
		buildinggrounddecaldecayspeed = 30,
		techlevel = 2,
	},
	weapondefs = {
		ata = {
            areaofeffect = 10,
            avoidfeature = false,
            beamtime = 0.3,
            collidefriendly = false,
            corethickness = 0.5,
            craterareaofeffect = 0,
            craterboost = 0,
            cratermult = 0,
            edgeeffectiveness = 0.5,
            energypershot = 25000,
            explosiongenerator = "custom:laserhit-large-blue",
            firestarter = 90,
            impulseboost = 0,
            impulsefactor = 0,
            largebeamlaser = true,
            laserflaresize = 30,
            name = "Rapid-fire extended-range g2g tachyon accelerator",
            noselfdamage = true,
            range = 2500,
            reloadtime = 2,
            rgbcolor = "0 0 1",
            scrollspeed = 5,
            soundhitdry = "",
            soundhitwet = "sizzle",
            soundstart = "annigun1",
            soundtrigger = 0.5,
            targetmoveerror = 0.3,
            texture3 = "largebeam",
            thickness = 9,
            tilelength = 150,
            tolerance = 10000,
            turret = true,
            weapontype = "BeamLaser",
            weaponvelocity = 3100,
            damage = {
                commanders = 4800,
                default = 50000,
            },
        },
    },
    weapons = {
        [1] = {
            badtargetcategory = "VTOL GROUNDSCOUT",
            def = "ATA",
            onlytargetcategory = "SURFACE",	
            },
        },
},