-- corscavdtm Missile Dragon's Tooth
-- cormwall Draon's Rage Wall
-- cortron Tactical Missile Launcher
-- corvipe Core T2 Scorpion [popup] Sabot Battery <Deep Penetration Micro Missiles>


-- Long range tracking missiles Medium Yield, low firerate.

corscavdtm = {
	buildcostenergy = 1550,
	buildcostmetal = 290,
	buildtime = 4419,
	canrepeat = false,
	damagemodifier = 0.25,
	maxdamage = 1610,
	weapondefs = {
		cormh_weapon = {
			areaofeffect = 80,
			edgeeffectiveness = 0.15,
			firestarter = 100,
			flighttime = 10,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			metalpershot = 0,
			range = 500,
			reloadtime = 5,
			tolerance = 4000,
			turnrate = 15000,
			weaponacceleration = 70,
			weapontimer = 2.9,
			weapontype = "StarburstLauncher",
			weaponvelocity = 480,
			damage = {
				default = 550,
				subs = 200,
			},
		},
	},
},

-- Tracking Mssile Launcher, medium damage, long range, high rate of fire.

cormwall = {
	energycost = 4800, 
	metalcost = 1020, 
	buildtime = 14000,
	damagemodifier = 0.25,
	decoyfor = "corfort",
	explodeas = "smallBuildingexplosiongeneric",
	health = 5320,
	stealth = true,
	customparams = {
		neutral_when_closed = true,
		usebuildinggrounddecal = true,
		unitgroup = 'weapon',
		decoyfor = "armfort",
		techlevel = 2,
	},
	weapondefs = {
		exp_heavyrocket = {
			areaofeffect = 96,
			avoidfeature = false,
			burst = 7,
			burstrate = 0.1,
			cegtag = "missiletrailsmall-red",
			craterboost = 0,
			cratermult = 0,
			dance = 24,
			edgeeffectiveness = 0.65,
			explosiongenerator = "custom:genericshellexplosion-catapult",
			firestarter = 70,
			flighttime = 3.2,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			metalpershot = 0,
			model = "catapultmissile.s3o",
			movingaccuracy = 600,
			name = "CatapultRockets",
			noselfdamage = true,
			proximitypriority = -1,
			range = 675,
			reloadtime = 15,
			smoketrail = true,
			smokePeriod = 4,
			smoketime = 16,
			smokesize = 8.5,
			smokecolor = 0.5,
			smokeTrailCastShadow = false,
			soundhit = "rockhit",
			soundhitwet = "splsmed",
			soundstart = "rapidrocket3",
			startvelocity = 165,
			texture1 = "null",
			texture2 = "smoketrailbar",
			trajectoryheight = 3,
			turnrate = 5000,
			turret = true,
			weaponacceleration = 100,
			weapontimer = 6,
			weapontype = "MissileLauncher",
			weaponvelocity = 530,
			wobble = 2000,
			damage = {
				default = 450,
			},
		},
	},
	weapons = {
		[1] = {
			def = "exp_heavyrocket",
			onlytargetcategory = "SURFACE",
			fastautoretargeting = true,
		},
	},
},

    -- Core Tactical Missile Launcher

cortron = {
    maxacc = 0,
    maxdec = 0,
    buildangle = 8192,
    energycost = 14000,
    metalcost = 1200,
    buildpic = "CORTRON.DDS",
    buildtime = 59000,
    category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
    collisionvolumeoffsets = "0 0 0",
    collisionvolumescales = "59 47 59",
    collisionvolumetype = "CylY",
    corpse = "DEAD",
    explodeas = "nukeBuilding",
    footprintx = 4,
    footprintz = 4,
    icontype = "building",
    idleautoheal = 5,
    idletime = 1800,
    health = 3550,
    maxslope = 10,
    maxwaterdepth = 0,
    objectname = "Units/CORTRON.s3o",
    script = "Units/CORTRON.cob",
    seismicsignature = 0,
    selfdestructas = "nukeBuildingSelfd",
    sightdistance = 455,
    yardmap = "oooooooooooooooo",
    customparams = {
        usebuildinggrounddecal = true,
        buildinggrounddecaltype = "decals/cortron_aoplane.dds",
        buildinggrounddecalsizey = 7.5,
        buildinggrounddecalsizex = 7.5,
        buildinggrounddecaldecayspeed = 30,
        unitgroup = 'weapon',
        model_author = "Mr Bob",
        normaltex = "unittextures/cor_normal.dds",
        removewait = true,
        subfolder = "corbuildings/landdefenceoffence",
        techlevel = 2,
    },
    weapondefs = {
        cortron_weapon = {
            areaofeffect = 380, --512,
            avoidfeature = false,
            avoidfriendly = false,
            cegtag = "cruisemissiletrail-tacnuke",
            collideenemy = false,
            collidefeature = false,
            collidefriendly = false,
            commandfire = true,
            craterareaofeffect = 512,
            craterboost = 1.6,
            cratermult = 0.7,
            edgeeffectiveness = 0.55,
            energypershot = 17437,
            explosiongenerator = "custom:newnuketac",
            firestarter = 0,
            flighttime = 400,
            impulseboost = 0.123,
            impulsefactor = 0.123,
            metalpershot = 550,
            model = "cortronmissile.s3o",
            name = "Long range tactical g2g nuclear warheads",
            noselfdamage = true,
            range = 2250,
            reloadtime = 2,
            smoketrail = true,
            smokePeriod = 9,
            smoketime = 60,
            smokesize = 14.0,
            smokecolor = 0.7,
            smokeTrailCastShadow = false,
            soundhit = "xplomed4",
            soundstart = "mismed1",
            stockpile = true,
            stockpiletime = 75,
            texture1 = "null",
            texture2 = "smoketrailbar",
            texture3 = "null",
            tolerance = 4000,
            turnrate = 10000,
            weaponacceleration = 150,
            weapontimer = 3,
            weapontype = "StarburstLauncher",
            weaponvelocity = 1200,
            damage = {
                commanders = 750,
                default = 4000,
            },
        },
    },
    weapons = {
        [1] = {
            badtargetcategory = "NOTLAND",
            def = "CORTRON_WEAPON",
            onlytargetcategory = "NOTSUB",
        },
    },
},


-- Medium range horizontal tracking Mssile launcher, high damage

corvipe = {
	energycost = 14000,
	metalcost = 730,
	buildtime = 15000,
	damagemodifier = 0.5,
	explodeas = "smallBuildingexplosiongeneric",
	health = 3000,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 546,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		vipersabot = {
			areaofeffect = 24,
			avoidfeature = false,
			burnblow = true,
			cegtag = "missiletrailviper",
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-medium-bomb",
			firestarter = 70,
			flighttime = 1.05,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			model = "cormissile3fast.s3o",
			name = "Heavy g2g sabot rocket launcher",
			noselfdamage = true,
			range = 730,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 33,
			smokesize = 10,
			smokecolor = 0.8,
			smokeTrailCastShadow = false,
			soundhit = "SabotHit",
			soundhitwet = "splshbig",
			soundstart = "SabotFire",
			startvelocity = 570,
			targetmoveerror = 0.2,
			smokeperiod = 5,
			castshadow = true,
			texture1 = "null",
			texture2 = "railguntrail",
			tolerance = 8000,
			tracks = true,
			turnrate = 6000,
			turret = true,
			weaponacceleration = 400,
			weapontimer = 0.1,
			weapontype = "MissileLauncher",
			weaponvelocity = 950,
			damage = {
				default = 825,
				hvyboats = 577.5,
				subs = 5,
				vtol = 26,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "VIPERSABOT",
			onlytargetcategory = "SURFACE",
		},
	},
},

