-- armguard Arm T1 Plasma
-- corpun Core T1 Plasma
-- armamb Arm T2 Plasma
-- cortoast Core T2 Plasma


    -- Arm T1 Plasma
armguard = {
	energycost = 12500,
	metalcost = 1250,
	buildtime = 21400,
	health = 3050,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 455,
	customparams = {
		techlevel = 1,
	},
	weapondefs = {
		plasma = {
			accuracy = 75,
			areaofeffect = 100,
			edgeeffectiveness = 0.4,
			explosiongenerator = "custom:genericshellexplosion-medium",
			impulseboost = 0.123,
			impulsefactor = 0.5,
			--model = "artshell-medium.s3o",
			name = "Heavy g2g long range plasma cannon",
			range = 1220,
			reloadtime = 2.85,
			weaponvelocity = 450,
			damage = {
				default = 300,
			},
		},
		plasma_high = {
			accuracy = 75,
			areaofeffect = 192,
			craterareaofeffect = 192,
			edgeeffectiveness = 0.65,
			explosiongenerator = "custom:genericshellexplosion-medium-bomb",
			hightrajectory = 1,
			impulseboost = 0.123,
			impulsefactor = 1.4,
			--model = "artshell-medium.s3o",
			name = "High-trajectory g2g long-range AoE plasma cannon",
			proximitypriority = -2,
			range = 1220,
			reloadtime = 7,
			weaponvelocity = 440,
			damage = {
				default = 600,
			},
		},
	},
},

-- Core T1 Plasma, Agitator
corpun = {
	energycost = 13500,
	metalcost = 1300,
	buildtime = 19300,
	explodeas = "largeBuildingexplosiongeneric",
	health = 3250,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 455,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		plasma = {
			accuracy = 75,
			areaofeffect = 120,
			edgeeffectiveness = 0.4,
			explosiongenerator = "custom:genericshellexplosion-medium-bomb",
			impulseboost = 0.123,
			impulsefactor = 0.5,
			--model = "artshell-medium.s3o",
			name = "Long-range g2g plasma cannon",
			range = 1245,
			reloadtime = 3.16667,
			weaponvelocity = 450,
			damage = {
				default = 350,
			},
		},
		plasma_high = {
			accuracy = 75,
			areaofeffect = 208,
			edgeeffectiveness = 0.65,
			explosiongenerator = "custom:genericshellexplosion-medium-bomb",
			hightrajectory = 1,
			impulseboost = 0.123,
			impulsefactor = 1.4,
			--model = "artshell-medium.s3o",
			name = "Long-range high-trajectory g2g AoE plasma cannon",
			proximitypriority = -2,
			range = 1245,
			reloadtime = 7.5,
			weaponvelocity = 440,
			damage = {
				default = 650,
			},
		},
	},
},


-- Arm T2 Plasma, Rattlesnake
armamb = {
	energycost = 17000,
	metalcost = 2500,
	buildtime = 27000,
	cloakcost = 24,
	damagemodifier = 0.25,
	explodeas = "smallBuildingexplosiongeneric",
	health = 4000,
	mincloakdistance = 70,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 442,
	customparams = {
		techlevel = 3,
	},
	weapondefs = {
		armamb_gun = {
			accuracy = 400,
			areaofeffect = 152,
			edgeeffectiveness = 0.4,
			explosiongenerator = "custom:genericshellexplosion-medium-aoe",
			impulseboost = 0.123,
			impulsefactor = 0.5,
			--model = "artshell-large.s3o",
			name = "Pop-up heavy  long range g2g plasna cannon",
			predictboost = 0.2,
			range = 1380,
			reloadtime = 1.8,
			weaponvelocity = 450,
			damage = {
				default = 350,
			},
		},
		armamb_gun_high = {
			accuracy = 400,
			areaofeffect = 224,
			craterareaofeffect = 224,
			craterboost = 0.0492,
			cratermult = 0.0492,
			edgeeffectiveness = 0.65,
			explosiongenerator = "custom:genericshellexplosion-large-bomb",
			hightrajectory = 1,
			impulseboost = 0.123,
			impulsefactor = 2,
			--model = "artshell-large.s3o",
			name = "Pop-up high-trajectory heavy  long range AoE g2g plasma cannon",
			proximitypriority = -2,
			range = 1380,
			reloadtime = 7,
			weaponvelocity = 440,
			damage = {
				default = 850,
				subs = 150,
				vtol = 90,
			},
		},
	},
},

--Core T2 Plasma, Persecutor
cortoast = {
	energycost = 17000,
	metalcost = 2500,
	buildtime = 25700,
	damagemodifier = 0.25,
	explodeas = "mediumBuildingExplosionGeneric",
	health = 4250,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 416,
	customparams = {
		techlevel = 4,
	},
	weapondefs = {
		cortoast_gun = {
			accuracy = 450,
			areaofeffect = 164,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.4,
			explosiongenerator = "custom:genericshellexplosion-medium-aoe",
			impulseboost = 0.123,
			impulsefactor = 0.5,
			--model = "artshell-medium.s3o",
			name = "Pop-up long-range heavy g2g plasma cannon",
			predictboost = 0.2,
			range = 1390,
			reloadtime = 2.1,
			weaponvelocity = 450,
			damage = {
				default = 420,
			},
		},
		cortoast_gun_high = {
			accuracy = 450,
			areaofeffect = 240,
			craterareaofeffect = 240,
			edgeeffectiveness = 0.65,
			explosiongenerator = "custom:genericshellexplosion-large-bomb",
			hightrajectory = 1,
			impulseboost = 0.123,
			impulsefactor = 2,
			--model = "artshell-medium.s3o",
			name = "Pop-up high-trajectory long-range heavy g2g AoE plasma cannon",
			proximitypriority = -2,
			range = 1390,
			reloadtime = 8,
			weaponvelocity = 440,
			damage = {
				default = 960,
			},
		},
	},
},