cormakr = {
	energycost = 1250,
	metalcost = 100,
	buildtime = 1500,
	health = 500,
	explodeas = "metalmaker",
	selfdestructas = "metalmakerSelfd",
	customparams = {
		energyconv_capacity = 100,
		energyconv_efficiency = 1/75,
	},
},
armmakr = {
	energycost = 5500,
	metalcost = 10,
	buildtime = 2500,
	health = 300,
	explodeas = "advmetalmaker",
	selfdestructas = "advmetalmakerSelfd",
	customparams = {
		energyconv_capacity = 2500,
		energyconv_efficiency = 1/50,
		techlevel = 2,
	},
},
cormmkr = {
	energycost = 10500,
	metalcost = 500,
	buildtime = 15500,
	health = 5000,
	explodeas = "metalmaker",
	selfdestructas = "metalmakerSelfd",
	customparams = {
		energyconv_capacity = 1000,
		energyconv_efficiency = 1/60,
		techlevel = 3,
	},
},
armmmkr = {
	energycost = 40500,
	metalcost = 300,
	buildtime = 10500,
	health = 900,
	explodeas = "advmetalmaker",
	selfdestructas = "advmetalmakerSelfd",
	customparams = {
		energyconv_capacity = 10000,
		energyconv_efficiency = 1/40,
		techlevel = 4,
	},
},

------------------ Safe Energy -----------------------------

armadvsol = {
	energycost = 1000,
	metalcost = 100,
	buildtime = 500,
	energymake = 200,
	energystorage = 100,
	metalmake = 5,
	health = 1200,
	selfdestructcountdown = 1,
	selfdestructas = "lootboxExplosion1",
	footprintx = 3,
	footprintz = 3,
	customparams = {
		techlevel = 1,
	},
},
lootboxplatinum = {
	energycost = 3000,
	metalcost = 1000,
	buildtime = 1500,
	energymake = 400,
	health = 2500,
	metalmake = 20,
	selfdestructcountdown = 1,
	explodeas = "fusionExplosion",
	selfdestructas = "lootboxExplosion4",
	unitname = "Experimental Safe Fusion Reactor",
	cantbetransported = false,
	capturable = false,
	icontype = "lootbox",
	speed = 0,
	movementclass = "HOVER3",
	movestate = 0,
	transportbyenemy = false,
	reclaimable = true,
	customparams = {
		techlevel = 2,
	},
},
lootboxgold = {
	energycost = 9000,
	metalcost = 10500,
	buildtime = 4500,
	energymake = 5000,
	health = 20500,
	metalmake = 80,
	explodeas = "lootboxExplosion4",
	selfdestructas = "lootboxExplosion3",
	unitname = "Safe Fusion Reactor",
	selfdestructcountdown = 1,
	cantbetransported = false,
	capturable = false,
	icontype = "lootbox",
	speed = 0,
	movementclass = "HOVER3",
	movestate = 0,
	transportbyenemy = false,
	reclaimable = true,
	customparams = {
		techlevel = 3,
	},
},

armfus = {
	energycost = 27000,
	metalcost = 100500,
	buildtime = 12500,
	energymake = 25000,
	energystorage = 5000,
	metalmake = 400,
	health = 100500,
	damagemodifier = 0.25,
	explodeas = "fusionExplosion",
	selfdestructas = "lootboxExplosion3",
	selfdestructcountdown = 1,
	footprintx = 6,
	footprintz = 3,
	customparams = {
		techlevel = 4,
	},
},


------------------ Volatile Energy -----------------------------

freefusion = {
    unitrestricted = 10,
	energycost = 2000,
	metalcost = 300,
	buildtime = 100,
	energymake = 1000,
	energystorage = 5000,
	metalmake = 10,
	explodeas = "fusionExplosion",
	selfdestructas = "lootboxExplosion1",
	selfdestructcountdown = 1,
	footprintx = 5,
	footprintz = 5,
	health = 100,
	customparams = {
		techlevel = 1,
	},
},
corfus = {
	energycost = 10500,
	metalcost = 1500,
	buildtime = 1000,
	energymake = 3500,
	energystorage = 10000,
	health = 1500,
	damagemodifier = 1.15,
	explodeas = "advancedFusionExplosion",
	selfdestructas = "lootboxExplosion2",
	selfdestructcountdown = 1,
	footprintx = 6,
	footprintz = 6,
	customparams = {
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		techlevel = 2,
	},
},
armafus = {
	energycost = 30500,
	metalcost = 3000,
	buildtime = 2500,
	energymake = 15500,
	energystorage = 30000,
	health = 1800,
	damagemodifier = 1.15,
	explodeas = "advancedFusionExplosion",
	selfdestructas = "lootboxExplosion4",
	selfdestructcountdown = 1,
	footprintx = 7,
	footprintz = 7,
	customparams = {
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		techlevel = 3,
	},
},
lootboxbronze = {
	energycost = 50000,
	metalcost = 10500,
	buildtime = 1000,
	energymake = 10,
	health = 500,
	metalmake = 10,
	cantbetransported = false,
	capturable = false,
	explodeas = "lootboxExplosion1",
	icontype = "lootbox",
	speed = 0,
	movementclass = "HOVER3",
	movestate = 0,
	explodeas = "advancedFusionExplosion",
	selfdestructcountdown = 1,
	transportbyenemy = false,
	unitname = "lootboxbronze",
	reclaimable = true,
	customparams = {
	techlevel = 4,
},
},

 -- Alternative Energy ----------------
 armgeo = {
	energycost = 9500,
	metalcost = 560,
	buildtime = 700,
	energymake = 1500,
	energystorage = 300,
	health = 2500,
	customparams = {
		techlevel = 1,
	},
},
armgmm ={
	energycost = 9500,
	metalcost = 860,
	buildtime = 10500,
	energymake = 5500,
	energystorage = 1000,
	damagemodifier = 0.75,
	health = 4500,
	customparams = {
		techlevel = 2,
	},
},
armageo = {
	energycost = 37000,
	metalcost = 2500,
	buildtime = 33300,
	energymake = 20500,
	energystorage = 30000,
	health = 3600,
	customparams = {
		energymultiplier = 10,
		techlevel = 3,
	},
},
corafus = {
	energycost = 40500,
	metalcost = 9000,
	buildtime = 7500,
	damagemodifier = 0.8,
	energymake = 40500,
	energystorage = 50500,
	metalmake = 100,
	explodeas = "fusionExplosion",
	selfdestructas = "fusionExplosionSelfd",
	footprintx = 7,
	footprintz = 7,
	health = 5500,
	customparams = {
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		techlevel = 4,
	},
},
