		-- -------------- Metal -----------------------------
cormakr = {
	energycost = 1250,
	metalcost = 100,
	buildtime = 1500,
	health = 500,
	explodeas = "metalmaker",
	selfdestructas = "metalmakerSelfd",
	customparams = {
		energyconv_capacity = 100,
		energyconv_efficiency = 1/75,
	},
},
armmakr = {
	energycost = 5500,
	metalcost = 10,
	buildtime = 2500,
	health = 300,
	explodeas = "advmetalmaker",
	selfdestructas = "advmetalmakerSelfd",
	customparams = {
		energyconv_capacity = 2500,
		energyconv_efficiency = 1/50,
		techlevel = 2,
	},
},
cormmkr = {
	energycost = 10500,
	metalcost = 500,
	buildtime = 15500,
	health = 5000,
	explodeas = "metalmaker",
	selfdestructas = "metalmakerSelfd",
	customparams = {
		energyconv_capacity = 1000,
		energyconv_efficiency = 1/60,
		techlevel = 3,
	},
},
armmmkr = {
	energycost = 40500,
	metalcost = 300,
	buildtime = 10500,
	health = 900,
	explodeas = "advmetalmaker",
	selfdestructas = "advmetalmakerSelfd",
	customparams = {
		energyconv_capacity = 10000,
		energyconv_efficiency = 1/40,
		techlevel = 4,
	},
},

		------------------ Safe Energy -----------------------------

coradvsol = {
	energycost = 1000,
	metalcost = 100,
	buildtime = 500,
	energymake = 100,
	energystorage = 100,
	health = 1200,
},
lootboxplatinum = {
	energycost = 25000,
	metalcost = 375,
	buildtime = 1000,
	cantbetransported = false,
	capturable = false,
	energymake = 400,
	explodeas = "lootboxExplosion1",
	icontype = "lootbox",
	health = 33500,
	speed = 0,
	metalmake = 20,
	movementclass = "HOVER3",
	movestate = 0,
	selfdestructas = "lootboxExplosion1",
	selfdestructcountdown = 9,
	transportbyenemy = false,
	unitname = "Experimental Safe Fusion Reactor",
	reclaimable = true,
	customparams = {
		techlevel = 2,
	},
},
lootboxgold = {
	energycost = 25000,
	metalcost = 375,
	buildtime = 1000,
	cantbetransported = false,
	capturable = false,
	energymake = 400,
	explodeas = "lootboxExplosion1",
	icontype = "lootbox",
	health = 33500,
	speed = 0,
	metalmake = 20,
	movementclass = "HOVER3",
	movestate = 0,
	selfdestructas = "lootboxExplosion1",
	selfdestructcountdown = 9,
	transportbyenemy = false,
	unitname = "Safe Fusion Reactor",
	reclaimable = true,
	customparams = {
		techlevel = 3,
	},
},

armfus = {
	energycost = 5500,
	metalcost = 2000,
	buildtime = 10500,
	energymake = 5500,
	energystorage = 5000,
	health = 7000,
	damagemodifier = 0.5,
	footprintx = 6,
	footprintz = 3,
	customparams = {
		techlevel = 4,
	},
},


		------------------ Volatile Energy -----------------------------

freefusion = {
    unitrestricted = 10,
	energycost = 2000,
	metalcost = 200,
	buildtime = 100,
	energymake = 1000,
	energystorage = 10000,
	metalmake = 10,
	explodeas = "fusionExplosion",
	footprintx = 6,
	footprintz = 6,
	health = 100,
},
corfus = {
	energycost = 80500,
	metalcost = 3000,
	buildtime = 8500,
	energymake = 20500,
	energystorage = 10000,
	footprintx = 6,
	footprintz = 6,
	health = 3000,
	damagemodifier = 1.15,
	customparams = {
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		techlevel = 2,
	},
},
armafus = {
	energycost = 300500,
	metalcost = 6000,
	buildtime = 35500,
	energymake = 70500,
	energystorage = 100000,
	explodeas = "advancedFusionExplosion",
	footprintx = 7,
	footprintz = 7,
	health = 2000,
	damagemodifier = 1.15,
	selfdestructas = "advancedFusionExplosionSelfd",
	customparams = {
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		techlevel = 3,
	},
},
lootboxbronze = {
	energycost = 25000,
	metalcost = 375,
	buildtime = 1000,
	cantbetransported = false,
	capturable = false,
	energymake = 400,
	explodeas = "lootboxExplosion1",
	icontype = "lootbox",
	health = 33500,
	speed = 0,
	metalmake = 20,
	movementclass = "HOVER3",
	movestate = 0,
	selfdestructas = "lootboxExplosion1",
	selfdestructcountdown = 9,
	transportbyenemy = false,
	unitname = "Micro Singularity Manipulator",
	reclaimable = true,
	customparams = {
	techlevel = 4,
},
},

 -- Alternative Energy ----------------
 armgeo = {
	energycost = 13000,
	metalcost = 560,
	buildtime = 13100,
	energymake = 300,
	energystorage = 1000,
	health = 1940,
},
 armwint2 = {
	energycost = 1750,
	metalcost = 200,
	buildtime = 10000,
	energystorage = 5,
	health = 1960,
	windgenerator = 500,
	customparams = {
		energymultiplier = 10,
		techlevel = 2,
	},
},
armageo = {
	energycost = 27000,
	metalcost = 1600,
	buildtime = 33300,
	energymake = 1250,
	energystorage = 12000,
	health = 3600,
	customparams = {
		energymultiplier = 10,
		techlevel = 3,
	},
},
corafus = {
	energycost = 150500,
	metalcost = 9000,
	buildtime = 40500,
	damagemodifier = 0.50,
	energymake = 40500,
	energystorage = 100000,
	explodeas = "fusionExplosion",
	footprintx = 7,
	footprintz = 7,
	health = 100000,
	selfdestructas = "fusionExplosionSelfd",
	customparams = {
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		techlevel = 4,
	},
},