corscavdtm = {
	buildcostenergy = 1550,
	buildcostmetal = 290,
	buildtime = 4419,
	canrepeat = false,
	damagemodifier = 0.25,
	maxdamage = 1610,
	weapondefs = {
		cormh_weapon = {
			areaofeffect = 80,
			edgeeffectiveness = 0.15,
			firestarter = 100,
			flighttime = 10,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			metalpershot = 0,
			range = 500,
			reloadtime = 5,
			tolerance = 4000,
			turnrate = 15000,
			weaponacceleration = 70,
			weapontimer = 2.9,
			weapontype = "StarburstLauncher",
			weaponvelocity = 480,
			damage = {
				default = 550,
				subs = 200,
			},
		},
	},
},

corscavdtl = {
	buildcostenergy = 1600,
	buildcostmetal = 340,
	buildtime = 4638,
	damagemodifier = 0.25,
	maxdamage = 1330,
	weapondefs = {
		dclaw = {
			areaofeffect = 8,
			beamttl = 1,
			burst = 10,
			burstrate = 0.03333,
			duration = 1,
			firestarter = 50,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			intensity = 24,
			range = 440,
			reloadtime = 1.13333,
			thickness = 1.5,
			turret = true,
			weaponvelocity = 450,
			customparams = {
				spark_ceg = "genericshellexplosion-splash-lightning",
				spark_forkdamage = "0.33",
				spark_maxunits = "2",
				spark_range = "60",
			},
			damage = {
				bombers = 2.5,
				commanders = 39,
				default = 21,
				fighters = 2.5,
				vtol = 2.5,
			},
		},
	},
},

corscavdtf = {
	buildcostenergy = 1550,
	buildcostmetal = 290,
	buildtime = 4419,
	damagemodifier = 0.25,
	idleautoheal = 10,
	idletime = 900,
	maxdamage = 1610,
	weapondefs = {
		dmaw = {
			areaofeffect = 64,
			burst = 22,
			burstrate = 0.03333,
			edgeeffectiveness = 0.15,
			firestarter = 100,
			flamegfxtime = 1,
			intensity = 0.75,
			name = "Pop-up anti-swarm AoE flamethrower",
			noselfdamage = true,
			proximitypriority = 3,
			range = 410,
			reloadtime = 1.1,
			sizegrowth = 0.7,
			sprayangle = 100,
			weaponvelocity = 300,
			damage = {
				commanders = 12,
				default = 16,
				subs = 5,
			},
		},
	},
},




armjuno = {
	buildcostenergy = 17000,
	buildcostmetal = 640,
	buildtime = 21833,
	footprintx = 4,
	footprintz = 4,
	maxdamage = 2350,
	customparams = {
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
	},
	weapondefs = {
		juno_pulse = {
			areaofeffect = 1400,
			craterareaofeffect = 1400,
			energypershot = 12000,
			metalpershot = 200,
			name = "Anti radar/minefield/jammer magnetic impulse rocket",
			range = 32000,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 8,
			smoketime = 45,
			smokesize = 14.0,
			smokecolor = 0.7,
			stockpile = true,
			stockpiletime = 75,
			tolerance = 4000,
			weaponacceleration = 75,
			weapontimer = 4,
			weapontype = "StarburstLauncher",
			customparams = {
				lups_noshockwave = 1,
				nofire = true,
			},
		},
	},
},



corflak = {
	airsightdistance = 1000,
	buildcostenergy = 14000,
	buildcostmetal = 850,
	buildtime = 20112,
	maxdamage = 1840,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		armflak_gun = {
			accuracy = 1000,
			areaofeffect = 172,
			craterareaofeffect = 192,
			name = "Heavy g2a flak cannon",
			range = 775,
			reloadtime = 0.53333,
			weaponvelocity = 1600,
			damage = {
				default = 125,
				bombers = 250,
				fighters = 500,
				vtol = 250,
			},
			rgbcolor = {
				[1] = 1,
				[2] = 0.33,
				[3] = 0.7,
			},
		},
	},
},


cormadsam = {
	airsightdistance = 850,
	buildcostenergy = 6100,
	buildcostmetal = 315,
	buildtime = 5237,
	energyuse = 5,
	maxdamage = 2800,
	weapondefs = {
		madsam_missile = {
			areaofeffect = 16,
			edgeeffectiveness = 0.15,
			flighttime = 2.5,
			range = 840,
			reloadtime = 0.4,
			startvelocity = 800,
			tolerance = 9950,
			tracks = true,
			turnrate = 68000,
			weaponacceleration = 160,
			weapontimer = 2,
			weapontype = "MissileLauncher",
			weaponvelocity = 1250,
			damage = {
				bombers = 76,
				fighters = 76,
				vtol = 76,
			},
		},
	},
},

armbeamer = {
	buildcostenergy = 1500,
	buildcostmetal = 190,
	buildtime = 5324,
	cantbetransported = false,
	mass = 7500,
	maxdamage = 1430,
	sightdistance = 475,
	weapondefs = {
		armbeamer_weapon = {
			areaofeffect = 8,
			beamdecay = 0.05,
			beamtime = 0.1,
			beamttl = 1,
			corethickness = 0.233,
			edgeeffectiveness = 0.15,
			energypershot = 6,
			explosiongenerator = "custom:laserhit-beamer",
			firestarter = 30,
			laserflaresize = 9.35,
			name = "Anti-swarm constant wave g2g laser",
			range = 480,
			reloadtime = 0.1,
			rgbcolor = "0 0 1",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "beamershot2",
			soundtrigger = 1,
			targetmoveerror = 0.05,
			thickness = 2.4,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 1000,
			damage = {
				bombers = 2,
				default = 26.6,
				fighters = 2,
				vtol = 2,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "armbeamer_WEAPON",
			onlytargetcategory = "NOTSUB",
			fastautoretargeting = true,
		},
	},
},

corhlt = {
	buildcostenergy = 4700,
	buildcostmetal = 480,
	buildtime = 12650,
	energystorage = 200,
	maxdamage = 2750,
	sightdistance = 455,
	weapondefs = {
		cor_laserh1 = {
			areaofeffect = 14,
			beamtime = 0.15,
			corethickness = 0.2,
			edgeeffectiveness = 0.15,
			energypershot = 50,
			explosiongenerator = "custom:laserhit-medium-green",
			laserflaresize = 8.8,
			name = "High energy g2g laser",
			range = 620,
			reloadtime = 1.2,
			rgbcolor = "0 1 0",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "Lasrmas2",
			soundtrigger = 1,
			targetmoveerror = 0.2,
			thickness = 2.7,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 2250,
			damage = {
				bombers = 35,
				default = 261,
				fighters = 35,
				vtol = 35,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "COR_LASERH1",
			onlytargetcategory = "NOTSUB",
			fastautoretargeting = true,
		},
	},
},

-- Arm Pitbull Small Popup Gauss Canmon
armpb = {
	buildcostenergy = 14000,
	buildcostmetal = 680,
	buildtime = 14961,
	cloakcost = 16,
	damagemodifier = 0.5,
	maxdamage = 2800,
	mincloakdistance = 55,
	sightdistance = 598,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		armpb_weapon = {
			areaofeffect = 24,
			edgeeffectiveness = 0.15,
			name = "Pop-up heavy g2g gauss cannon",
			range = 730,
			reloadtime = 1.6,
			separation = 1.8,
			nogap = false,
			sizeDecay = 0.06,
			stages = 14,
			alphaDecay = 0.08,
			targetmoveerror = 0.2,
			tolerance = 8000,
			turret = true,
			weapontype = "Cannon",
			weaponvelocity = 800,
			damage = {
				bombers = 26,
				default = 675,
				fighters = 26,
				hvyboats = 472.5,
				subs = 300,
				vtol = 26,
			},
		},
	},
},



leginf = {
	acceleration = 0,
	airsightdistance = 1050,
	brakerate = 0,
	buildcostenergy = 30000,
	buildcostmetal = 2000,
	buildpic = "LEGINF.DDS",
	buildtime = 33000,
	canmove = true,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE TANK EMPABLE",
	collisionvolumeoffsets = "0 -5 3",
	collisionvolumescales = "37 51 51",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "hugeexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	idleautoheal = 5,
	idletime = 1800,
	leavetracks = true,
	mass = 5001,
	maxdamage = 3650,
	--maxreversevelocity = 0.762,
	maxslope = 14,
	maxvelocity = 1.25,
	maxwaterdepth = 15,
	movementclass = "HTANK4",
	nochasecategory = "VTOL",
	objectname = "Units/leginf.s3o",
	script = "Units/LEGINF.cob",
	seismicsignature = 0,
	selfdestructas = "hugeExplosionGenericSelfd",
	sightdistance = 351,
	trackoffset = -8,
	trackstrength = 8,
	tracktype = "corwidetracks",
	trackwidth = 50,
	turninplace = true,
	turninplaceanglelimit = 90,
	turninplacespeedlimit = 0.95832,
	turnrate = 169.39999,
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armason_aoplane.dds",
		buildinggrounddecalsizey = 2,
		buildinggrounddecalsizex = 2,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "corvehicles/t2",
		techlevel = 2,
	},
	weapondefs = {
		rapidnapalm = {
			areaofeffect = 150,
			cegtag = "burnflame",
			colormap = "0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008",
			craterareaofeffect = 90,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:burnblack",
			flamegfxtime = 1,
			gravityaffected = "true",
			mygravity = 0.08,
			name = "HeavyCannon",
			noselfdamage = true,
			projectiles = 1,
			range = 1100,
			reloadtime = 0.6,
			rgbcolor = "1 0.25 0.1",
			size = 4,
			sprayangle = 2500,
			turret = true,
			weapontype = "Cannon",
			weaponvelocity = 300,
			damage = {
				bombers = 10,
				default = 30,
				fighters = 10,
				subs = 10,
				vtol = 10,
			},
		},
	},
},

--  Underwater Sonar, will be advanced vision ---

armason = {
	acceleration = 0,
	activatewhenbuilt = true,
	brakerate = 0,
	buildangle = 8192,
	buildcostenergy = 2600,
	buildcostmetal = 170,
	buildpic = "ARMASON.DDS",
	buildtime = 6152,
	canattack = false,
	canrepeat = false,
	category = "ALL UNDERWATER NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	damagemodifier = 0.46,
	explodeas = "mediumBuildingexplosiongeneric-uw",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 2350,
	maxslope = 10,
	minwaterdepth = 0,
	maxwaterdeapth = 24
	objectname = "Units/ARMASON.s3o",
	onoffable = true,
	sightdistance = 2500,
	sonardistance = 0,
	customparams = {
		subfolder = "armbuildings/seautil",
		techlevel = 2,
	},
},

-- Arm Bomb Resistant 

armcir = {
	acceleration = 0,
	airsightdistance = 1060,
	brakerate = 0,
	buildangle = 65536,
	buildcostenergy = 7300,
	buildcostmetal = 750,
	buildpic = "ARMCIR.DDS",
	buildtime = 12000,
	canrepeat = false,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "50 77 50",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 4450,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMCIR.s3o",
	script = "Units/ARMCIR.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 380,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armcir_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'aa',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "50 77 50",
			collisionvolumetype = "cylY",
			damage = 1500,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 370,
			object = "Units/armcir_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 750,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 150,
			object = "Units/arm3X3B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "twrturn3",
		},
		select = {
			[1] = "twrturn3",
		},
	},
	weapondefs = {
		arm_cir = {
			areaofeffect = 48,
			avoidfeature = false,
			burnblow = true,
			burst = 4,
			burstrate = 0.26667,
			burnblow = true,
			canattackground = false,
			cegtag = "missiletrailaa",
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-tiny-aa",
			firestarter = 20,
			flighttime = 2.3,
			impulseboost = 0,
			impulsefactor = 0,
			model = "cormissile.s3o",
			name = "Rapid-fire long-range g2a missile barrel",
			noselfdamage = true,
			projectiles = 1,
			proximitypriority = -2,
			range = 1125,
			reloadtime = 1.6,
			smoketrail = true,
			smokePeriod = 8,
			smoketime = 12,
			smokesize = 5.4,
			smokecolor = 0.95,
			smokeTrailCastShadow = false,
			castshadow = false,
			soundhit = "xplosml2",
			soundhitwet = "splshbig",
			soundstart = "rocklit1",
			soundtrigger = true,
			texture1 = "null",
			texture2 = "smoketrailaa3",
			tolerance = 100000,
			tracks = true,
			turnrate = 42000,
			turret = true,
			startvelocity = 250,
			weaponacceleration = 300,
			weapontype = "MissileLauncher",
			weaponvelocity = 1300,
			damage = {
				bombers = 265,
				fighters = 215,
				vtol = 170,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "ARM_CIR",
			onlytargetcategory = "VTOL",
			fastautoretargeting = true,
		},
	},
},


cormwall = {
	maxacc = 0,
	energycost = 4800, --was 4850
	metalcost = 1020, --was 485
	buildpic = "CORMWALL.DDS",
	buildtime = 14000, -- was 12214
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "32 50 32",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	damagemodifier = 0.25,
	decoyfor = "corfort",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 10,
	idletime = 900,
	levelground = false,
	mass = 10000000000,
	health = 5320, --was 4450, --1/2 of corfort
	maxslope = 24,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/CORMWALL.s3o",
	script = "Units/CORMWALL.cob",
	seismicsignature = 0,
	selfdestructas = "tinyBuildingExplosionGenericSelfd",
	sightdistance = 330,
	stealth = true,
	turnrate = 0,
	upright = true,
	yardmap = "ffff",
	customparams = {
		neutral_when_closed = true,
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corfort_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		decoyfor = "armfort",
		model_author = "Beherith",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			autoreclaimable = 0,
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -3 0",
			collisionvolumescales = "32 50 32",
			collisionvolumetype = "CylY",
			damage = 540,
			energy = 0,
			featuredead = "ROCKTEETH",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 205,
			object = "Units/corfort.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		rockteeth = {
			animating = 0,
			animtrans = 0,
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 500,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2,
			object = "Units/cor1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:flamestreamxm",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4-fire",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed2",
		},
		select = {
			[1] = "servmed2",
		},
	},
	weapondefs = {
		-- banisher = {
		-- 	areaofeffect = 128,
		-- 	avoidfeature = false,
		-- 	burnblow = true,
		-- 	burst = 7,
		-- 	burstrate = 0.3333,
		-- 	cegtag = "missiletraillarge-red",
		-- 	craterareaofeffect = 128,
		-- 	craterboost = 0,
		-- 	cratermult = 0,
		-- 	edgeeffectiveness = 0.55,
		-- 	explosiongenerator = "custom:genericshellexplosion-large-bomb",
		-- 	firestarter = 20,
		-- 	flighttime = 7.4,
		-- 	impulseboost = 0.123,
		-- 	impulsefactor = 0.123,
		-- 	model = "banishermissile.s3o",
		-- 	name = "Banisher",
		-- 	noselfdamage = true,
		-- 	range = 300,
		-- 	reloadtime = 38, --18
		-- 	smoketrail = true,
		-- 	smokePeriod = 7, --7
		-- 	smoketime = 24, --48
		-- 	smokesize = 11.3,
		-- 	smokecolor = 0.82,
		-- 	smokeTrailCastShadow = false,
		-- 	soundhit = "corban_b",
		-- 	soundhitwet = "splsmed",
		-- 	soundstart = "corban_a",
		-- 	startvelocity = 240,
		-- 	texture1 = "null",
		-- 	texture2 = "railguntrail",
		-- 	tolerance = 9000,
		-- 	tracks = true,
		-- 	trajectoryheight = 0.45,
		-- 	turnrate = 60000,
		-- 	turret = true,
		-- 	weaponacceleration = 220,
		-- 	weapontimer = 0.25,
		-- 	weapontype = "StarburstLauncher",
		-- 	weaponvelocity = 650,
		-- 	damage = {
		-- 		default = 750,
		-- 	},
		-- },
		exp_heavyrocket = {
			areaofeffect = 96,
			avoidfeature = false,
			burst = 7,
			burstrate = 0.1,
			cegtag = "missiletrailsmall-red",
			craterboost = 0,
			cratermult = 0,
			dance = 24,
			edgeeffectiveness = 0.65,
			explosiongenerator = "custom:genericshellexplosion-catapult",
			firestarter = 70,
			flighttime = 3.2,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			metalpershot = 0,
			model = "catapultmissile.s3o",
			movingaccuracy = 600,
			name = "CatapultRockets",
			noselfdamage = true,
			proximitypriority = -1,
			range = 675, --1/2 of corcat
			reloadtime = 15,
			smoketrail = true,
			smokePeriod = 4,
			smoketime = 16,
			smokesize = 8.5,
			smokecolor = 0.5,
			smokeTrailCastShadow = false,
			soundhit = "rockhit",
			soundhitwet = "splsmed",
			soundstart = "rapidrocket3",
			startvelocity = 165,
			texture1 = "null",
			texture2 = "smoketrailbar",
			trajectoryheight = 3,
			turnrate = 5000,
			turret = true,
			weaponacceleration = 100,
			weapontimer = 6,
			weapontype = "MissileLauncher",
			weaponvelocity = 530,
			wobble = 2000,
			damage = {
				default = 450,
			},
		},
	},
	weapons = {
		[1] = {
			def = "exp_heavyrocket",
			onlytargetcategory = "SURFACE",
			fastautoretargeting = true,
		},
	},
},



corvipe = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 8192,
	energycost = 14000,
	metalcost = 730,
	buildpic = "CORVIPE.DDS",
	buildtime = 15000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	damagemodifier = 0.5,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3000,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/CORVIPE.s3o",
	script = "Units/CORVIPE.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 546,
	usepiececollisionvolumes = 1,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corvipe_aoplane.dds",
		buildinggrounddecalsizey = 4.7,
		buildinggrounddecalsizex = 4.7,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-2.7282333374 -4.31274414048e-05 -3.87004852295",
			collisionvolumescales = "42.4275054932 38.4097137451 38.8498077393",
			collisionvolumetype = "Box",
			damage = 1631,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 380,
			object = "Units/corvipe_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 408,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 61,
			object = "Units/cor2X2F.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak2",
		uncloak = "kloak2un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed1",
		},
		select = {
			[1] = "servmed1",
		},
	},
	weapondefs = {
		vipersabot = {
			areaofeffect = 24,
			avoidfeature = false,
			burnblow = true,
			cegtag = "missiletrailviper",
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-medium-bomb",
			firestarter = 70,
			flighttime = 1.05,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			model = "cormissile3fast.s3o",
			name = "Heavy g2g sabot rocket launcher",
			noselfdamage = true,
			range = 730,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 33,
			smokesize = 10,
			smokecolor = 0.8,
			smokeTrailCastShadow = false,
			soundhit = "SabotHit",
			soundhitwet = "splshbig",
			soundstart = "SabotFire",
			startvelocity = 570,
			targetmoveerror = 0.2,
			smokeperiod = 5,
			castshadow = true,
			texture1 = "null",
			texture2 = "railguntrail",
			tolerance = 8000,
			tracks = true,
			turnrate = 6000,
			turret = true,
			weaponacceleration = 400,
			weapontimer = 0.1,
			weapontype = "MissileLauncher",
			weaponvelocity = 950,
			damage = {
				default = 825,
				hvyboats = 577.5,
				subs = 5,
				vtol = 26,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "VIPERSABOT",
			onlytargetcategory = "SURFACE",
		},
	},
},




armclaw = {
	maxacc = 0,
	buildangle = 8192,
	energycost = 1600,
	metalcost = 340,
	buildpic = "ARMCLAW.DDS",
	buildtime = 4650,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "32 22 32",
	collisionvolumetype = "CyLy",
	corpse = "DEAD",
	damagemodifier = 0.25,
	decoyfor = "armdrag",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 10,
	idletime = 900,
	levelground = false,
	mass = 10000000000,
	health = 1330,
	maxslope = 18,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/ARMCLAW.s3o",
	radardistancejam = 8,
	script = "Units/ARMCLAW.cob",
	seismicsignature = 0,
	selfdestructas = "tinyBuildingExplosionGenericSelfd",
	sightdistance = 440,
	stealth = true,
	turnrate = 0,
	upright = true,
	yardmap = "ffff",
	customparams = {
		neutral_when_closed = true,
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armclaw_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		decoyfor = "armdrag",
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	featuredefs = {
		dead = {
			autoreclaimable = 0,
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 2.37060546837e-06 -0.0625",
			collisionvolumescales = "32.0 17.7499847412 31.375",
			collisionvolumetype = "Box",
			damage = 540,
			energy = 0,
			featuredead = "ROCKTEETH",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 205,
			object = "Units/armdrag.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		rockteeth = {
			animating = 0,
			animtrans = 0,
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 500,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2,
			object = "Units/arm1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-lightning",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3-lightning",
			[2] = "deathceg4-lightning",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed2",
		},
		select = {
			[1] = "servmed2",
		},
	},
	weapondefs = {
		dclaw = {
			areaofeffect = 8,
			avoidfeature = false,
			beamttl = 1,
			burst = 10,
			burstrate = 0.03333,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			duration = 1,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-medium-lightning2",
			firestarter = 50,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			intensity = 24,
			name = "Close-quarters g2g lightning turret",
			noselfdamage = true,
			range = 440,
			reloadtime = 1.13333,
			rgbcolor = "0.5 0.5 1",
			soundhit = "lashit",
			soundhitwet = "sizzle",
			soundstart = "lghthvy1",
			soundtrigger = true,
			thickness = 1.5,
			turret = true,
			weapontype = "LightningCannon",
			weaponvelocity = 450,
			customparams = {
				spark_ceg = "genericshellexplosion-splash-lightning",
				spark_forkdamage = "0.33",
				spark_maxunits = "2",
				spark_range = "60",
			},
			damage = {
				commanders = 31.5,
				default = 21,
				vtol = 2.5,
			},
		},
	},
	weapons = {
		[1] = {
			def = "DCLAW",
			onlytargetcategory = "SURFACE",
			fastautoretargeting = true,
		},
	},
},




armbrtha = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 32700,
	energycost = 64000,
	metalcost = 4500,
	buildpic = "ARMBRTHA.DDS",
	buildtime = 85000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -20",
	collisionvolumescales = "48 90 48",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "hugeBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 4450,
	maxslope = 12,
	maxwaterdepth = 0,
	objectname = "Units/ARMBRTHA.s3o",
	script = "Units/ARMBRTHA.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 273,
	usepiececollisionvolumes = 1,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armbrtha_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		canareaattack = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "3.15924835205 -0.787798413086 6.6563873291",
			collisionvolumescales = "81.6838531494 113.772003174 72.5632324219",
			collisionvolumetype = "Box",
			damage = 2520,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 40,
			hitdensity = 100,
			metal = 2720,
			object = "Units/armbrtha_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1260,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 1088,
			object = "Units/arm3X3E.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-huge",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servlrg3",
		},
		select = {
			[1] = "servlrg3",
		},
	},
	weapondefs = {
		lrpc = {
			accuracy = 300,
			areaofeffect = 135,
			avoidfeature = false,
			avoidfriendly = false,
			cegtag = "arty-huge",
			collidefriendly = false,
			craterareaofeffect = 116,
			craterboost = 0.1,
			cratermult = 0.1,
			edgeeffectiveness = 0.15,
			energypershot = 5000,
			explosiongenerator = "custom:genericshellexplosion-huge",
			gravityaffected = "true",
			heightboostfactor = 8,
			impulseboost = 0.5,
			impulsefactor = 0.5,
			leadbonus = 0,
			model = "artshell-large.s3o",
			name = "Long range g2g plasma cannon",
			noselfdamage = true,
			range = 4650,
			reloadtime = 13.2,
			soundhit = "lrpcexplo",
			soundhitwet = "splshbig",
			soundstart = "lrpcshot3",
			soundhitvolume = 38,
			soundstartvolume = 24,
			turret = true,
			weapontype = "Cannon",
			weaponvelocity = 1100,
			damage = {
				default = 1625,
				shields = 812,
				subs = 500,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "LRPC",
			onlytargetcategory = "SURFACE",
		},
	},
},




legministarfall = {
	acceleration = 0,
	brakerate = 0,
	buildangle = 29096,
	buildcostenergy = 60000,
	buildcostmetal = 2000,
	buildpic = "LEGSTARFALL.DDS",
	buildtime = 65000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "52 65 52",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "hugeBuildingexplosiongeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 7000,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/scavbuildings/legministarfall.s3o",
	script = "Units/scavbuildings/legministarfall.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 700,
	--usepiececollisionvolumes = 1,
	yardmap = "ooo ooo ooo",
	customparams = {
		usebuildinggrounddecal = false,
		unitgroup = 'weapon',
		model_author = "Hornet",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 60 45",
			collisionvolumetype = "Box",
			damage = 3000,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			hitdensity = 100,
			metal = 6000,
			object = "Units/scavbuildings/legministarfall_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 1500,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 3000,
			object = "Units/arm3X3A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-large",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servlrg3",
		},
		select = {
			[1] = "servlrg3",
		},
	},
	weapondefs = {
		ministarfire = {
			accuracy = 0,
			areaofeffect = 55,
			avoidfeature = false,
			avoidfriendly = false,
			avoidground = false,
			burst = 61,
			burstrate = 0.01,
			
			sprayangle = 400,
			highTrajectory = 1,
			
			cegtag = "ministarfire",
			collidefriendly = false,
			craterboost = 0.1,
			cratermult = 0.1,
			edgeeffectiveness = 0.95,
			energypershot = 20000,
			
			explosiongenerator = "custom:ministarfire-explosion",
			gravityaffected = "true",
			impulseboost = 0.5,
			impulsefactor = 0.5,
			name = "Starfire Barrage Launcher",
			noselfdamage = true,
			range = 1400,
			reloadtime = 15,
			rgbcolor = "0.7 0.7 1.0 0.7 1.0 1.0 1.0 0.7",
			soundhit = "xplomed3",
			soundhitwet = "splshbig",
			soundstart = "cannon2",
			soundhitvolume = 20,
			turret = true,
			weapontimer = 14,
			weapontype = "Cannon",
			weaponvelocity = 500,
			damage = {
				default = 125,
				shields = 110,
				subs = 50,
			},
		},
	
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "ministarfire",
			onlytargetcategory = "SURFACE",
		},
	},
},




armemp = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 8192,
	energycost = 29000,
	metalcost = 1600,
	buildpic = "ARMEMP.DDS",
	buildtime = 79300,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 5 0",
	collisionvolumescales = "80 30 60",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3350,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMEMP.s3o",
	script = "Units/ARMEMP.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 455,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armemp_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'emp',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
		yardmap = "ooooooo ooooooo ooooooo ooooooo ooooooo ooooooo",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "80 30 60",
			collisionvolumetype = "Box",
			damage = 1800,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			hitdensity = 100,
			metal = 976,
			object = "Units/armemp_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 900,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 390,
			object = "Units/arm3X3A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servroc1",
		},
		select = {
			[1] = "servroc1",
		},
	},
	weapondefs = {
		armemp_weapon = {
			areaofeffect = 312,
			avoidfeature = false,
			avoidfriendly = false,
			cegtag = "cruisemissiletrail-emp",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			commandfire = true,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 1,
			energypershot = 15644,
			explosiongenerator = "custom:genericshellexplosion-huge-lightning",
			firestarter = 0,
			flighttime = 400,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 500,
			model = "cortronmissile.s3o",
			name = "Heavy long-range g2g EMP starburst rocket",
			noselfdamage = true,
			paralyzer = true,
			paralyzetime = 35,
			range = 3650,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 8,
			smoketime = 60,
			smokesize = 7,
			smokecolor = 0.9,
			smokeTrailCastShadow = false,
			soundhit = "emgpuls1",
			--soundhitwet = "splslrg",
			soundstart = "mismed1emp1",
			stockpile = true,
			stockpiletime = 65,
			texture1 = "null",
			texture2 = "smoketrailbar",
			texture3 = "null",
			tolerance = 4000,
			turnrate = 10000,
			weaponacceleration = 150,
			weapontimer = 3,
			weapontype = "StarburstLauncher",
			weaponvelocity = 1200,
			damage = {
				default = 50000,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "ARMEMP_WEAPON",
			onlytargetcategory = "NOTSUB",
		},
	},
},





armflak = {
	maxacc = 0,
	airsightdistance = 1000,
	maxdec = 0,
	buildangle = 8192,
	energycost = 13000,
	metalcost = 820,
	buildpic = "ARMFLAK.DDS",
	buildtime = 19000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "36 55 36",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1750,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "ALL",
	objectname = "Units/ARMFLAK.s3o",
	script = "Units/ARMFLAK.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 525,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armflak_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'aa',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-3.8550491333 -3.09570312496e-05 3.13596343994",
			collisionvolumescales = "30.5327911377 31.4515380859 37.50050354",
			collisionvolumetype = "Box",
			damage = 945,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 500,
			object = "Units/armflak_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 473,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 200,
			object = "Units/arm2X2C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-flak",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "twrturn3",
		},
		select = {
			[1] = "twrturn3",
		},
	},
	weapondefs = {
		armflak_gun = {
			accuracy = 1000,
			areaofeffect = 172,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			canattackground = false,
			cegtag = "flaktrailaa",
			collidefriendly = false,
			craterareaofeffect = 192,
			craterboost = 0,
			cratermult = 0,
			cylindertargeting = 1,
			edgeeffectiveness = 1,
			explosiongenerator = "custom:flak",
			gravityaffected = "true",
			impulseboost = 0,
			impulsefactor = 0,
			mygravity = 0.01,
			name = "Heavy g2a flak cannon",
			noselfdamage = true,
			predictboost = 1,
			range = 775,
			reloadtime = 0.53333,
			--size = 4.5,
			--sizedecay = 0.08,
			smoketrail = false,
			soundhit = "flakhit2",
			soundhitwet = "splslrg",
			soundstart = "flakfire",
			soundhitvolume = 7.5,
			soundstartvolume = 9,
			stages = 0,
			turret = true,
			weapontimer = 1,
			weapontype = "Cannon",
			weaponvelocity = 1600,
			damage = {
				--default = 125,
				vtol = 250,
			},
			rgbcolor = {
				[1] = 1,
				[2] = 0.33,
				[3] = 0.7,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
			def = "ARMFLAK_GUN",
			onlytargetcategory = "VTOL",
		},
	},
},




armmercury = {
    maxacc = 0,
    activatewhenbuilt = true,
    airsightdistance = 2400,
    maxdec = 0,
    energycost = 33000,
    metalcost = 1600,
    buildpic = "ARMMERCURY.DDS",
    buildtime = 28000,
    canrepeat = false,
    category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
    collisionvolumeoffsets = "-1 -1 0",
    collisionvolumescales = "60 78 60",
    collisionvolumetype = "CylY",
    corpse = "DEAD",
    explodeas = "largeBuildingExplosionGeneric",
    footprintx = 4,
    footprintz = 4,
    icontype = "building",
    idleautoheal = 5,
    idletime = 1800,
    health = 1670,
    maxslope = 20,
    maxwaterdepth = 0,
    objectname = "Units/ARMMERCURY.s3o",
    script = "Units/ARMMERCURY.cob",
    seismicsignature = 0,
    selfdestructas = "largeBuildingExplosionGenericSelfd",
    sightdistance = 600,
    yardmap = "oooooooooooooooo",
    customparams = {
        usebuildinggrounddecal = true,
        buildinggrounddecaltype = "decals/armmercury_aoplane.dds",
        buildinggrounddecalsizey = 6,
        buildinggrounddecalsizex = 6,
        buildinggrounddecaldecayspeed = 30,
        unitgroup = 'aa',
        model_author = "Beherith",
        normaltex = "unittextures/Arm_normal.dds",
        removewait = true,
        subfolder = "armbuildings/landdefenceoffence",
        techlevel = 2,
    },
    featuredefs = {
        dead = {
            blocking = true,
            category = "corpses",
            collisionvolumeoffsets = "0 0 0",
            collisionvolumescales = "60 78 60",
            collisionvolumetype = "CylY",
            damage = 900,
            energy = 0,
            featuredead = "HEAP",
            featurereclamate = "SMUDGE01",
            footprintx = 3,
            footprintz = 3,
            height = 20,
            hitdensity = 100,
            metal = 1022,
            object = "Units/armmercury_dead.s3o",
            reclaimable = true,
            seqnamereclamate = "TREE1RECLAMATE",
            world = "All Worlds",
        },
        heap = {
            blocking = false,
            category = "heaps",
            collisionvolumescales = "55.0 4.0 6.0",
            collisionvolumetype = "cylY",
            damage = 450,
            energy = 0,
            featurereclamate = "SMUDGE01",
            footprintx = 3,
            footprintz = 3,
            hitdensity = 100,
            metal = 409,
            object = "Units/arm3X3A.s3o",
            reclaimable = true,
            resurrectable = 0,
            seqnamereclamate = "TREE1RECLAMATE",
            world = "All Worlds",
        },
    },
    sfxtypes = {
        pieceexplosiongenerators = {
            [1] = "deathceg2",
            [2] = "deathceg3",
            [3] = "deathceg4",
        },
    },
    sounds = {
        activate = "targon1",
        canceldestruct = "cancel2",
        deactivate = "targoff1",
        underattack = "warning1",
        working = "targsel1",
        count = {
            [1] = "count6",
            [2] = "count5",
            [3] = "count4",
            [4] = "count3",
            [5] = "count2",
            [6] = "count1",
        },
        select = {
            [1] = "targsel1",
        },
    },
    weapondefs = {
        arm_advsam = {
            areaofeffect = 425,
            avoidfeature = false,
            avoidfriendly = false,
            burnblow = true,
            canattackground = false,
            cegtag = "missiletrailaa-large",
            collidefriendly = false,
            craterareaofeffect = 425,
            craterboost = 0,
            cratermult = 0,
            edgeeffectiveness = 0.75,
            energypershot = 1800,
            explosiongenerator = "custom:genericshellexplosion-huge-aa",
            firestarter = 90,
            flighttime = 2.2,
            impulseboost = 0,
            impulsefactor = 0,
            metalpershot = 0,
            model = "corscreamermissile.s3o",
            name = "Heavy long-range g2a guided missile launcher",
            noselfdamage = true,
            proximitypriority = -2,
            range = 2400,
            reloadtime = 1.8,
            smoketrail = true,
            smokePeriod = 3,
            smoketime = 24,
            smokesize = 11,
            smokecolor = 0.9,
            smokeTrailCastShadow = false,
            castshadow = false,
            soundhit = "impact",
            soundhitwet = "splslrg",
            soundstart = "aarocket",
            soundhitvolume = 8,
            soundstartvolume = 8,
            sprayangle = 10000,
            startvelocity = 1400,
            stockpile = true,
            stockpiletime = 14,
            texture1 = "null",
            texture2 = "smoketrailaaflak",
            tolerance = 10000,
            tracks = true,
            trajectoryheight = 0.55,
            turnrate = 99000,
            turret = true,
            weaponacceleration = 1000,
            weapontype = "MissileLauncher",
            weaponvelocity = 1850,
            damage = {
                vtol = 750,
                space = 750,
            },
        },
    },
    weapons = {
        [1] = {
            badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
            def = "ARM_ADVSAM",
            onlytargetcategory = "VTOL SPACE",
        },
    },
},

armannit3 = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 450000,
	metalcost = 13500,
	buildpic = "ARMANNIT3.DDS",
	buildtime = 190000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 15 0",
	collisionvolumescales = "81 122 81",
	collisionvolumetype = "BoxY",
	corpse = "DEAD",
	damagemodifier = 0.25,
	energystorage = 3000,
	explodeas = "fusionExplosion",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 72,
	health = 28000,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/scavbuildings/ARMANNIT3.s3o",
	onoffable = true,
	radardistance = 1500,
	radaremitheight = 72,
	script = "Units/ARMANNI.cob",
	seismicsignature = 0,
	selfdestructas = "fusionExplosion",
	sightdistance = 900,
	yardmap = "oooooo oooooo oooooo oooooo oooooo oooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armannit3_aoplane.dds",
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 3,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 1.06567382829e-05 -0.0",
			collisionvolumescales = "62.5 81.7362213135 62.5",
			collisionvolumetype = "Box",
			damage = 1800,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 5820,
			object = "Units/scavbuildings/armannit3_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 900,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 2328,
			object = "Units/arm3X3B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:tachyonshot",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "obli",
		},
		select = {
			[1] = "obli",
		},
	},
	weapondefs = {
		ata = {
			areaofeffect = 16,
			avoidfeature = false,
			beamtime = 1,
			collidefriendly = false,
			corethickness = 0.5,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.30,
			energypershot = 7000,
			explosiongenerator = "custom:laserhit-large-blue",
			firestarter = 90,
			impulseboost = 0,
			impulsefactor = 0,
			largebeamlaser = true,
			laserflaresize = 8,
			name = "Heavy long-range g2g tachyon accelerator beam",
			noselfdamage = true,
			range = 1800,
			reloadtime = 15,
			rgbcolor = "0 0 1",
			scrollspeed = 5,
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "annigun1",
			soundtrigger = 1,
			targetmoveerror = 0.3,
			texture3 = "largebeam",
			thickness = 10,
			tilelength = 150,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 3100,
			damage = {
				commanders = 480,
				default = 48000,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "ATA",
			onlytargetcategory = "SURFACE",
		},
	},
},






legbastion = {
	maxacc= 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 58000,
	metalcost = 4200,
	buildpic = "legbastion.DDS",
	buildtime = 79000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0.0 0.0 0.0",
	collisionvolumescales = "60 150 60",
	collisionvolumetype = "box",
	corpse = "DEAD",
	damagemodifier = 0.25,
	energystorage = 1000,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 5,
	footprintz = 5,
	icontype = "building",
	idleautoheal = 2,
	idletime = 1800,
	losemitheight = 80,
	health = 15000,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "VTOL",
	objectname = "Units/legbastion.s3o",
	onoffable = true,
	radardistance = 1200,
	radaremitheight = 80,
	script = "Units/legbastion.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 780,
	yardmap = "yoo0y o0ooo o0ooo yo0oy",
	customparams = {
		maxrange = 1125,
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corjuno_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Hornet",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 150 60",
			collisionvolumetype = "Box",
			damage = 5400,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			hitdensity = 100,
			metal = 2911,
			object = "Units/legbastion_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 2700,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 1644,
			object = "Units/cor3X3E.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "doom",
		},
		select = {
			[1] = "doom",
		},
	},
	weapondefs = {
		pineappleofdoom = {
			areaofeffect = 120,
			avoidfeature = false,
			avoidfriendly = true,
			beamtime = 1,
			camerashake = 0.1,
			--collidefriendly = false,
			corethickness = 0.4,
			craterareaofeffect = 120,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.45,
			energypershot = 500,
			explosiongenerator = "custom:genericshellexplosion-medium-beam",
			firestarter = 90,
			firetolerance = 300,
			impulseboost = 0,
			impulsefactor = 0,
			laserflaresize = 6,
			name = "Cleansing Light",
			noselfdamage = true,
			predictboost = 0.3,
			proximitypriority = 1,
			range = 1100,
			reloadtime = 2.5,
			rgbcolor = "1 0.5 0",
			rgbcolor2 = "0.9 1.0 0.5",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "heatray3",
			soundstartvolume = 38,
			soundtrigger = 1,
			--sweepfire = true,
			targetmoveerror = 0.001,
			thickness = 5.5,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 1500,
			damage = {
				default = 4500,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "pineappleofdoom",
			onlytargetcategory = "SURFACE",
			--fastautoretargeting = true,
		}
	},
},



armvulc = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 29096,
	energycost = 752000,
	metalcost = 63000,
	buildpic = "ARMVULC.DDS",
	buildtime = 1400000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -45",
	collisionvolumescales = "90 145 90",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "advancedFusionExplosion",
	firestate = 0,
	footprintx = 8,
	footprintz = 8,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 32000,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/ARMVULC.s3o",
	script = "Units/ARMVULC.cob",
	seismicsignature = 0,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 700,
	usepiececollisionvolumes = 1,
	yardmap = "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armvulc_aoplane.dds",
		buildinggrounddecalsizey = 7.5,
		buildinggrounddecalsizex = 7.5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-30.100944519 -5.74996727295 19.3314819336",
			collisionvolumescales = "169.401870728 123.486465454 147.862945557",
			collisionvolumetype = "Box",
			damage = 26000,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 7,
			footprintz = 7,
			height = 20,
			hitdensity = 100,
			metal = 30000,
			object = "Units/armvulc_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 12000,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 7,
			footprintz = 7,
			height = 4,
			hitdensity = 100,
			metal = 14000,
			object = "Units/arm7X7A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:tachyonshot",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servlrg3",
		},
		select = {
			[1] = "servlrg3",
		},
	},
	weapondefs = {
		ata = {
            areaofeffect = 10,
            avoidfeature = false,
            beamtime = 0.3,
            collidefriendly = false,
            corethickness = 0.5,
            craterareaofeffect = 0,
            craterboost = 0,
            cratermult = 0,
            edgeeffectiveness = 0.5,
            energypershot = 25000,
            explosiongenerator = "custom:laserhit-large-blue",
            firestarter = 90,
            impulseboost = 0,
            impulsefactor = 0,
            largebeamlaser = true,
            laserflaresize = 30,
            name = "Rapid-fire extended-range g2g tachyon accelerator",
            noselfdamage = true,
            range = 2500,
            reloadtime = 2,
            rgbcolor = "0 0 1",
            scrollspeed = 5,
            soundhitdry = "",
            soundhitwet = "sizzle",
            soundstart = "annigun1",
            soundtrigger = 0.5,
            targetmoveerror = 0.3,
            texture3 = "largebeam",
            thickness = 9,
            tilelength = 150,
            tolerance = 10000,
            turret = true,
            weapontype = "BeamLaser",
            weaponvelocity = 3100,
            damage = {
                commanders = 4800,
                default = 50000,
            },
        },
    },
    weapons = {
        [1] = {
            badtargetcategory = "VTOL GROUNDSCOUT",
            def = "ATA",
            onlytargetcategory = "SURFACE",	
            },
        },
},



legstarfall = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 29096,
	energycost = 600000,
	metalcost = 52500,
	buildpic = "legstarfall.DDS",
	buildtime = 1400000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "120 165 120",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "advancedFusionExplosion",
	hightrajectory = 1,
	firestate = 0,
	footprintx = 8,
	footprintz = 8,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 33500,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/legstarfall.s3o",
	script = "Units/legstarfall.cob",
	seismicsignature = 0,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 700,
	yardmap = "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corbhmth_aoplane.dds",
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Hornet",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "120 125 120",
			collisionvolumetype = "CylY",
			damage = 26000,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 7,
			footprintz = 7,
			height = 20,
			hitdensity = 100,
			metal = 25000,
			object = "Units/legstarfall_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "80 10 80",
			damage = 12000,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 7,
			footprintz = 7,
			height = 4,
			hitdensity = 100,
			metal = 12000,
			object = "Units/cor7X7A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {

		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servlrg4",
		},
		select = {
			[1] = "servlrg4",
		},
	},
	weapondefs = {
		starfire = {
			accuracy = 0,
			areaofeffect = 256,
			avoidfeature = false,
			avoidfriendly = false,
			avoidground = false,
			burst = 61,
			burstrate = 0.01,
			
			sprayangle = 500,
			highTrajectory = 1,
			
			cegtag = "starfire",
			collidefriendly = false,
			craterboost = 0.1,
			cratermult = 0.1,
			edgeeffectiveness = 0.95,
			energypershot = 360000,
			
			explosiongenerator = "custom:starfire-explosion",
			gravityaffected = "true",
			impulseboost = 0.5,
			impulsefactor = 0.5,
			name = "Starfire Barrage Launcher",
			noselfdamage = true,
			range = 6100,
			reloadtime = 15,
			rgbcolor = "0.7 0.7 1.0 1.0 1.0 1.0 1.0 1.0",
			soundhit = "rflrpcexplo",
			soundhitwet = "splshbig",
			soundstart = "lrpcshot",
			soundhitvolume = 36,
			turret = true,
			weapontimer = 14,
			weapontype = "Cannon",
			weaponvelocity = 900,
			damage = {
				default = 600,
				shields = 375,
				subs = 200,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "starfire",
			onlytargetcategory = "SURFACE",
		},
	},
},


corscreamer = {
	maxacc = 0,
	activatewhenbuilt = true,
	airsightdistance = 2400,
	maxdec = 0,
	energycost = 32000,
	metalcost = 1650,
	buildpic = "CORSCREAMER.DDS",
	buildtime = 28000,
	canrepeat = false,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "63 57 63",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "largeBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1670,
	maxslope = 20,
	maxwaterdepth = 0,
	objectname = "Units/CORSCREAMER.s3o",
	script = "Units/CORSCREAMER.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 600,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corscreamer_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'aa',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "63 57 63",
			collisionvolumetype = "CylY",
			damage = 942,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 1145,
			object = "Units/corscreamer_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 471,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 458,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "targon2",
		canceldestruct = "cancel2",
		deactivate = "targoff2",
		underattack = "warning1",
		working = "targsel2",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "targsel2",
		},
	},
	weapondefs = {
		cor_advsam = {
			areaofeffect = 425,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			canattackground = false,
			cegtag = "missiletrailaa-large",
			collidefriendly = false,
			craterareaofeffect = 425,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.75,
			energypershot = 1800,
			explosiongenerator = "custom:genericshellexplosion-huge-aa",
			firestarter = 90,
			flighttime = 2.2,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 0,
			model = "corscreamermissile.s3o",
			name = "Long-range heavy g2a missile launcher",
			noselfdamage = true,
			proximitypriority = -2,
			range = 2400,
			reloadtime = 1.8,
			smoketrail = true,
			smokePeriod = 3,
			smoketime = 24,
			smokesize = 11,
			smokecolor = 0.9,
			smokeTrailCastShadow = false,
			castshadow = false,
			soundhit = "impact",
			soundhitwet = "splslrg",
			soundstart = "aarocket",
			soundhitvolume = 8,
			soundstartvolume = 8,
			sprayangle = 10000,
			startvelocity = 1400,
			stockpile = true,
			stockpiletime = 14,
			texture1 = "null",
			texture2 = "smoketrailaaflak",
			tolerance = 10000,
			tracks = true,
			trajectoryheight = 0.55,
			turnrate = 99000,
			turret = true,
			weaponacceleration = 1000,
			weapontype = "MissileLauncher",
			weaponvelocity = 1850,
			damage = {
				vtol = 750,
				space = 750,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
			def = "COR_ADVSAM",
			onlytargetcategory = "VTOL SPACE",
		},
	},
},




corbuzz = {
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-huge",
		},
	},
	weapondefs = {
		crblmssl = {
			areaofeffect = 1920,
			avoidfeature = false,
			avoidfriendly = false,
			cegtag = "NUKETRAIL",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			commandfire = true,
			craterareaofeffect = 1920,
			craterboost = 2.4,
			cratermult = 1.2,
			edgeeffectiveness = 0.45,
			energypershot = 187500,
			explosiongenerator = "custom:newnukecor",
			firestarter = 100,
			flighttime = 400,
			impulseboost = 0.5,
			impulsefactor = 0.5,
			metalpershot = 1500,
			model = "crblmssl.s3o",
			name = "Intercontinental thermonuclear ballistic missile",
			range = 10000,
			reloadtime = 10,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 130,
			smokesize = 28,
			smokecolor = 0.85,
			smokeTrailCastShadow = true,
			soundhit = "nukecor",
			soundhitwet = "nukewater",
			soundstart = "nukelaunch",
			soundhitwetvolume = 56,
			soundstartvolume = 20,
			stockpile = true,
			stockpiletime = 10,
			texture1 = "null",
			texture2 = "railguntrail",
			texture3 = "null",
			targetable = 1,
			tolerance = 4000,
			tracks = true,
			turnrate = 5500,
			weaponacceleration = 100,
			weapontimer = 5.5,
			weapontype = "Cannon",
			weaponvelocity = 1600,
			customparams = {
				place_target_on_ground = "true",
			},
			damage = {
				commanders = 2500,
				default = 11500,
			},
		},
		nuclear_launch = {
			areaofeffect = 0,
			avoidfeature = false,
			avoidfriendly = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 0,
			name = "Nuclear Launch",
			range = 0,
			reloadtime = 10,
			soundhit = "nukelaunchalarm",
			soundhitvolume = 50,
			tolerance = 10000,
			turnrate = 10000,
			weaponacceleration = 101,
			weapontimer = 0.1,
			weapontype = "StarburstLauncher",
			weaponvelocity = 100,
			damage = {
				default = 0,
			},
		},
	},
	weapons = {
		[1] = {
			def = "CRBLMSSL",
			onlytargetcategory = "NOTSUB",
		},
		[2] = {
			def = "NUCLEAR_LAUNCH",
			onlytargetcategory = "NOTSUB",
		},
	},
},