{
armnanotct2 = {
	builddistance = 700,
	workertime = 500,
		},
armrespawn = {
	buildoptions = {
		[1] = "cormex",
		[2] = "cormakr",
		[3] = "armsolar",
		[4] = "corwin",
		[5] = "corgeo",
		[6] = "armestor",
		[7] = "",
		[8] = "lootboxnano_t1_var1",
		[9] = "lootboxnano_t1_var2",
	},
},
correspawn = {
	buildoptions = {
		[1] = "cormex",
		[2] = "cormakr",
		[3] = "armsolar",
		[4] = "corwin",
		[5] = "corgeo",
		[6] = "armestor",
		[7] = "",
		[8] = "lootboxnano_t1_var1",
		[9] = "lootboxnano_t1_var2",
	},
},
lootboxnano_t1_var1 = {
	builddistance = 1000,
	buildpic = "ARMNANOTCPLAT.DDS",
	objectname = "lootboxes/lootboxnanoarmt1.s3o",
	script = "lootboxes/lootboxnanoarm.cob",
	workertime = 1000,
buildoptions = {
			[1] = "cormex",
			[2] = "corexp",
			[3] = "armmakr",
			[4] = "armsolar",
			[5] = "armadvsol",
			[6] = "corwin",
			[7] = "corgeo",
			[8] = "freefusion",
			[9] = "armdf",
			[10] = "",
			[11] = "",
			[12] = "",
			[13] = "",
			[14] = "",
			[15] = "armestor",
			[16] = "armmstor",
			[17] = "armrad",
			[18] = "lootboxnano_t1_var1",
			[19] = "lootboxnano_t2_var1",
			[20] = "",
			[21] = "lootboxnano_t1_var2",
		},
	},
lootboxnano_t1_var2 = {
	builddistance = 500,
	buildpic = "CORNANOTCPLAT.DDS",
	objectname = "lootboxes/lootboxnanocort1.s3o",
	script = "lootboxes/lootboxnanocor.cob",
	workertime = 1000,
buildoptions = {
			[1] = "",
			[2] = "",
			[3] = "",
			[4] = "",
			[5] = "",
			[6] = "",
			[7] = "",
			[8] = "",
			[9] = "",
			[10] = "",
			[11] = "",
			[12] = "",
			[13] = "",
			[14] = "",
			[15] = "",
			[16] = "",
			[17] = "",
			[18] = "",
			[19] = "",
			[20] = "",
			[21] = "lootboxnano_t1_var2",
		},
	},
lootboxnano_t2_var1 = {
	builddistance = 1200,
	buildpic = "ARMNANOTCPLAT.DDS",
	objectname = "lootboxes/lootboxnanoarmt2.s3o",
	script = "lootboxes/lootboxnanoarm.cob",
	workertime = 150,
buildoptions = {
			[1] = "armmex",
			[2] = "armamex",
			[3] = "armmakr",
			[4] = "corsolar",
			[5] = "coradvsol",
			[6] = "corwint2",
			[7] = "corageo",
			[8] = "armfus",
			[9] = "armckfus",
			[10] = "armuwadves",
			[11] = "cormstor",
			[12] = "corsd",
			[13] = "cortarg",
			[14] = "armarad",
			[15] = "",
			[16] = "",
			[17] = "lootboxnano_t1_var1",
			[18] = "lootboxnano_t2_var1",
			[19] = "lootboxnano_t3_var1",
			[20] = "",
			[21] = "lootboxnano_t2_var2",
		},
	},
lootboxnano_t2_var2 = {
	builddistance = 1200,
	buildpic = "CORNANOTCPLAT.DDS",
	objectname = "lootboxes/lootboxnanocort2.s3o",
	script = "lootboxes/lootboxnanocor.cob",
	workertime = 150,
buildoptions = {
			[1] = "",
			[2] = "",
			[3] = "",
			[4] = "",
			[5] = "",
			[6] = "",
			[7] = "",
			[8] = "",
			[9] = "",
			[10] = "",
			[11] = "",
			[12] = "",
			[13] = "",
			[14] = "",
			[15] = "",
			[16] = "",
			[17] = "",
			[18] = "",
			[19] = "",
			[20] = "",
			[21] = "lootboxnano_t2_var2",
		},
	},
lootboxnano_t3_var1 = {
	builddistance = 1200,
	buildpic = "ARMNANOTCPLAT.DDS",
	objectname = "lootboxes/lootboxnanoarmT3.s3o",
	script = "lootboxes/lootboxnanoarm.cob",
	workertime = 300,
buildoptions = {
			[1] = "armmoho",
			[2] = "armshockwave",
			[3] = "cormmkr",
			[4] = "",
			[5] = "corfus",
			[6] = "",
			[7] = "corestor",
			[8] = "armuwadvms",
			[9] = "",
			[10] = "armsd",
			[11] = "corrar",
			[12] = "",
			[13] = "",
			[14] = "",
			[15] = "",
			[16] = "lootboxnano_t2_var1",
			[17] = "lootboxnano_t3_var1",
			[18] = "lootboxnano_t4_var1",
			[19] = "",
			[20] = "",
			[21] = "lootboxnano_t3_var2",
		},
	},
lootboxnano_t3_var2 = {
	builddistance = 1200,
	buildpic = "CORNANOTCPLAT.DDS",
	objectname = "lootboxes/lootboxnanocorT3.s3o",
	script = "lootboxes/lootboxnanocor.cob",
	workertime = 300,
buildoptions = {
			[1] = "",
			[2] = "",
			[3] = "",
			[4] = "",
			[5] = "",
			[6] = "",
			[7] = "",
			[8] = "",
			[9] = "",
			[10] = "",
			[11] = "",
			[12] = "",
			[13] = "",
			[14] = "",
			[15] = "",
			[16] = "",
			[17] = "lootboxnano_t3_var2",
			[18] = "",
			[19] = "",
			[20] = "",
			[21] = "",
		},
	},
lootboxnano_t4_var1 = {
	builddistance = 1200,
	buildpic = "ARMNANOTCPLAT.DDS",
	objectname = "lootboxes/lootboxnanoarmt4.s3o",
	script = "lootboxes/lootboxnanoarm.cob",
	workertime = 500,
buildoptions = {
			[1] = "cormoho",
			[2] = "cormexp",
			[3] = "armmmkr",
			[4] = "corafus",
			[5] = "armafus",
			[6] = "",
			[7] = "coruwadves",
			[8] = "coruwadvms",
			[9] = "corarad",
			[10] = "",
			[11] = "",
			[12] = "",
			[13] = "",
			[14] = "",
			[15] = "",
			[16] = "lootboxnano_t3_var1",
			[17] = "lootboxnano_t4_var1",
			[18] = "",
			[19] = "",
			[20] = "",
			[21] = "lootboxnano_t4_var2",
		},
	},
lootboxnano_t4_var2 = {
	builddistance = 1200,
	buildpic = "CORNANOTCPLAT.DDS",
	objectname = "lootboxes/lootboxnanocort4.s3o",
	script = "lootboxes/lootboxnanocor.cob",
	workertime = 500,
buildoptions = {
			[1] = "",
			[2] = "",
			[3] = "",
			[4] = "",
			[5] = "",
			[6] = "",
			[7] = "",
			[8] = "",
			[9] = "",
			[10] = "",
			[11] = "",
			[12] = "",
			[13] = "",
			[14] = "",
			[15] = "",
			[16] = "",
			[17] = "",
			[18] = "",
			[19] = "",
			[20] = "",
			[21] = "",
		},
	},
armapt3 = {
buildoptions = {
"armsat",
},
},
corapt3 = {
buildoptions = {
"corsat",
},
},
armshltx = {
buildoptions = {
[7] = "armcomcon",
	},
},
corgant = {
buildoptions = {
[7] = "corcomcon",
	},
},
armsat = {
radardistance = 3500,
sightdistance = 3000,
},
corsat = {
radardistance = 3500,
sightdistance = 3000,
},
armcomcon = {
acceleration = 0.5,
autoheal = 500,
builddistance = 250,
cancloak = false,
canmanualfire = false,
category = "ALL WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE CANBEUW EMPABLE",
mass = 5000,
maxvelocity = 2,
reclaimable = true,
showplayername = false,
buildoptions = {
			[1] = "armgate",
			[2] = "lootboxnano_t3_var1",
			[3] = "armannit3",
			[4] = "resourcecheat",
			[5] = "coruwadves",
			[6] = "coruwadvms",
			[7] = "armvulc",
		},
customparams = {
iscommander = false,
unitgroup = 'buildert3',
techlevel = 3,
		},
weapondefs = {},
weapons = {
			[1] = {
				def = "",
			},
			[2] = {
				def = "",
			},
			[3] = {
				def = "",
			},
		},
	},
corcomcon = {
acceleration = 0.5,
autoheal = 500,
builddistance = 250,
cancloak = false,
canmanualfire = false,
category = "ALL WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE CANBEUW EMPABLE",
mass = 5000,
maxvelocity = 2,
reclaimable = true,
showplayername = false,
buildoptions = {
			[1] = "armgate",
			[2] = "cordoomt3",
			[3] = "lootboxnano_t3_var2",
			[4] = "resourcecheat",
			[5] = "coruwadves",
			[6] = "coruwadvms",
			[7] = "corbuzz",
		},
customparams = {
iscommander = false,
unitgroup = 'buildert3',
techlevel = 3,
		},
weapondefs = {},
weapons = {
			[1] = {
				def = "",
			},
			[2] = {
				def = "",
			},
			[3] = {
				def = "",
			},
		},
	},
resourcecheat = {
buildcostenergy = 160000,
buildcostmetal = 30000,
buildtime = 690000,
energymake = 10000,
energystorage = 10000,
energyuse = 0,
footprintx = 8,
footprintz = 8,
metalmake = 0,
metalstorage = 10000,
maxdamage = 2000,
customparams = {
buildinggrounddecalsizey = 10,
buildinggrounddecalsizex = 10,
energyconv_capacity = 5000,
energyconv_efficiency = 1/50,
techlevel = 3,
			},
		},
armvulc = {
energystorage = 10000,
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:tachyonshot",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			ok = {
				[1] = "obli",
			},
			select = {
				[1] = "obli",
			},
		},
weapondefs = {
ata = {
				areaofeffect = 10,
				avoidfeature = false,
				beamtime = 0.3,
				collidefriendly = false,
				corethickness = 0.5,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				energypershot = 25000,
				explosiongenerator = "custom:laserhit-large-blue",
				firestarter = 90,
				impulseboost = 0,
				impulsefactor = 0,
				largebeamlaser = true,
				laserflaresize = 30,
				name = "Rapid-fire extended-range g2g tachyon accelerator",
				noselfdamage = true,
				range = 2500,
				reloadtime = 2,
				rgbcolor = "0 0 1",
				scrollspeed = 5,
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "annigun1",
				soundtrigger = 0.5,
				targetmoveerror = 0.3,
				texture3 = "largebeam",
				thickness = 9,
				tilelength = 150,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 3100,
				damage = {
					commanders = 4800,
					default = 50000,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "ATA",
				onlytargetcategory = "SURFACE",	
				},
			},
	},
coruwadves = {
	buildcostenergy = 100000,
	buildcostmetal = 5000,
	buildtime = 50000,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	energystorage = 250000,
	footprintx = 6,
	footprintz = 6,
	maxdamage = 100000,
	customparams = {	
		techlevel = 3,
			},
		},
coruwadvms = {
	buildcostenergy = 80000,
	buildcostmetal = 7000,
	buildtime = 20524,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE UNDERWATER EMPABLE",
	footprintx = 5,
	footprintz = 5,
	maxdamage = 100000,
	maxwaterdepth = 0,
	metalstorage = 100000,
	customparams = {	
		techlevel = 3,
			},
		},
armlwall = {
	weapondefs = {
		lightning = {
			areaofeffect = 10,
			beamttl = 1,
			burst = 1,
			edgeeffectiveness = 0.25,
			energypershot = 250,
			explosiongenerator = "custom:genericshellexplosion-large-lightning",
			firestarter = 0,
			impactonly = 1,
			intensity = 2,
			name = "Crowd controlling paralyzer EMP weapon",
			paralyzer = true,
			paralyzetime = 3,
			range = 480,
			reloadtime = 5,
			rgbcolor = "0 0 0.2",
			soundhit = "EMGPULS1",
			soundhitwet = "splsslrg",
			soundstart = "beamershot2",
			thickness = 15,
			customparams = {
					spark_ceg = "genericshellexplosion-splash-lightning",
					spark_forkdamage = "0.5",
					spark_maxunits = "5",
					spark_range = "50",
				},
			damage = {
				default = 1000,
				},
			},
		},
	},
cormwall = {
	weapondefs = {
		banisher = {
			areaofeffect = 150,
			burst = 1,
			burstrate = 0,
			cegtag = "burnflame",
			colormap = "0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008",
			craterareaofeffect = 0,
			explosiongenerator = "custom:burnblack",
			flamegfxtime = 1,
			name = "Napalm missile pod",
			range = 500,
			reloadtime = 1,
			rgbcolor = "1 0.25 0.1",
			size = 4,
			soundhitdry = "flamhit1",
			soundhitwet = "sizzle",
			soundstart = "corban_a",
			damage = {
					bombers = 10,
					default = 50,
					fighters = 10,
					subs = 10,
					vtol = 10,
				},	
			},
		},
		
	},
armgate = {
	energyuse = 200,
	maxdamage = 2200,
	customparams = {
		shield_power = 10000,
		shield_radius = 800,
		techlevel = 3,
			},
	weapondefs = {
		repulsor = {
			range = 800,
			damage = {
				default = 500,
				},
			shield = {
				energyuse = 100,
				power = 10000,
				powerregen = 800,
				powerregenenergy = 800,
				radius = 800,
				startingpower = 3000,
				},
			},
		},
	},
}