LR - "armbeamer",
MR - "corhlt",
SR - "armpb",
AD - "leginf",
Eminate Juno Field (persistent Juno field radiates from station)- "armason",
 
LRAA - "armfflak",
SRAA -  Arm Bomb Resistant AA "armcir",



armbeamer = {
	acceleration = 0,
	brakerate = 0,
	buildangle = 32768,
	buildcostenergy = 1500,
	buildcostmetal = 190,
	buildpic = "armbeamer.DDS",
	buildtime = 5324,
	canrepeat = false,
	cantbetransported = false,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -1",
	collisionvolumescales = "33 85 33",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 7500,
	maxdamage = 1430,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMBEAMER.s3o",
	script = "Units/armbeamer.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 475,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armbeamer_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-1.45989990234 -3.69362253418 0.310646057129",
			collisionvolumescales = "48.9197998047 59.9625549316 37.0396270752",
			collisionvolumetype = "Box",
			damage = 774,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 50,
			hitdensity = 100,
			metal = 114,
			object = "Units/armbeamer_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 387,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 46,
			object = "Units/arm2X2A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed2",
		},
		select = {
			[1] = "servmed2",
		},
	},
	weapondefs = {
		armbeamer_weapon = {
			areaofeffect = 8,
			avoidfeature = false,
			beamdecay = 0.05,
			beamtime = 0.1,
			beamttl = 1,
			corethickness = 0.233,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 6,
			explosiongenerator = "custom:laserhit-beamer",
			firestarter = 30,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			laserflaresize = 9.35,
			name = "Anti-swarm constant wave g2g laser",
			noselfdamage = true,
			range = 480,
			reloadtime = 0.1,
			rgbcolor = "0 0 1",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "beamershot2",
			soundtrigger = 1,
			targetmoveerror = 0.05,
			thickness = 2.4,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 1000,
			damage = {
				bombers = 2,
				default = 26.6,
				fighters = 2,
				vtol = 2,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "armbeamer_WEAPON",
			onlytargetcategory = "NOTSUB",
			fastautoretargeting = true,
		},
	},
},




corhlt = {
	acceleration = 0,
	brakerate = 0,
	buildangle = 4096,
	buildcostenergy = 4700,
	buildcostmetal = 480,
	buildpic = "CORHLT.DDS",
	buildtime = 12650,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -8 0",
	collisionvolumescales = "38 90 38",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 200,
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 2750,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/CORHLT.s3o",
	script = "Units/CORHLT.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 455,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corhlt_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		legacyname = "Gaat Gun",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "38 95 38",
			collisionvolumetype = "CylY",
			damage = 1485,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 292,
			object = "Units/corhlt_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 743,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 117,
			object = "Units/cor2X2A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "twractv3",
		},
		select = {
			[1] = "twractv3",
		},
	},
	weapondefs = {
		cor_laserh1 = {
			areaofeffect = 14,
			avoidfeature = false,
			beamtime = 0.15,
			corethickness = 0.2,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 50,
			explosiongenerator = "custom:laserhit-medium-green",
			firestarter = 90,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			laserflaresize = 8.8,
			name = "High energy g2g laser",
			noselfdamage = true,
			range = 620,
			reloadtime = 1.2,
			rgbcolor = "0 1 0",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "Lasrmas2",
			soundtrigger = 1,
			targetmoveerror = 0.2,
			thickness = 2.7,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 2250,
			damage = {
				bombers = 35,
				default = 261,
				fighters = 35,
				vtol = 35,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "COR_LASERH1",
			onlytargetcategory = "NOTSUB",
			fastautoretargeting = true,
		},
	},
},


armpb = {
	acceleration = 0,
	brakerate = 0,
	buildcostenergy = 14000,
	buildcostmetal = 680,
	buildpic = "ARMPB.DDS",
	buildtime = 14961,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	cloakcost = 16,
	corpse = "DEAD",
	damagemodifier = 0.5,
	explodeas = "smallBuildingExplosionGeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 2800,
	maxslope = 10,
	maxwaterdepth = 0,
	mincloakdistance = 55,
	nochasecategory = "MOBILE",
	objectname = "Units/ARMPB.s3o",
	script = "Units/ARMPB.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 598,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armpb_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "32 18 32",
			collisionvolumetype = "Box",
			damage = 1519,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 15,
			hitdensity = 100,
			metal = 350,
			object = "Units/armpb_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 760,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 140,
			object = "Units/arm3X3D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-medium-impulse",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "twrturn3",
		},
		select = {
			[1] = "twrturn3",
		},
	},
	weapondefs = {
		armpb_weapon = {
			areaofeffect = 24,
			avoidfeature = false,
			burnblow = true,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-medium",
			impulseboost = 0.123,
			impulsefactor = 0.123,
			name = "Pop-up heavy g2g gauss cannon",
			noselfdamage = true,
			range = 730,
			reloadtime = 1.6,
			separation = 1.8,
			nogap = false,
			sizeDecay = 0.06,
			stages = 14,
			alphaDecay = 0.08,
			soundhit = "xplomed2",
			soundhitwet = "splshbig",
			soundstart = "cannhvy1",
			targetmoveerror = 0.2,
			tolerance = 8000,
			turret = true,
			weapontype = "Cannon",
			weaponvelocity = 800,
			damage = {
				bombers = 26,
				default = 675,
				fighters = 26,
				hvyboats = 472.5,
				subs = 300,
				vtol = 26,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "ARMPB_WEAPON",
			onlytargetcategory = "SURFACE",
		},
	},
},



leginf = {
	acceleration = 0.0098,
	airsightdistance = 1050,
	brakerate = 0.0196,
	buildcostenergy = 30000,
	buildcostmetal = 2000,
	buildpic = "LEGINF.DDS",
	buildtime = 33000,
	canmove = true,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE TANK EMPABLE",
	collisionvolumeoffsets = "0 -5 3",
	collisionvolumescales = "37 51 51",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "hugeexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	idleautoheal = 5,
	idletime = 1800,
	leavetracks = true,
	mass = 5001,
	maxdamage = 3650,
	--maxreversevelocity = 0.762,
	maxslope = 14,
	maxvelocity = 1.25,
	maxwaterdepth = 15,
	movementclass = "HTANK4",
	nochasecategory = "VTOL",
	objectname = "Units/leginf.s3o",
	script = "Units/LEGINF.cob",
	seismicsignature = 0,
	selfdestructas = "hugeExplosionGenericSelfd",
	sightdistance = 351,
	trackoffset = -8,
	trackstrength = 8,
	tracktype = "corwidetracks",
	trackwidth = 50,
	turninplace = true,
	turninplaceanglelimit = 90,
	turninplacespeedlimit = 0.95832,
	turnrate = 169.39999,
	customparams = {
		unitgroup = 'weapon',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "corvehicles/t2",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "1.25984954834 -1.01012474365 0.475593566895",
			collisionvolumescales = "55.5426483154 42.2261505127 61.5749359131",
			collisionvolumetype = "Box",
			damage = 2000,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 8,
			hitdensity = 100,
			metal = 1200,
			object = "Units/leginf_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1500,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 2,
			hitdensity = 100,
			metal = 550,
			object = "Units/cor2X2B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-medium",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "tcormove",
		},
		select = {
			[1] = "tcorsel",
		},
	},
	weapondefs = {
		rapidnapalm = {
			areaofeffect = 150,
			avoidfeature = false,
			cegtag = "burnflame",
			collidefriendly = false,
			colormap = "0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008",
			craterareaofeffect = 90,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:burnblack",
			flamegfxtime = 1,
			gravityaffected = "true",
			impulseboost = 0.123,
			impulsefactor = 0.123,
			mygravity = 0.08,
			name = "HeavyCannon",
			noselfdamage = true,
			projectiles = 1,
			range = 1100,
			reloadtime = 0.6,
			rgbcolor = "1 0.25 0.1",
			size = 4,
			soundhitdry = "flamhit1",
			soundhitwet = "sizzle",
			soundstart = "cannhvy2",
			sprayangle = 2500,
			turret = true,
			weapontype = "Cannon",
			weaponvelocity = 300,
			damage = {
				bombers = 10,
				default = 30,
				fighters = 10,
				subs = 10,
				vtol = 10,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "RAPIDNAPALM",
			maindir = "0 0 1",
			maxangledif = 180,
			onlytargetcategory = "SURFACE",
		},
	},
},




armason = {
	acceleration = 0,
	activatewhenbuilt = true,
	brakerate = 0,
	buildangle = 8192,
	buildcostenergy = 2600,
	buildcostmetal = 170,
	buildpic = "ARMASON.DDS",
	buildtime = 6152,
	canattack = false,
	canrepeat = false,
	category = "ALL UNDERWATER NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	damagemodifier = 0.46,
	explodeas = "mediumBuildingexplosiongeneric-uw",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 2350,
	maxslope = 10,
	minwaterdepth = 24,
	objectname = "Units/ARMASON.s3o",
	onoffable = false,
	script = "Units/ARMASON.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd-uw",
	sightdistance = 215,
	sonardistance = 1600,
	yardmap = "yooy oooo oooo yooy",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armason_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "FireStorm",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/seautil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = false,
			category = "corpses",
			collisionvolumeoffsets = "-2.53617095947 -6.10351563068e-07 -2.30155944824",
			collisionvolumescales = "30.2144622803 57.7799987793 23.5352478027",
			collisionvolumetype = "Box",
			damage = 1272,
			energy = 0,
			footprintx = 4,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 106,
			object = "Units/armason_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "cmd-on",
		canceldestruct = "cancel2",
		deactivate = "cmd-off",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "sonar1",
		},
	},
},





armfflak = {
	acceleration = 0,
	airsightdistance = 1000,
	brakerate = 0,
	buildangle = 16384,
	buildcostenergy = 23000,
	buildcostmetal = 850,
	buildpic = "ARMFFLAK.DDS",
	buildtime = 21855,
	canrepeat = false,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -10 0",
	collisionvolumescales = "42 64 42",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumExplosionGeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 1920,
	minwaterdepth = 5,
	objectname = "Units/ARMFFLAK.s3o",
	script = "Units/ARMFFLAK.cob",
	seismicsignature = 0,
	selfdestructas = "mediumExplosionGenericSelfd",
	sightdistance = 550,
	waterline = 0.3,
	yardmap = "wwwwwwwww",
	customparams = {
		unitgroup = 'aa',
		model_author = "FireStorm",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/seadefence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.25456237793 -3.1726487793 0.162696838379",
			collisionvolumescales = "33.5091247559 30.6275024414 44.9046173096",
			collisionvolumetype = "Box",
			damage = 1038,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 1,
			footprintz = 1,
			height = 20,
			hitdensity = 100,
			metal = 525,
			object = "Units/armfflak_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-medium-aa",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "twrturn3",
		},
		select = {
			[1] = "twrturn3",
		},
	},
	weapondefs = {
		armflak_gun = {
			accuracy = 1000,
			areaofeffect = 192,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			canattackground = false,
			collidefriendly = false,
			cegtag = "flaktrailaa",
			craterareaofeffect = 192,
			craterboost = 0,
			cratermult = 0,
			cylindertargeting = 1,
			edgeeffectiveness = 1,
			explosiongenerator = "custom:flak",
			gravityaffected = "true",
			impulseboost = 0,
			impulsefactor = 0,
			mygravity = 0.01,
			name = "Heavy g2a flak cannon",
			noselfdamage = true,
			predictboost = 1,
			range = 775,
			reloadtime = 0.53333,
			size = 4.5,
			sizedecay = 0.08,
			soundhit = "flakhit",
			soundhitwet = "splslrg",
			soundstart = "flakfire",
			stages = 8,
			turret = true,
			weapontimer = 1,
			weapontype = "Cannon",
			weaponvelocity = 2450,
			damage = {
				bombers = 250,
				fighters = 500,
				vtol = 250,
			},
			rgbcolor = {
				[1] = 1,
				[2] = 0.33,
				[3] = 0.7,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
			def = "ARMFLAK_GUN",
			onlytargetcategory = "VTOL",
		},
	},
},





armcir = {
	acceleration = 0,
	airsightdistance = 1060,
	brakerate = 0,
	buildangle = 65536,
	buildcostenergy = 7300,
	buildcostmetal = 750,
	buildpic = "ARMCIR.DDS",
	buildtime = 12000,
	canrepeat = false,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "50 77 50",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 4450,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMCIR.s3o",
	script = "Units/ARMCIR.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 380,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armcir_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'aa',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "50 77 50",
			collisionvolumetype = "cylY",
			damage = 1500,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 370,
			object = "Units/armcir_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 750,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 150,
			object = "Units/arm3X3B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "twrturn3",
		},
		select = {
			[1] = "twrturn3",
		},
	},
	weapondefs = {
		arm_cir = {
			areaofeffect = 48,
			avoidfeature = false,
			burnblow = true,
			burst = 4,
			burstrate = 0.26667,
			burnblow = true,
			canattackground = false,
			cegtag = "missiletrailaa",
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-tiny-aa",
			firestarter = 20,
			flighttime = 2.3,
			impulseboost = 0,
			impulsefactor = 0,
			model = "cormissile.s3o",
			name = "Rapid-fire long-range g2a missile barrel",
			noselfdamage = true,
			projectiles = 1,
			proximitypriority = -2,
			range = 1125,
			reloadtime = 1.6,
			smoketrail = true,
			smokePeriod = 8,
			smoketime = 12,
			smokesize = 5.4,
			smokecolor = 0.95,
			smokeTrailCastShadow = false,
			castshadow = false,
			soundhit = "xplosml2",
			soundhitwet = "splshbig",
			soundstart = "rocklit1",
			soundtrigger = true,
			texture1 = "null",
			texture2 = "smoketrailaa3",
			tolerance = 100000,
			tracks = true,
			turnrate = 42000,
			turret = true,
			startvelocity = 250,
			weaponacceleration = 300,
			weapontype = "MissileLauncher",
			weaponvelocity = 1300,
			damage = {
				bombers = 265,
				fighters = 215,
				vtol = 170,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "ARM_CIR",
			onlytargetcategory = "VTOL",
			fastautoretargeting = true,
		},
	},
},




