Volatile Metal - "armmmmkr",
Safe Metal - "armuwmmm",

Volatile Energy - "armafus",
Safe Energy - "armfus",
Alt Energy - "armwint2"

Metal Store - "armuwadvms",
Energy Store - "armuwadves",


armmmkr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 21000,
	metalcost = 380,
	buildpic = "ARMMMKR.DDS",
	buildtime = 35000,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	explodeas = "advmetalmaker",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 445,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMMMKR.s3o",
	script = "Units/ARMMMKR.cob",
	seismicsignature = 0,
	selfdestructas = "advmetalmakerSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armmmkr_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		energyconv_capacity = 600,
		energyconv_efficiency = 1/58,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-0.574371337891 -11.1292811768 1.24842834473",
			collisionvolumescales = "60.6127624512 52.6148376465 60.6127624512",
			collisionvolumetype = "Box",
			damage = 240,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 233,
			object = "Units/armmmkr_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 120,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 93,
			object = "Units/arm4X4C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-mm-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-mm-deactivate",
		underattack = "warning1",
		working = "arm-bld-metalmaker",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon1",
		},
	},
},




armuwmmm = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 24000,
	metalcost = 400,
	buildpic = "ARMUWMMM.DDS",
	buildtime = 38960,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -4 0",
	collisionvolumescales = "72 72 72",
	collisionvolumetype = "Ell",
	corpse = "DEAD",
	explodeas = "hugeBuildingExplosionGeneric",
	floater = true,
	footprintx = 5,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 445,
	maxslope = 16,
	minwaterdepth = 15,
	objectname = "Units/ARMUWMMM.s3o",
	script = "Units/ARMUWMMM.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 156,
	usebuildinggrounddecal = true,
	waterline = 5,
	yardmap = "oooooooooooooooooooo",
	customparams = {
		unitgroup = 'metal',
		energyconv_capacity = 650,
		energyconv_efficiency = 1/58,
		model_author = "FireStorm",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/seaeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "1.91563415527 -2.21923828114e-05 -2.03186035156",
			collisionvolumescales = "70.811340332 33.9307556152 58.6123657227",
			collisionvolumetype = "Box",
			damage = 240,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 247,
			object = "Units/armuwmmm_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 120,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 99,
			object = "Units/arm4X4C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-mm-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-mm-deactivate",
		underattack = "warning1",
		working = "arm-bld-metalmaker",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon1",
		},
	},
},




armafus = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 4096,
	energycost = 69000,
	metalcost = 9700,
	buildpic = "ARMAFUS.DDS",
	buildtime = 312500,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "96 96 96",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	damagemodifier = 0.95,
	energymake = 3000,
	energystorage = 9000,
	explodeas = "advancedFusionExplosion",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 7900,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/ARMAFUS.s3o",
	script = "Units/ARMAFUS.cob",
	seismicsignature = 0,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armafus_aoplane.dds",
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "96 96 96",
			collisionvolumetype = "Box",
			damage = 16290,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 6441,
			object = "Units/armafus_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "96.0 14.0 6.0",
			collisionvolumetype = "box",
			damage = 8145,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 2576,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "fusion1",
		},
	},
},




armfus = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 21000,
	metalcost = 4300,
	buildpic = "ARMFUS.DDS",
	buildtime = 70000,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -2",
	collisionvolumescales = "91 57 59",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energymake = 1000,
	energystorage = 2500,
	explodeas = "fusionExplosion",
	footprintx = 6,
	footprintz = 5,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 4450,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMFUS.s3o",
	script = "Units/ARMFUS.cob",
	seismicsignature = 0,
	selfdestructas = "fusionExplosionSelfd",
	sightdistance = 273,
	yardmap = "oooooo oooooo oooooo oooooo oooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armfus_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.420112609863 0.0956184448242 -0.353080749512",
			collisionvolumescales = "98.7820892334 38.6634368896 65.8547515869",
			collisionvolumetype = "Box",
			damage = 2700,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 2603,
			object = "Units/armfus_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1350,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 1041,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "fusion1",
		},
	},
},




armwint2 = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	energycost = 1750,
	metalcost = 370,
	buildpic = "ARMWINT2.DDS",
	buildtime = 16000,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 1 0",
	collisionvolumescales = "68 174 68",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 5,
	explodeas = "windboom",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1960,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/scavbuildings/ARMWINT2.s3o",
	script = "Units/scavbuildings/ARMWINT2.cob",
	seismicsignature = 0,
	selfdestructas = "windboom",
	sightdistance = 273,
	windgenerator = 500,
	yardmap = "oooooo oooooo oooooo oooooo oooooo oooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armwint2_aoplane.dds",
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		energymultiplier = 10,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 1 0",
			collisionvolumescales = "68 174 68",
			collisionvolumetype = "CylY",
			damage = 1125,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 6,
			footprintz = 6,
			height = 40,
			hitdensity = 100,
			metal = 222,
			object = "Units/scavbuildings/armwint2_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "windgen",
		},
	},
},



armuwadvms = {
	buildangle = 5049,
	energycost = 11500,
	metalcost = 750,
	buildpic = "ARMUWADVMS.DDS",
	buildtime = 20400,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE UNDERWATER EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "88 38 72",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 10300,
	maxslope = 20,
	maxwaterdepth = 9999,
	metalstorage = 10000,
	objectname = "Units/ARMUWADVMS.s3o",
	script = "Units/ARMUWADVMS.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 195,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armuwadvms_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 5.4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/seaeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "7.62939453125e-06 -3.51196289046e-05 -0.0",
			collisionvolumescales = "45.1519927979 49.1111297607 45.1520080566",
			collisionvolumetype = "Box",
			damage = 3720,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 9,
			hitdensity = 100,
			metal = 458,
			object = "Units/armuwadvms_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1860,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 183,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "stormtl1",
		},
	},
},



armuwadves = {
	buildangle = 8192,
	energycost = 10000,
	metalcost = 830,
	buildpic = "ARMUWADVES.DDS",
	buildtime = 20300,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE UNDERWATER EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "42 62 62",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energystorage = 40000,
	explodeas = "advenergystorage",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 11700,
	maxslope = 20,
	maxwaterdepth = 9999,
	objectname = "Units/ARMUWADVES.s3o",
	script = "Units/ARMUWADVES.cob",
	seismicsignature = 0,
	selfdestructas = "advenergystorageSelfd",
	sightdistance = 169,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armuwadves_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/seaeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "42 62 62",
			collisionvolumetype = "Box",
			damage = 4200,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 9,
			hitdensity = 100,
			metal = 502,
			object = "Units/armuwadves_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 2100,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 201,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "storngy1",
		},
	},
},