LR - "cormwall",
MR - Missiles track "corvipe",
SR - Arm Claw but really high health "armclaw",

Basilica Massive Tachyon Sniper.  Huge Alpha, Huge Energy, moderate reload. "armbrtha",
AD - "legministarfall", or "armemp",

OP
LRAA - "armflak",
SRAA - "armmercury",



cormwall = {
	maxacc = 0,
	energycost = 4800, --was 4850
	metalcost = 1020, --was 485
	buildpic = "CORMWALL.DDS",
	buildtime = 14000, -- was 12214
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "32 50 32",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	damagemodifier = 0.25,
	decoyfor = "corfort",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 10,
	idletime = 900,
	levelground = false,
	mass = 10000000000,
	health = 5320, --was 4450, --1/2 of corfort
	maxslope = 24,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/CORMWALL.s3o",
	script = "Units/CORMWALL.cob",
	seismicsignature = 0,
	selfdestructas = "tinyBuildingExplosionGenericSelfd",
	sightdistance = 330,
	stealth = true,
	turnrate = 0,
	upright = true,
	yardmap = "ffff",
	customparams = {
		neutral_when_closed = true,
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corfort_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		decoyfor = "armfort",
		model_author = "Beherith",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			autoreclaimable = 0,
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -3 0",
			collisionvolumescales = "32 50 32",
			collisionvolumetype = "CylY",
			damage = 540,
			energy = 0,
			featuredead = "ROCKTEETH",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 205,
			object = "Units/corfort.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		rockteeth = {
			animating = 0,
			animtrans = 0,
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 500,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2,
			object = "Units/cor1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:flamestreamxm",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4-fire",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed2",
		},
		select = {
			[1] = "servmed2",
		},
	},
	weapondefs = {
		-- banisher = {
		-- 	areaofeffect = 128,
		-- 	avoidfeature = false,
		-- 	burnblow = true,
		-- 	burst = 7,
		-- 	burstrate = 0.3333,
		-- 	cegtag = "missiletraillarge-red",
		-- 	craterareaofeffect = 128,
		-- 	craterboost = 0,
		-- 	cratermult = 0,
		-- 	edgeeffectiveness = 0.55,
		-- 	explosiongenerator = "custom:genericshellexplosion-large-bomb",
		-- 	firestarter = 20,
		-- 	flighttime = 7.4,
		-- 	impulseboost = 0.123,
		-- 	impulsefactor = 0.123,
		-- 	model = "banishermissile.s3o",
		-- 	name = "Banisher",
		-- 	noselfdamage = true,
		-- 	range = 300,
		-- 	reloadtime = 38, --18
		-- 	smoketrail = true,
		-- 	smokePeriod = 7, --7
		-- 	smoketime = 24, --48
		-- 	smokesize = 11.3,
		-- 	smokecolor = 0.82,
		-- 	smokeTrailCastShadow = false,
		-- 	soundhit = "corban_b",
		-- 	soundhitwet = "splsmed",
		-- 	soundstart = "corban_a",
		-- 	startvelocity = 240,
		-- 	texture1 = "null",
		-- 	texture2 = "railguntrail",
		-- 	tolerance = 9000,
		-- 	tracks = true,
		-- 	trajectoryheight = 0.45,
		-- 	turnrate = 60000,
		-- 	turret = true,
		-- 	weaponacceleration = 220,
		-- 	weapontimer = 0.25,
		-- 	weapontype = "StarburstLauncher",
		-- 	weaponvelocity = 650,
		-- 	damage = {
		-- 		default = 750,
		-- 	},
		-- },
		exp_heavyrocket = {
			areaofeffect = 96,
			avoidfeature = false,
			burst = 7,
			burstrate = 0.1,
			cegtag = "missiletrailsmall-red",
			craterboost = 0,
			cratermult = 0,
			dance = 24,
			edgeeffectiveness = 0.65,
			explosiongenerator = "custom:genericshellexplosion-catapult",
			firestarter = 70,
			flighttime = 3.2,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			metalpershot = 0,
			model = "catapultmissile.s3o",
			movingaccuracy = 600,
			name = "CatapultRockets",
			noselfdamage = true,
			proximitypriority = -1,
			range = 675, --1/2 of corcat
			reloadtime = 15,
			smoketrail = true,
			smokePeriod = 4,
			smoketime = 16,
			smokesize = 8.5,
			smokecolor = 0.5,
			smokeTrailCastShadow = false,
			soundhit = "rockhit",
			soundhitwet = "splsmed",
			soundstart = "rapidrocket3",
			startvelocity = 165,
			texture1 = "null",
			texture2 = "smoketrailbar",
			trajectoryheight = 3,
			turnrate = 5000,
			turret = true,
			weaponacceleration = 100,
			weapontimer = 6,
			weapontype = "MissileLauncher",
			weaponvelocity = 530,
			wobble = 2000,
			damage = {
				default = 450,
			},
		},
	},
	weapons = {
		[1] = {
			def = "exp_heavyrocket",
			onlytargetcategory = "SURFACE",
			fastautoretargeting = true,
		},
	},
},



corvipe = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 8192,
	energycost = 14000,
	metalcost = 730,
	buildpic = "CORVIPE.DDS",
	buildtime = 15000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	damagemodifier = 0.5,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3000,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/CORVIPE.s3o",
	script = "Units/CORVIPE.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 546,
	usepiececollisionvolumes = 1,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corvipe_aoplane.dds",
		buildinggrounddecalsizey = 4.7,
		buildinggrounddecalsizex = 4.7,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-2.7282333374 -4.31274414048e-05 -3.87004852295",
			collisionvolumescales = "42.4275054932 38.4097137451 38.8498077393",
			collisionvolumetype = "Box",
			damage = 1631,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 380,
			object = "Units/corvipe_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 408,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 61,
			object = "Units/cor2X2F.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak2",
		uncloak = "kloak2un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed1",
		},
		select = {
			[1] = "servmed1",
		},
	},
	weapondefs = {
		vipersabot = {
			areaofeffect = 24,
			avoidfeature = false,
			burnblow = true,
			cegtag = "missiletrailviper",
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-medium-bomb",
			firestarter = 70,
			flighttime = 1.05,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			model = "cormissile3fast.s3o",
			name = "Heavy g2g sabot rocket launcher",
			noselfdamage = true,
			range = 730,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 33,
			smokesize = 10,
			smokecolor = 0.8,
			smokeTrailCastShadow = false,
			soundhit = "SabotHit",
			soundhitwet = "splshbig",
			soundstart = "SabotFire",
			startvelocity = 570,
			targetmoveerror = 0.2,
			smokeperiod = 5,
			castshadow = true,
			texture1 = "null",
			texture2 = "railguntrail",
			tolerance = 8000,
			tracks = true,
			turnrate = 6000,
			turret = true,
			weaponacceleration = 400,
			weapontimer = 0.1,
			weapontype = "MissileLauncher",
			weaponvelocity = 950,
			damage = {
				default = 825,
				hvyboats = 577.5,
				subs = 5,
				vtol = 26,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "VIPERSABOT",
			onlytargetcategory = "SURFACE",
		},
	},
},




armclaw = {
	maxacc = 0,
	buildangle = 8192,
	energycost = 1600,
	metalcost = 340,
	buildpic = "ARMCLAW.DDS",
	buildtime = 4650,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "32 22 32",
	collisionvolumetype = "CyLy",
	corpse = "DEAD",
	damagemodifier = 0.25,
	decoyfor = "armdrag",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 10,
	idletime = 900,
	levelground = false,
	mass = 10000000000,
	health = 1330,
	maxslope = 18,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/ARMCLAW.s3o",
	radardistancejam = 8,
	script = "Units/ARMCLAW.cob",
	seismicsignature = 0,
	selfdestructas = "tinyBuildingExplosionGenericSelfd",
	sightdistance = 440,
	stealth = true,
	turnrate = 0,
	upright = true,
	yardmap = "ffff",
	customparams = {
		neutral_when_closed = true,
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armclaw_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		decoyfor = "armdrag",
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	featuredefs = {
		dead = {
			autoreclaimable = 0,
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 2.37060546837e-06 -0.0625",
			collisionvolumescales = "32.0 17.7499847412 31.375",
			collisionvolumetype = "Box",
			damage = 540,
			energy = 0,
			featuredead = "ROCKTEETH",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 205,
			object = "Units/armdrag.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		rockteeth = {
			animating = 0,
			animtrans = 0,
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 500,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2,
			object = "Units/arm1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-lightning",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3-lightning",
			[2] = "deathceg4-lightning",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed2",
		},
		select = {
			[1] = "servmed2",
		},
	},
	weapondefs = {
		dclaw = {
			areaofeffect = 8,
			avoidfeature = false,
			beamttl = 1,
			burst = 10,
			burstrate = 0.03333,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			duration = 1,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-medium-lightning2",
			firestarter = 50,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			intensity = 24,
			name = "Close-quarters g2g lightning turret",
			noselfdamage = true,
			range = 440,
			reloadtime = 1.13333,
			rgbcolor = "0.5 0.5 1",
			soundhit = "lashit",
			soundhitwet = "sizzle",
			soundstart = "lghthvy1",
			soundtrigger = true,
			thickness = 1.5,
			turret = true,
			weapontype = "LightningCannon",
			weaponvelocity = 450,
			customparams = {
				spark_ceg = "genericshellexplosion-splash-lightning",
				spark_forkdamage = "0.33",
				spark_maxunits = "2",
				spark_range = "60",
			},
			damage = {
				commanders = 31.5,
				default = 21,
				vtol = 2.5,
			},
		},
	},
	weapons = {
		[1] = {
			def = "DCLAW",
			onlytargetcategory = "SURFACE",
			fastautoretargeting = true,
		},
	},
},




armbrtha = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 32700,
	energycost = 64000,
	metalcost = 4500,
	buildpic = "ARMBRTHA.DDS",
	buildtime = 85000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -20",
	collisionvolumescales = "48 90 48",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "hugeBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 4450,
	maxslope = 12,
	maxwaterdepth = 0,
	objectname = "Units/ARMBRTHA.s3o",
	script = "Units/ARMBRTHA.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 273,
	usepiececollisionvolumes = 1,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armbrtha_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		canareaattack = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "3.15924835205 -0.787798413086 6.6563873291",
			collisionvolumescales = "81.6838531494 113.772003174 72.5632324219",
			collisionvolumetype = "Box",
			damage = 2520,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 40,
			hitdensity = 100,
			metal = 2720,
			object = "Units/armbrtha_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1260,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 1088,
			object = "Units/arm3X3E.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-huge",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servlrg3",
		},
		select = {
			[1] = "servlrg3",
		},
	},
	weapondefs = {
		lrpc = {
			accuracy = 300,
			areaofeffect = 135,
			avoidfeature = false,
			avoidfriendly = false,
			cegtag = "arty-huge",
			collidefriendly = false,
			craterareaofeffect = 116,
			craterboost = 0.1,
			cratermult = 0.1,
			edgeeffectiveness = 0.15,
			energypershot = 5000,
			explosiongenerator = "custom:genericshellexplosion-huge",
			gravityaffected = "true",
			heightboostfactor = 8,
			impulseboost = 0.5,
			impulsefactor = 0.5,
			leadbonus = 0,
			model = "artshell-large.s3o",
			name = "Long range g2g plasma cannon",
			noselfdamage = true,
			range = 4650,
			reloadtime = 13.2,
			soundhit = "lrpcexplo",
			soundhitwet = "splshbig",
			soundstart = "lrpcshot3",
			soundhitvolume = 38,
			soundstartvolume = 24,
			turret = true,
			weapontype = "Cannon",
			weaponvelocity = 1100,
			damage = {
				default = 1625,
				shields = 812,
				subs = 500,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "LRPC",
			onlytargetcategory = "SURFACE",
		},
	},
},




legministarfall = {
	acceleration = 0,
	brakerate = 0,
	buildangle = 29096,
	buildcostenergy = 60000,
	buildcostmetal = 2000,
	buildpic = "LEGSTARFALL.DDS",
	buildtime = 65000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "52 65 52",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "hugeBuildingexplosiongeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 7000,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/scavbuildings/legministarfall.s3o",
	script = "Units/scavbuildings/legministarfall.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 700,
	--usepiececollisionvolumes = 1,
	yardmap = "ooo ooo ooo",
	customparams = {
		usebuildinggrounddecal = false,
		unitgroup = 'weapon',
		model_author = "Hornet",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 60 45",
			collisionvolumetype = "Box",
			damage = 3000,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			hitdensity = 100,
			metal = 6000,
			object = "Units/scavbuildings/legministarfall_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 1500,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 3000,
			object = "Units/arm3X3A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-large",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servlrg3",
		},
		select = {
			[1] = "servlrg3",
		},
	},
	weapondefs = {
		ministarfire = {
			accuracy = 0,
			areaofeffect = 55,
			avoidfeature = false,
			avoidfriendly = false,
			avoidground = false,
			burst = 61,
			burstrate = 0.01,
			
			sprayangle = 400,
			highTrajectory = 1,
			
			cegtag = "ministarfire",
			collidefriendly = false,
			craterboost = 0.1,
			cratermult = 0.1,
			edgeeffectiveness = 0.95,
			energypershot = 20000,
			
			explosiongenerator = "custom:ministarfire-explosion",
			gravityaffected = "true",
			impulseboost = 0.5,
			impulsefactor = 0.5,
			name = "Starfire Barrage Launcher",
			noselfdamage = true,
			range = 1400,
			reloadtime = 15,
			rgbcolor = "0.7 0.7 1.0 0.7 1.0 1.0 1.0 0.7",
			soundhit = "xplomed3",
			soundhitwet = "splshbig",
			soundstart = "cannon2",
			soundhitvolume = 20,
			turret = true,
			weapontimer = 14,
			weapontype = "Cannon",
			weaponvelocity = 500,
			damage = {
				default = 125,
				shields = 110,
				subs = 50,
			},
		},
	
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "ministarfire",
			onlytargetcategory = "SURFACE",
		},
	},
},




armemp = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 8192,
	energycost = 29000,
	metalcost = 1600,
	buildpic = "ARMEMP.DDS",
	buildtime = 79300,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 5 0",
	collisionvolumescales = "80 30 60",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3350,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMEMP.s3o",
	script = "Units/ARMEMP.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 455,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armemp_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'emp',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
		yardmap = "ooooooo ooooooo ooooooo ooooooo ooooooo ooooooo",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "80 30 60",
			collisionvolumetype = "Box",
			damage = 1800,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			hitdensity = 100,
			metal = 976,
			object = "Units/armemp_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 900,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 390,
			object = "Units/arm3X3A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servroc1",
		},
		select = {
			[1] = "servroc1",
		},
	},
	weapondefs = {
		armemp_weapon = {
			areaofeffect = 312,
			avoidfeature = false,
			avoidfriendly = false,
			cegtag = "cruisemissiletrail-emp",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			commandfire = true,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 1,
			energypershot = 15644,
			explosiongenerator = "custom:genericshellexplosion-huge-lightning",
			firestarter = 0,
			flighttime = 400,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 500,
			model = "cortronmissile.s3o",
			name = "Heavy long-range g2g EMP starburst rocket",
			noselfdamage = true,
			paralyzer = true,
			paralyzetime = 35,
			range = 3650,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 8,
			smoketime = 60,
			smokesize = 7,
			smokecolor = 0.9,
			smokeTrailCastShadow = false,
			soundhit = "emgpuls1",
			--soundhitwet = "splslrg",
			soundstart = "mismed1emp1",
			stockpile = true,
			stockpiletime = 65,
			texture1 = "null",
			texture2 = "smoketrailbar",
			texture3 = "null",
			tolerance = 4000,
			turnrate = 10000,
			weaponacceleration = 150,
			weapontimer = 3,
			weapontype = "StarburstLauncher",
			weaponvelocity = 1200,
			damage = {
				default = 50000,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "ARMEMP_WEAPON",
			onlytargetcategory = "NOTSUB",
		},
	},
},





armflak = {
	maxacc = 0,
	airsightdistance = 1000,
	maxdec = 0,
	buildangle = 8192,
	energycost = 13000,
	metalcost = 820,
	buildpic = "ARMFLAK.DDS",
	buildtime = 19000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "36 55 36",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1750,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "ALL",
	objectname = "Units/ARMFLAK.s3o",
	script = "Units/ARMFLAK.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 525,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armflak_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'aa',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-3.8550491333 -3.09570312496e-05 3.13596343994",
			collisionvolumescales = "30.5327911377 31.4515380859 37.50050354",
			collisionvolumetype = "Box",
			damage = 945,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 500,
			object = "Units/armflak_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 473,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 200,
			object = "Units/arm2X2C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-flak",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "twrturn3",
		},
		select = {
			[1] = "twrturn3",
		},
	},
	weapondefs = {
		armflak_gun = {
			accuracy = 1000,
			areaofeffect = 172,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			canattackground = false,
			cegtag = "flaktrailaa",
			collidefriendly = false,
			craterareaofeffect = 192,
			craterboost = 0,
			cratermult = 0,
			cylindertargeting = 1,
			edgeeffectiveness = 1,
			explosiongenerator = "custom:flak",
			gravityaffected = "true",
			impulseboost = 0,
			impulsefactor = 0,
			mygravity = 0.01,
			name = "Heavy g2a flak cannon",
			noselfdamage = true,
			predictboost = 1,
			range = 775,
			reloadtime = 0.53333,
			--size = 4.5,
			--sizedecay = 0.08,
			smoketrail = false,
			soundhit = "flakhit2",
			soundhitwet = "splslrg",
			soundstart = "flakfire",
			soundhitvolume = 7.5,
			soundstartvolume = 9,
			stages = 0,
			turret = true,
			weapontimer = 1,
			weapontype = "Cannon",
			weaponvelocity = 1600,
			damage = {
				--default = 125,
				vtol = 250,
			},
			rgbcolor = {
				[1] = 1,
				[2] = 0.33,
				[3] = 0.7,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
			def = "ARMFLAK_GUN",
			onlytargetcategory = "VTOL",
		},
	},
},




armmercury = {
    maxacc = 0,
    activatewhenbuilt = true,
    airsightdistance = 2400,
    maxdec = 0,
    energycost = 33000,
    metalcost = 1600,
    buildpic = "ARMMERCURY.DDS",
    buildtime = 28000,
    canrepeat = false,
    category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
    collisionvolumeoffsets = "-1 -1 0",
    collisionvolumescales = "60 78 60",
    collisionvolumetype = "CylY",
    corpse = "DEAD",
    explodeas = "largeBuildingExplosionGeneric",
    footprintx = 4,
    footprintz = 4,
    icontype = "building",
    idleautoheal = 5,
    idletime = 1800,
    health = 1670,
    maxslope = 20,
    maxwaterdepth = 0,
    objectname = "Units/ARMMERCURY.s3o",
    script = "Units/ARMMERCURY.cob",
    seismicsignature = 0,
    selfdestructas = "largeBuildingExplosionGenericSelfd",
    sightdistance = 600,
    yardmap = "oooooooooooooooo",
    customparams = {
        usebuildinggrounddecal = true,
        buildinggrounddecaltype = "decals/armmercury_aoplane.dds",
        buildinggrounddecalsizey = 6,
        buildinggrounddecalsizex = 6,
        buildinggrounddecaldecayspeed = 30,
        unitgroup = 'aa',
        model_author = "Beherith",
        normaltex = "unittextures/Arm_normal.dds",
        removewait = true,
        subfolder = "armbuildings/landdefenceoffence",
        techlevel = 2,
    },
    featuredefs = {
        dead = {
            blocking = true,
            category = "corpses",
            collisionvolumeoffsets = "0 0 0",
            collisionvolumescales = "60 78 60",
            collisionvolumetype = "CylY",
            damage = 900,
            energy = 0,
            featuredead = "HEAP",
            featurereclamate = "SMUDGE01",
            footprintx = 3,
            footprintz = 3,
            height = 20,
            hitdensity = 100,
            metal = 1022,
            object = "Units/armmercury_dead.s3o",
            reclaimable = true,
            seqnamereclamate = "TREE1RECLAMATE",
            world = "All Worlds",
        },
        heap = {
            blocking = false,
            category = "heaps",
            collisionvolumescales = "55.0 4.0 6.0",
            collisionvolumetype = "cylY",
            damage = 450,
            energy = 0,
            featurereclamate = "SMUDGE01",
            footprintx = 3,
            footprintz = 3,
            hitdensity = 100,
            metal = 409,
            object = "Units/arm3X3A.s3o",
            reclaimable = true,
            resurrectable = 0,
            seqnamereclamate = "TREE1RECLAMATE",
            world = "All Worlds",
        },
    },
    sfxtypes = {
        pieceexplosiongenerators = {
            [1] = "deathceg2",
            [2] = "deathceg3",
            [3] = "deathceg4",
        },
    },
    sounds = {
        activate = "targon1",
        canceldestruct = "cancel2",
        deactivate = "targoff1",
        underattack = "warning1",
        working = "targsel1",
        count = {
            [1] = "count6",
            [2] = "count5",
            [3] = "count4",
            [4] = "count3",
            [5] = "count2",
            [6] = "count1",
        },
        select = {
            [1] = "targsel1",
        },
    },
    weapondefs = {
        arm_advsam = {
            areaofeffect = 425,
            avoidfeature = false,
            avoidfriendly = false,
            burnblow = true,
            canattackground = false,
            cegtag = "missiletrailaa-large",
            collidefriendly = false,
            craterareaofeffect = 425,
            craterboost = 0,
            cratermult = 0,
            edgeeffectiveness = 0.75,
            energypershot = 1800,
            explosiongenerator = "custom:genericshellexplosion-huge-aa",
            firestarter = 90,
            flighttime = 2.2,
            impulseboost = 0,
            impulsefactor = 0,
            metalpershot = 0,
            model = "corscreamermissile.s3o",
            name = "Heavy long-range g2a guided missile launcher",
            noselfdamage = true,
            proximitypriority = -2,
            range = 2400,
            reloadtime = 1.8,
            smoketrail = true,
            smokePeriod = 3,
            smoketime = 24,
            smokesize = 11,
            smokecolor = 0.9,
            smokeTrailCastShadow = false,
            castshadow = false,
            soundhit = "impact",
            soundhitwet = "splslrg",
            soundstart = "aarocket",
            soundhitvolume = 8,
            soundstartvolume = 8,
            sprayangle = 10000,
            startvelocity = 1400,
            stockpile = true,
            stockpiletime = 14,
            texture1 = "null",
            texture2 = "smoketrailaaflak",
            tolerance = 10000,
            tracks = true,
            trajectoryheight = 0.55,
            turnrate = 99000,
            turret = true,
            weaponacceleration = 1000,
            weapontype = "MissileLauncher",
            weaponvelocity = 1850,
            damage = {
                vtol = 750,
                space = 750,
            },
        },
    },
    weapons = {
        [1] = {
            badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
            def = "ARM_ADVSAM",
            onlytargetcategory = "VTOL SPACE",
        },
    },
},
