corbuzz = {
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-huge",
		},
	},
	weapondefs = {
		crblmssl = {
			areaofeffect = 1920,
			avoidfeature = false,
			avoidfriendly = false,
			cegtag = "NUKETRAIL",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			commandfire = true,
			craterareaofeffect = 1920,
			craterboost = 2.4,
			cratermult = 1.2,
			edgeeffectiveness = 0.45,
			energypershot = 187500,
			explosiongenerator = "custom:newnukecor",
			firestarter = 100,
			flighttime = 400,
			impulseboost = 0.5,
			impulsefactor = 0.5,
			metalpershot = 1500,
			model = "crblmssl.s3o",
			name = "Intercontinental thermonuclear ballistic missile",
			range = 10000,
			reloadtime = 10,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 130,
			smokesize = 28,
			smokecolor = 0.85,
			smokeTrailCastShadow = true,
			soundhit = "nukecor",
			soundhitwet = "nukewater",
			soundstart = "nukelaunch",
			soundhitwetvolume = 56,
			soundstartvolume = 20,
			stockpile = true,
			stockpiletime = 10,
			texture1 = "null",
			texture2 = "railguntrail",
			texture3 = "null",
			targetable = 1,
			tolerance = 4000,
			tracks = true,
			turnrate = 5500,
			weaponacceleration = 100,
			weapontimer = 5.5,
			weapontype = "Cannon",
			weaponvelocity = 1600,
			customparams = {
				place_target_on_ground = "true",
			},
			damage = {
				commanders = 2500,
				default = 11500,
			},
		},
		nuclear_launch = {
			areaofeffect = 0,
			avoidfeature = false,
			avoidfriendly = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 0,
			name = "Nuclear Launch",
			range = 0,
			reloadtime = 10,
			soundhit = "nukelaunchalarm",
			soundhitvolume = 50,
			tolerance = 10000,
			turnrate = 10000,
			weaponacceleration = 101,
			weapontimer = 0.1,
			weapontype = "StarburstLauncher",
			weaponvelocity = 100,
			damage = {
				default = 0,
			},
		},
	},
	weapons = {
		[1] = {
			def = "CRBLMSSL",
			onlytargetcategory = "NOTSUB",
		},
		[2] = {
			def = "NUCLEAR_LAUNCH",
			onlytargetcategory = "NOTSUB",
		},
	},
},
armvulc = {
    energystorage = 10000,
            sfxtypes = {
                explosiongenerators = {
                    [1] = "custom:tachyonshot",
                },
                pieceexplosiongenerators = {
                    [1] = "deathceg2",
                    [2] = "deathceg3",
                    [3] = "deathceg4",
                },
            },
            sounds = {
                ok = {
                    [1] = "obli",
                },
                select = {
                    [1] = "obli",
                },
            },
    weapondefs = {
    ata = {
                    areaofeffect = 10,
                    avoidfeature = false,
                    beamtime = 0.3,
                    collidefriendly = false,
                    corethickness = 0.5,
                    craterareaofeffect = 0,
                    craterboost = 0,
                    cratermult = 0,
                    edgeeffectiveness = 0.5,
                    energypershot = 25000,
                    explosiongenerator = "custom:laserhit-large-blue",
                    firestarter = 90,
                    impulseboost = 0,
                    impulsefactor = 0,
                    largebeamlaser = true,
                    laserflaresize = 30,
                    name = "Rapid-fire extended-range g2g tachyon accelerator",
                    noselfdamage = true,
                    range = 2500,
                    reloadtime = 2,
                    rgbcolor = "0 0 1",
                    scrollspeed = 5,
                    soundhitdry = "",
                    soundhitwet = "sizzle",
                    soundstart = "annigun1",
                    soundtrigger = 0.5,
                    targetmoveerror = 0.3,
                    texture3 = "largebeam",
                    thickness = 9,
                    tilelength = 150,
                    tolerance = 10000,
                    turret = true,
                    weapontype = "BeamLaser",
                    weaponvelocity = 3100,
                    damage = {
                        commanders = 4800,
                        default = 50000,
                    },
                },
            },
            weapons = {
                [1] = {
                    badtargetcategory = "VTOL GROUNDSCOUT",
                    def = "ATA",
                    onlytargetcategory = "SURFACE",	
                    },
                },
        },