LR - Scav Missile DT "corscavdtm",
MR -  Scav Claw "corscavdtl",
SR - Scav Flamer "corscavdtf",
Area Denial - "armjuno",

LRAA - "corflak"
SRAA - "cormadsam",

corscavdtm = {
	acceleration = 0,
	buildangle = 8192,
	buildcostenergy = 1550,
	buildcostmetal = 290,
	buildpic = "CORSCAVDTM.DDS",
	buildtime = 4419,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	damagemodifier = 0.25,
	decoyfor = "scavdrag",
	explodeas = "flamethrower",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 10,
	idletime = 900,
	levelground = false,
	mass = 10000000000,
	maxdamage = 1610,
	maxslope = 18,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "scavs/SCAVDTM.s3o",
	radardistancejam = 8,
	script = "units/scavbuildings/SCAVDTM.cob",
	seismicsignature = 0,
	selfdestructas = "flamethrowerSelfd",
	sightdistance = 422,
	stealth = true,
	turnrate = 0,
	upright = true,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = false,
		buildinggrounddecaltype = "decals/scavdtf_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		decoyfor = "corscavdrag",
		model_author = "FireStorm",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		--subfolder = "other/Scavengers",
	},
	featuredefs = {
		dead = {
			autoreclaimable = 0,
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 0.0149960864258 0.116882324219",
			collisionvolumescales = "32.042388916 19.5953521729 32.6287231445",
			collisionvolumetype = "Box",
			damage = 600,
			energy = 0,
			featuredead = "ROCKTEETH",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 177,
			object = "scavs/scavdrag.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		rockteeth = {
			animating = 0,
			animtrans = 0,
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 500,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2,
			object = "Units/cor1X1A.s3o",
			reclaimable = true,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4-fire",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed2",
		},
		select = {
			[1] = "servmed2",
		},
	},
	weapondefs = {
		cormh_weapon = {
			areaofeffect = 80,
			avoidfeature = false,
			cegtag = "missiletrailsmall-starburst",
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-medium-bomb",
			firestarter = 100,
			firesubmersed = true,
			flighttime = 10,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			metalpershot = 0,
			model = "corkbmissl1.s3o",
			name = "Rocket",
			noselfdamage = true,
			range = 500,
			reloadtime = 5,
			smoketrail = false,
			soundhit = "xplomed4",
			soundhitwet = "splssml",
			soundstart = "Rockhvy1",
			texture1 = "null",
			texture2 = "null",
			texture3 = "null",
			tolerance = 4000,
			turnrate = 15000,
			weaponacceleration = 70,
			weapontimer = 2.9,
			weapontype = "StarburstLauncher",
			weaponvelocity = 480,
			damage = {
				default = 550,
				subs = 200,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "CORMH_WEAPON",
			onlytargetcategory = "SURFACE",
		},
	},
},




corscavdtl = {
	acceleration = 0,
	buildangle = 8192,
	buildcostenergy = 1600,
	buildcostmetal = 340,
	buildpic = "CORSCAVDTL.DDS",
	buildtime = 4638,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -24 0",
	collisionvolumescales = "30 51 30",
	collisionvolumetype = "Ell",
	corpse = "DEAD",
	damagemodifier = 0.25,
	decoyfor = "scavdrag",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 10,
	idletime = 900,
	levelground = false,
	mass = 10000000000,
	maxdamage = 1330,
	maxslope = 18,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "scavs/SCAVDTL.s3o",
	radardistancejam = 8,
	script = "units/scavbuildings/SCAVDTL.cob",
	seismicsignature = 0,
	selfdestructas = "tinyBuildingExplosionGenericSelfd",
	sightdistance = 440,
	stealth = true,
	turnrate = 0,
	upright = true,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = false,
		buildinggrounddecaltype = "decals/scavdtf_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		decoyfor = "corscavdrag",
		model_author = "FireStorm",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		--subfolder = "other/Scavengers",
	},
	featuredefs = {
		dead = {
			autoreclaimable = 0,
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 2.37060546837e-06 -0.0625",
			collisionvolumescales = "32.0 17.7499847412 31.375",
			collisionvolumetype = "Box",
			damage = 540,
			energy = 0,
			featuredead = "ROCKTEETH",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 205,
			object = "scavs/scavdrag.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		rockteeth = {
			animating = 0,
			animtrans = 0,
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 500,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2,
			object = "Units/cor1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-lightning",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3-lightning",
			[2] = "deathceg4-lightning",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed2",
		},
		select = {
			[1] = "servmed2",
		},
	},
	weapondefs = {
		dclaw = {
			areaofeffect = 8,
			avoidfeature = false,
			beamttl = 1,
			burst = 10,
			burstrate = 0.03333,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			duration = 1,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-medium-lightning2",
			firestarter = 50,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			intensity = 24,
			name = "Close-quarters g2g lightning turret",
			noselfdamage = true,
			range = 440,
			reloadtime = 1.13333,
			rgbcolor = "0.5 0.5 1",
			soundhit = "lashit",
			soundhitwet = "sizzle",
			soundstart = "lghthvy1",
			soundtrigger = true,
			thickness = 1.5,
			turret = true,
			weapontype = "LightningCannon",
			weaponvelocity = 450,
			customparams = {
				spark_ceg = "genericshellexplosion-splash-lightning",
				spark_forkdamage = "0.33",
				spark_maxunits = "2",
				spark_range = "60",
			},
			damage = {
				bombers = 2.5,
				commanders = 39,
				default = 21,
				fighters = 2.5,
				vtol = 2.5,
			},
		},
	},
	weapons = {
		[1] = {
			def = "DCLAW",
			onlytargetcategory = "SURFACE",
		},
	},
},


corscavdtf = {
	acceleration = 0,
	buildangle = 8192,
	buildcostenergy = 1550,
	buildcostmetal = 290,
	buildpic = "CORSCAVDTF.DDS",
	buildtime = 4419,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	damagemodifier = 0.25,
	decoyfor = "scavdrag",
	energystorage = 15,
	explodeas = "flamethrower",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 10,
	idletime = 900,
	levelground = false,
	mass = 10000000000,
	maxdamage = 1610,
	maxslope = 18,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "scavs/SCAVDTF.s3o",
	radardistancejam = 8,
	script = "units/scavbuildings/SCAVDTF.cob",
	seismicsignature = 0,
	selfdestructas = "flamethrowerSelfd",
	sightdistance = 422,
	stealth = true,
	turnrate = 0,
	upright = true,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = false,
		buildinggrounddecaltype = "decals/scavdtf_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		decoyfor = "corscavdrag",
		model_author = "FireStorm",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		--subfolder = "other/Scavengers",
	},
	featuredefs = {
		dead = {
			autoreclaimable = 0,
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 0.0149960864258 0.116882324219",
			collisionvolumescales = "32.042388916 19.5953521729 32.6287231445",
			collisionvolumetype = "Box",
			damage = 600,
			energy = 0,
			featuredead = "ROCKTEETH",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 177,
			object = "scavs/scavdrag.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		rockteeth = {
			animating = 0,
			animtrans = 0,
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 500,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2,
			object = "Units/cor1X1B.s3o",
			reclaimable = true,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:flamestreamxm",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4-fire",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servmed2",
		},
		select = {
			[1] = "servmed2",
		},
	},
	weapondefs = {
		dmaw = {
			areaofeffect = 64,
			avoidfeature = false,
			burst = 22,
			burstrate = 0.03333,
			cegtag = "burnflame",
			colormap = "1 0.95 0.82 0.03   0.7 0.4 0.25 0.027   0.44 0.25 0.15 0.024   0.033 0.018 0.011 0.02   0.0 0.0 0.0 0.01",
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:burnblack",
			firestarter = 100,
			flamegfxtime = 1,
			groundbounce = false,
			impulseboost = 0,
			impulsefactor = 0,
			intensity = 0.75,
			name = "Pop-up anti-swarm AoE flamethrower",
			noselfdamage = true,
			proximitypriority = 3,
			range = 410,
			reloadtime = 1.1,
			rgbcolor = "1 0.94 0.88",
			rgbcolor2 = "0.9 0.84 0.8",
			sizegrowth = 0.7,
			soundhitdry = "flamhit1",
			soundhitwet = "sizzle",
			soundstart = "Flamhvy1",
			soundhitvolume = 7.5,
			soundstartvolume = 5.3,
			soundtrigger = false,
			sprayangle = 100,
			targetmoveerror = 0.001,
			tolerance = 2500,
			turret = true,
			weapontimer = 1,
			weapontype = "Flame",
			weaponvelocity = 300,
			damage = {
				commanders = 12,
				default = 16,
				subs = 5,
			},
		},
	},
	weapons = {
		[1] = {
			def = "DMAW",
			onlytargetcategory = "SURFACE",
		},
	},
},




armjuno = {
	acceleration = 0,
	brakerate = 0,
	buildcostenergy = 17000,
	buildcostmetal = 640,
	buildpic = "ARMJUNO.DDS",
	buildtime = 21833,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "44 128 44",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 2350,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMJUNO.s3o",
	script = "Units/ARMJUNO.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 494,
	stealth = true,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armjuno_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -30 0",
			collisionvolumescales = "44 128 44",
			collisionvolumetype = "CylY",
			damage = 1272,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 352,
			object = "Units/armjuno_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 636,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 145,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:juno_sphere_emit",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "drone1",
		},
		select = {
			[1] = "drone1",
		},
	},
	weapondefs = {
		juno_pulse = {
			areaofeffect = 1400,
			avoidfeature = false,
			cegtag = "missiletrail-juno",
			commandfire = true,
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			craterareaofeffect = 1400,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 1,
			energypershot = 12000,
			explosiongenerator = "custom:juno-explo",
			flighttime = 400,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 200,
			model = "epulse.s3o",
			name = "Anti radar/minefield/jammer magnetic impulse rocket",
			range = 32000,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 8,
			smoketime = 45,
			smokesize = 14.0,
			smokecolor = 0.7,
			smokeTrailCastShadow = false,
			castshadow = true, --projectile
			soundhit = "junohit2",
			soundstart = "junofir2",
			stockpile = true,
			stockpiletime = 75,
			tolerance = 4000,
			texture1 = "null",
			texture2 = "smoketrailbar",
			texture3 = "null",
			turnrate = 5500,
			weaponacceleration = 75,
			weapontimer = 4,
			weapontype = "StarburstLauncher",
			weaponvelocity = 500,
			customparams = {
				lups_noshockwave = 1,
				nofire = true,
			},
			damage = {
				default = 1,
				mines = 1000,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "JUNO_PULSE",
			onlytargetcategory = "NOTSUB",
		},
	},
},



corflak = {
	acceleration = 0,
	airsightdistance = 1000,
	brakerate = 0,
	buildangle = 8192,
	buildcostenergy = 14000,
	buildcostmetal = 850,
	buildpic = "CORFLAK.DDS",
	buildtime = 20112,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "28 34 28",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "smallBuildingExplosionGeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 1840,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "ALL",
	objectname = "Units/CORFLAK.s3o",
	script = "Units/CORFLAK.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 525,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corflak_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'aa',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "37.281829834 27.9406890869 36.1777038574",
			collisionvolumetype = "CylY",
			damage = 993,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 515,
			object = "Units/corflak_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 497,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 206,
			object = "Units/cor2X2D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-flak",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "twrturn3",
		},
		select = {
			[1] = "twrturn3",
		},
	},
	weapondefs = {
		armflak_gun = {
			accuracy = 1000,
			areaofeffect = 172,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			canattackground = false,
			cegtag = "flaktrailaa",
			collidefriendly = false,
			craterareaofeffect = 192,
			craterboost = 0,
			cratermult = 0,
			cylindertargeting = 1,
			edgeeffectiveness = 1,
			explosiongenerator = "custom:flak",
			gravityaffected = "true",
			impulseboost = 0,
			impulsefactor = 0,
			mygravity = 0.01,
			name = "Heavy g2a flak cannon",
			noselfdamage = true,
			predictboost = 1,
			range = 775,
			reloadtime = 0.53333,
			--size = 4.5,
			--sizedecay = 0.08,
			soundhit = "flakhit2",
			soundhitwet = "splslrg",
			soundstart = "flakfire",
			soundhitvolume = 7.5,
			soundstartvolume = 9,
			stages = 0,
			turret = true,
			weapontimer = 1,
			weapontype = "Cannon",
			weaponvelocity = 1600,
			damage = {
				default = 125,
				bombers = 250,
				fighters = 500,
				vtol = 250,
			},
			rgbcolor = {
				[1] = 1,
				[2] = 0.33,
				[3] = 0.7,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
			def = "ARMFLAK_GUN",
			onlytargetcategory = "VTOL",
		},
	},
},




cormadsam = {
	acceleration = 0,
	airsightdistance = 850,
	brakerate = 0,
	buildangle = 8192,
	buildcostenergy = 6100,
	buildcostmetal = 315,
	buildpic = "CORMADSAM.DDS",
	buildtime = 5237,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "-1 5 -2",
	collisionvolumescales = "45 54 45",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energyuse = 5,
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 2800,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORMADSAM.s3o",
	script = "Units/CORMADSAM.lua",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 375,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cormadsam_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'aa',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 54 45",
			collisionvolumetype = "CylY",
			damage = 1500,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 10,
			hitdensity = 100,
			metal = 233,
			object = "Units/cormadsam_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 750,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			hitdensity = 100,
			metal = 100,
			object = "Units/cor2X2C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		cloak = "kloak1",
		uncloak = "kloak1un",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "twrturn3",
		},
		select = {
			[1] = "twrturn3",
		},
	},
	weapondefs = {
		madsam_missile = {
			areaofeffect = 16,
			avoidfeature = false,
			burnblow = true,
			canattackground = false,
			cegtag = "missiletrailaa",
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-tiny-aa",
			firestarter = 72,
			flighttime = 2.5,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			model = "cormissile.s3o",
			name = "Advanced g2a rapid missile launcher",
			noselfdamage = true,
			range = 840,
			reloadtime = 0.4,
			smoketrail = true,
			smokePeriod = 7,
			smoketime = 10,
			smokesize = 4.2,
			smokecolor = 1.0,
			smokeTrailCastShadow = false,
			castshadow = false,
			soundhit = "packohit",
			soundhitwet = "splshbig",
			soundstart = "packolau",
			soundtrigger = true,
			startvelocity = 800,
			texture1 = "null",
			texture2 = "smoketrailaa",
			tolerance = 9950,
			tracks = true,
			turnrate = 68000,
			turret = true,
			weaponacceleration = 160,
			weapontimer = 2,
			weapontype = "MissileLauncher",
			weaponvelocity = 1250,
			damage = {
				bombers = 76,
				fighters = 76,
				vtol = 76,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR",
			def = "MADSAM_MISSILE",
			onlytargetcategory = "VTOL",
			fastautoretargeting = true,
		},
	},
},