Volatile Metal - "cormmkr",
Safe Metal - "coruwmmm",

Volatile Energy - "armafus",
Safe Energy - "corafus",
Alt Energy - "armageo"



cormmkr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 21000,
	metalcost = 370,
	buildpic = "CORMMKR.DDS",
	buildtime = 31300,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	explodeas = "advmetalmaker",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 560,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORMMKR.s3o",
	script = "Units/CORMMKR.cob",
	seismicsignature = 0,
	selfdestructas = "advmetalmakerSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cormmkr_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		energyconv_capacity = 600,
		energyconv_efficiency = 1/58,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		flashlightmin = 0.8,
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -2.96020507804e-05 0.388763427734",
			collisionvolumescales = "61.3712463379 53.8299407959 60.5937194824",
			collisionvolumetype = "Box",
			damage = 300,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 228,
			object = "Units/cormmkr_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 150,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 91,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "metlon2",
		canceldestruct = "cancel2",
		deactivate = "metloff2",
		underattack = "warning1",
		working = "metlrun2",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon2",
		},
	},
},




coruwmmm = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 23500,
	metalcost = 400,
	buildpic = "CORUWMMM.DDS",
	buildtime = 38600,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "120 120 120",
	collisionvolumetype = "Ell",
	corpse = "DEAD",
	explodeas = "hugeBuildingExplosionGeneric",
	floater = true,
	footprintx = 5,
	footprintz = 5,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 445,
	maxslope = 16,
	minwaterdepth = 15,
	objectname = "Units/CORUWMMM.s3o",
	script = "Units/CORUWMMM.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 143,
	usebuildinggrounddecal = true,
	waterline = 17,
	yardmap = "ooooooooooooooooooooooooo",
	customparams = {
		unitgroup = 'metal',
		energyconv_capacity = 650,
		energyconv_efficiency = 1/58,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/seaeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -2.2497558593e-05 -0.0",
			collisionvolumescales = "60.0 29.4457550049 60.0",
			collisionvolumetype = "Box",
			damage = 300,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 242,
			object = "Units/coruwmmm_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 150,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 97,
			object = "Units/cor5X5A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "metlon2",
		canceldestruct = "cancel2",
		deactivate = "metloff2",
		underattack = "warning1",
		working = "metlrun2",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon2",
		},
	},
},





armafus = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 4096,
	energycost = 69000,
	metalcost = 9700,
	buildpic = "ARMAFUS.DDS",
	buildtime = 312500,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "96 96 96",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	damagemodifier = 0.95,
	energymake = 3000,
	energystorage = 9000,
	explodeas = "advancedFusionExplosion",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 7900,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/ARMAFUS.s3o",
	script = "Units/ARMAFUS.cob",
	seismicsignature = 0,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armafus_aoplane.dds",
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "96 96 96",
			collisionvolumetype = "Box",
			damage = 16290,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 6441,
			object = "Units/armafus_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "96.0 14.0 6.0",
			collisionvolumetype = "box",
			damage = 8145,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 2576,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "fusion1",
		},
	},
},




corafus = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 4096,
	energycost = 48000,
	metalcost = 9700,
	buildpic = "CORAFUS.DDS",
	buildtime = 329200,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "84 95 84",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	damagemodifier = 0.95,
	energymake = 3000,
	energystorage = 9000,
	explodeas = "advancedFusionExplosion",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 9400,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/CORAFUS.s3o",
	script = "Units/CORAFUS.cob",
	seismicsignature = 0,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corafus_aoplane.dds",
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-5.1672668457 -0.194635522461 -0.799919128418",
			collisionvolumescales = "114.264892578 89.6709289551 97.8311309814",
			collisionvolumetype = "Box",
			damage = 17100,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 6440,
			object = "Units/corafus_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 8550,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 2576,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "fusion2",
		},
	},
},




armageo = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 0,
	energycost = 27000,
	metalcost = 1600,
	buildpic = "ARMAGEO.DDS",
	buildtime = 33300,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "107 77 107",
	collisionvolumetype = "CylY",
	energymake = 1250,
	energystorage = 12000,
	explodeas = "advancedFusionExplosion",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3600,
	maxslope = 15,
	maxwaterdepth = 5,
	objectname = "Units/ARMAGEO.s3o",
	script = "Units/ARMAGEO.cob",
	seismicsignature = 0,
	selfdestructas = "advgeo",
	sightdistance = 273,
	yardmap = "h cysoosyc ysbssbsy sbbjjbbs osjbbjso osjbbjso sbbjjbbs ysbssbsy cysoosyc",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armageo_aoplane.dds",
		buildinggrounddecalsizey = 11,
		buildinggrounddecalsizex = 11,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		cvbuildable = true,
		geothermal = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "geothrm1",
		},
	},
},