Volatile Metal - Core T1 Converter "cormakr",
Safe Metal - Core T1 Naval Converter "corfmkr",

Volatile Energy - Arm (unrestricted) Geothernal "armgeo",
Safe Energy - Core Adv Solar "coradvsol",
Alt Energy - Limited to 1 "freefusion",

Metal Store - "armmstor",
Energy Store - "armestor",


cormakr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 1250,
	metalcost = 1,
	buildpic = "CORMAKR.DDS",
	buildtime = 2680,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -1 0",
	collisionvolumescales = "32 25 32",
	collisionvolumetype = "Box",
	explodeas = "metalmaker",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 167,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORMAKR.s3o",
	script = "Units/CORMAKR.cob",
	seismicsignature = 0,
	selfdestructas = "metalmakerSelfd",
	sightdistance = 273,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cormakr_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		energyconv_capacity = 70,
		energyconv_efficiency = 1/70,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-mm-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-mm-deactivate",
		underattack = "warning1",
		working = "arm-bld-metalmaker",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon2",
		},
	},
},


corfmkr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 2500,
	metalcost = 1,
	buildpic = "CORFMKR.DDS",
	buildtime = 2680,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	explodeas = "largeBuildingExplosionGeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 133,
	maxslope = 10,
	minwaterdepth = 11,
	objectname = "Units/CORFMKR.s3o",
	script = "Units/CORFMKR.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 273,
	waterline = 3.5,
	yardmap = "wwwwwwwww",
	customparams = {
		unitgroup = 'metal',
		energyconv_capacity = 70,
		energyconv_efficiency = 1/64,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/seaeconomy",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-mm-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-mm-deactivate",
		underattack = "warning1",
		working = "arm-bld-metalmaker",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon2",
		},
	},
},



armgeo = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 2048,
	energycost = 13000,
	metalcost = 560,
	buildpic = "ARMGEO.DDS",
	buildtime = 13100,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -4 0",
	collisionvolumescales = "60 70 60",
	collisionvolumetype = "Box",
	corpse = "dead",
	energymake = 300,
	energystorage = 1000,
	explodeas = "geo",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1940,
	maxslope = 20,
	maxwaterdepth = 5,
	objectname = "Units/ARMGEO.s3o",
	script = "Units/ARMGEO.cob",
	seismicsignature = 0,
	selfdestructas = "geo",
	sightdistance = 273,
	yardmap = "h cbobbobc boboobob obbggbbo bogbbgob bogbbgob obbggbbo boboobob cbobbobc",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armgeo_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		cvbuildable = true,
		geothermal = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 70 60",
			collisionvolumetype = "Box",
			damage = 1050,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 338,
			object = "Units/armgeo_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 525,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 135,
			object = "Units/arm4X4B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "geothrm1",
		},
	},
},




coradvsol = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 4000,
	metalcost = 370,
	buildpic = "CORADVSOL.DDS",
	buildtime = 8150,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -2",
	collisionvolumescales = "57 35 57",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	damagemodifier = 0.9,
	energymake = 75,
	energystorage = 100,
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1200,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORADVSOL.s3o",
	script = "Units/CORADVSOL.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 260,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/coradvsol_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		solar = true,
		subfolder = "corbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -27 -1",
			collisionvolumescales = "60 112 58",
			collisionvolumetype = "Ell",
			damage = 648,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 12,
			hitdensity = 100,
			metal = 231,
			object = "Units/coradvsol_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 324,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 92,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "solar2",
		canceldestruct = "cancel2",
		deactivate = "solar2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "solar2",
		},
	},
},


freefusion = {
    unitrestricted = 1,
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 50,
	metalcost = 40,
	buildpic = "FREEFUSION.DDS",
	buildtime = 800,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	corpse = "DEAD",
	energymake = 850,
	energystorage = 150,
	explodeas = "fusionExplosion",
	footprintx = 5,
	footprintz = 5,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 560,
	maxslope = 20,
	maxwaterdepth = 0,
	objectname = "Units/freefusion.s3o",
	seismicsignature = 0,
	selfdestructas = "fusionExplosionSelfd",
	sightdistance = 250,
	yardmap = "ooooooooooooooooooooooooo",
	customparams = {
		removestop = true,
		removewait = true,
		subfolder = "other",
		techlevel = 1,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			damage = 2500,
			energy = 0,
			featuredead = "HEAP",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 30,
			object = "Units/freefusion_dead.s3o",
			reclaimable = true,
			customparams = {
				faction = "none",
			},
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1350,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 5,
			hitdensity = 100,
			metal = 10,
			object = "Units/arm5X5A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},



armmstor = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 570,
	metalcost = 330,
	buildpic = "ARMMSTOR.DDS",
	buildtime = 2920,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "56 61 56",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 2100,
	maxslope = 10,
	maxwaterdepth = 0,
	metalstorage = 3000,
	objectname = "Units/ARMMSTOR.s3o",
	script = "Units/ARMMSTOR.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armmstor_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.224998474121 -2.43896484378e-05 0.229019165039",
			collisionvolumescales = "55.897567749 35.6887512207 72.7919311523",
			collisionvolumetype = "Box",
			damage = 1595,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 198,
			object = "Units/armmstor_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 798,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 79,
			object = "Units/arm4X4E.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "stormtl1",
		},
	},
},




armestor = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 1700,
	metalcost = 170,
	buildpic = "ARMESTOR.DDS",
	buildtime = 4110,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "42 34 42",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 6000,
	explodeas = "energystorage",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1890,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMESTOR.s3o",
	script = "Units/ARMESTOR.cob",
	seismicsignature = 0,
	selfdestructas = "energystorageSelfd",
	sightdistance = 273,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armestor_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0361251831055 -3.17626953112e-05 -0.330192565918",
			collisionvolumescales = "39.6697540283 34.9461364746 42.0973052979",
			collisionvolumetype = "Box",
			damage = 1020,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 103,
			object = "Units/armestor_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 510,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 41,
			object = "Units/arm4X4C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "storngy1",
		},
	},
},