Wall - "cordrag",
Radar - "armrad",
Jammer - "armjamt",
Shield - "corfgate",
Alt - "armtarg",



cordrag = {
	maxacc = 0,
	autoheal = 4,
	blocking = true,
	maxdec = 0,
	energycost = 0,
	metalcost = 8,
	buildpic = "CORDRAG.DDS",
	buildtime = 255,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "32 22 32",
	collisionvolumetype = "CylY",
	corpse = "ROCKTEETH",
	crushresistance = 250,
	explodeas = "WallExplosionConcrete",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	idleautoheal = 0,
	levelground = false,
	health = 2800,
	maxslope = 64,
	maxwaterdepth = 0,
	objectname = "Units/cordrag.s3o",
	repairable = false,
	script = "Units/cordrag.cob",
	seismicsignature = 0,
	selfdestructas = "WallExplosionConcrete",
	selfdestructcountdown = 1,
	sightdistance = 1,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cordrag_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		objectify = true,
		paralyzemultiplier = 0,
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
	},
	featuredefs = {
		rockteeth = {
			animating = 0,
			animtrans = 0,
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			crushresistance = 0,
			damage = 500,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2,
			object = "Units/cor1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {},
	},
},


armrad = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 630,
	metalcost = 60,
	buildpic = "ARMRAD.DDS",
	buildtime = 1140,
	canattack = false,
	canrepeat = false,
	cantbetransported = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 66,
	mass = 5100,
	health = 90,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMRAD.s3o",
	onoffable = false,
	radardistance = 2100,
	radaremitheight = 66,
	script = "Units/ARMRAD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 680,
	usepiececollisionvolumes = 1,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armrad_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-1.52809143066 -0.0377662597656 8.02375793457",
			collisionvolumescales = "46.8276062012 74.2716674805 38.2336730957",
			collisionvolumetype = "Box",
			damage = 49,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 35,
			object = "Units/armrad_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 25,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 14,
			object = "Units/arm2X2A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t1_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		activate = "cmd-on",
		canceldestruct = "cancel2",
		deactivate = "cmd-off",
		underattack = "warning1",
		working = "cmd-on",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "radarselect",
		},
	},
},



armjamt = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4400,
	energycost = 8500,
	metalcost = 240,
	buildpic = "ARMJAMT.DDS",
	buildtime = 9950,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	cloakcost = 25,
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "32 82 32",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energyupkeep = 40,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 790,
	maxslope = 10,
	maxwaterdepth = 0,
	mincloakdistance = 35,
	objectname = "Units/ARMJAMT.s3o",
	onoffable = true,
	radardistancejam = 500,
	script = "Units/ARMJAMT.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 195,
	yardmap = "oooo",
	customparams = {
		unitgroup = 'util',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-7.62939453125e-06 -2.49999949951 -0.0",
			collisionvolumescales = "28.2096405029 67.270401001 28.2096252441",
			collisionvolumetype = "Box",
			damage = 427,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 3,
			hitdensity = 100,
			metal = 147,
			object = "Units/armjamt_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "kbarmmov",
		},
		select = {
			[1] = "radjam1",
		},
	},
},



corfgate = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 2048,
	energycost = 74000,
	metalcost = 4100,
	builder = 0,
	buildpic = "CORFGATE.DDS",
	buildtime = 59000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR",
	collisionvolumeoffsets = "0 -25 0",
	collisionvolumescales = "60 70 60",
	collisionvolumetype = "cyly",
	corpse = "DEAD",
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 4100,
	maxslope = 10,
	speed = 0.0,
	minwaterdepth = 16,
	noautofire = true,
	norestrict = 1,
	objectname = "Units/corfgate.s3o",
	onoffable = false,
	script = "Units/corfgate.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 600,
	turninplaceanglelimit = 140,
	turninplacespeedlimit = 0,
	turnrate = 0,
	unitname = "corfgate",
	waterline = 0,
	workertime = 0,
	customparams = {
		unitgroup = 'util',
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		shield_color_mult = 0.8,
		shield_power = 5000,
		shield_radius = 600,
		subfolder = "corbuildings/seautil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -2.91625976558e-05 -0.414924621582",
			collisionvolumescales = "57.2399902344 32.5033416748 63.3298492432",
			collisionvolumetype = "Box",
			damage = 1800,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2296,
			object = "Units/corfgate_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 900,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 918,
			object = "Units/cor2X2D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "drone1",
		},
		select = {
			[1] = "drone1",
		},
	},
	weapondefs = {
		sea_repulsor = {
			avoidfeature = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			name = "NavalPlasmaRepulsor",
			range = 600,
			soundhitwet = "sizzle",
			weapontype = "Shield",
			damage = {
				default = 100,
			},
			shield = {
				alpha = 0.17,
				armortype = "shields",
				energyupkeep = 0,
				force = 2.5,
				intercepttype = 1,
				power = 3250,
				powerregen = 52,
				powerregenenergy = 562.5,
				radius = 600,
				repulser = true,
				smart = true,
				startingpower = 1100,
				visiblerepulse = true,
				badcolor = {
					[1] = 1,
					[2] = 0.2,
					[3] = 0.2,
					[4] = 0.2,
				},
				goodcolor = {
					[1] = 0.2,
					[2] = 1,
					[3] = 0.2,
					[4] = 0.17,
				},
			},
		},
	},
	weapons = {
		[1] = {
			def = "SEA_REPULSOR",
			onlytargetcategory = "NOTSUB",
		},
	},
},




armtarg = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 7200,
	metalcost = 810,
	buildpic = "ARMTARG.DDS",
	buildtime = 8700,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "55 80 55",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energyupkeep = 100,
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	istargetingupgrade = true,
	health = 2100,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMTARG.s3o",
	onoffable = true,
	script = "Units/ARMTARG.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armtarg_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "55 80 55",
			collisionvolumetype = "cylY",
			damage = 1140,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 492,
			object = "Units/armtarg_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 570,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 197,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "cmd-on",
		canceldestruct = "cancel2",
		deactivate = "cmd-off",
		underattack = "warning1",
		working = "cmd-on",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "targsel1",
		},
	},
},