Wall - "armfort",
Radar & vision - "corarad",
Jammer - "corshroud",
Shield - "armfgate",
Alt - (faster stockpiling / firing, smaller radius) "armamd",

armfort = {
	maxacc = 0,
	autoheal = 12,
	blocking = true,
	maxdec = 0,
	buildangle = 0,
	energycost = 500,
	metalcost = 40,
	buildpic = "ARMFORT.DDS",
	buildtime = 900,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "32 50 32",
	collisionvolumetype = "CylY",
	corpse = "ROCKTEETHX",
	crushresistance = 1000,
	explodeas = "WallExplosionMetalXL",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	idleautoheal = 0,
	levelground = false,
	health = 8900,
	maxslope = 24,
	maxwaterdepth = 0,
	objectname = "Units/ARMFORT.s3o",
	repairable = false,
	script = "Units/ARMFORT.cob",
	seismicsignature = 0,
	selfdestructas = "WallExplosionMetal",
	selfdestructcountdown = 1,
	sightdistance = 1,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armfort_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		objectify = true,
		paralyzemultiplier = 0,
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		rockteethx = {
			animating = 0,
			animtrans = 0,
			blocking = true,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			crushresistance = 0,
			damage = 3000,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 7,
			object = "Units/arm1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},



corarad = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 19000,
	metalcost = 560,
	buildpic = "CORARAD.DDS",
	buildtime = 12000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "35 98 35",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "smallBuildingExplosionGeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 87,
	health = 365,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORARAD.s3o",
	onoffable = false,
	radardistance = 3500,
	radaremitheight = 87,
	script = "Units/CORARAD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 780,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corarad_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0 ",
			collisionvolumescales = "37.4503479004 89.5777740479 30.4736785889",
			collisionvolumetype = "Cyly",
			damage = 198,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			hitdensity = 100,
			metal = 339,
			object = "Units/corarad_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 99,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 136,
			object = "Units/cor3X3C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t2_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "radadvn2",
		canceldestruct = "cancel2",
		deactivate = "radadde2",
		underattack = "warning1",
		working = "radar2",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "radadvn2",
		},
	},
},




corshroud = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 20000,
	metalcost = 130,
	buildpic = "CORSHROUD.DDS",
	buildtime = 9400,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 16 -2",
	collisionvolumescales = "34 93 34",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energyupkeep = 125,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 890,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORSHROUD.s3o",
	onoffable = true,
	radardistancejam = 700,
	script = "Units/CORSHROUD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 155,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corshroud_aoplane.dds",
		buildinggrounddecalsizey = 3.8,
		buildinggrounddecalsizex = 3.8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-7.38106536865 2.64404296892e-05 2.18940734863",
			collisionvolumescales = "57.2317047119 61.2454528809 48.0499572754",
			collisionvolumetype = "Box",
			damage = 480,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 81,
			object = "Units/corshroud_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 240,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 32,
			object = "Units/cor2X2A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "kbcormov",
		},
		select = {
			[1] = "radjam2",
		},
	},
},



armfgate = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 2048,
	energycost = 72000,
	metalcost = 3900,
	builder = 0,
	buildpic = "ARMFGATE.DDS",
	buildtime = 59000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR",
	collisionvolumeoffsets = "0 -30 0",
	collisionvolumescales = "53 65 53",
	collisionvolumetype = "cyly",
	corpse = "DEAD",
	explodeas = "hugeBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3900,
	maxslope = 10,
	speed = 0.0,
	minwaterdepth = 16,
	noautofire = true,
	norestrict = 1,
	objectname = "Units/armfgate.s3o",
	onoffable = false,
	script = "Units/armfgate.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 600,
	turninplaceanglelimit = 140,
	turninplacespeedlimit = 0,
	turnrate = 0,
	unitname = "armfgate",
	waterline = 0,
	workertime = 0,
	customparams = {
		unitgroup = 'util',
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		shield_color_mult = 0.8,
		shield_power = 5000,
		shield_radius = 600,
		subfolder = "armbuildings/seautil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -2.91625976558e-05 -0.414924621582",
			collisionvolumescales = "57.2399902344 32.5033416748 63.3298492432",
			collisionvolumetype = "Box",
			damage = 1800,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2296,
			object = "Units/armfgate_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 900,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 918,
			object = "Units/arm2X2D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "drone1",
		},
		select = {
			[1] = "drone1",
		},
	},
	weapondefs = {
		sea_repulsor = {
			avoidfeature = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			name = "NavalPlasmaRepulsor",
			range = 600,
			soundhitwet = "sizzle",
			weapontype = "Shield",
			damage = {
				default = 100,
			},
			shield = {
				alpha = 0.17,
				armortype = "shields",
				energyupkeep = 0,
				force = 2.5,
				intercepttype = 1,
				power = 3250,
				powerregen = 52,
				powerregenenergy = 562.5,
				radius = 600,
				repulser = true,
				smart = true,
				startingpower = 1100,
				visiblerepulse = true,
				badcolor = {
					[1] = 1,
					[2] = 0.2,
					[3] = 0.2,
					[4] = 0.2,
				},
				goodcolor = {
					[1] = 0.2,
					[2] = 1,
					[3] = 0.2,
					[4] = 0.17,
				},
			},
		},
	},
	weapons = {
		[1] = {
			def = "SEA_REPULSOR",
			onlytargetcategory = "NOTSUB",
		},
	},
},



armamd = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 4096,
	energycost = 38000,
	metalcost = 1500,
	buildpic = "ARMAMD.DDS",
	buildtime = 60000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -1",
	collisionvolumescales = "53 78 53",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "largeexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3650,
	maxslope = 10,
	maxwaterdepth = 0,
	noautofire = true,
	objectname = "Units/ARMAMD.s3o",
	radardistance = 50,
	script = "Units/ARMAMD.cob",
	seismicsignature = 0,
	selfdestructas = "largeExplosionGenericSelfd",
	sightdistance = 201,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armamd_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'antinuke',
		model_author = "FireStorm",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "53 78 53",
			collisionvolumetype = "Box",
			damage = 1980,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 6,
			height = 20,
			hitdensity = 100,
			metal = 934,
			object = "Units/armamd_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 990,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 374,
			object = "Units/arm5X5B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "loadwtr2",
		},
		select = {
			[1] = "loadwtr2",
		},
	},
	weapondefs = {
		amd_rocket = {
			areaofeffect = 420,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			cegtag = "antimissiletrail",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			coverage = 2000,
			craterareaofeffect = 420,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 7500,
			explosiongenerator = "custom:antinuke",
			firestarter = 100,
			flighttime = 20,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			interceptor = 1,
			metalpershot = 150,
			model = "fmdmissile.s3o",
			name = "ICBM intercepting missile launcher",
			noselfdamage = true,
			range = 72000,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 110,
			smokesize = 27,
			smokecolor = 0.70,
			smokeTrailCastShadow = true,
			soundhit = "xplomed4",
			soundhitwet = "splslrg",
			soundstart = "antinukelaunch",
			stockpile = true,
			stockpiletime = 90,
			texture1 = "bluenovaexplo",
			texture2 = "smoketrailbar",
			texture3 = "null",
			tolerance = 7000,
			tracks = true,
			turnrate = 10000,
			weaponacceleration = 150,
			weapontimer = 3,
			weapontype = "StarburstLauncher",
			weaponvelocity = 6000,
			damage = {
				default = 1500,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "ALL",
			def = "AMD_ROCKET",
		},
	},
},