					---  Utilities ----
-- Tier 1 -----

-- Radar = armrad
-- Jammer = armjamt
-- Safe E Store = corestor
-- Safe M Store = cormstor
-- Wall = corscavdrag
-- Shield = None (or something)

-- Tier 2 -----

-- Radar & Vision = corrad
-- Jammer = corjamt
-- Volatile E Store = armestor
-- Volatile M Store = armmstor
-- Wall = corfort
-- Shield = corgate 
-- Anti Nuke = corfmd

--  Tier 3 -------
-- Radar = armarad (Ideally armmason if this naval unit can be build on land, it would be the primary vision provider)
-- Jammer = armveil
-- Safe E Store = coruwadves
-- Safe M Store = coruwadvms
-- Wall = corscavfort
-- Shield = None (or something)
-- Anti Nuke = corsd

-- Tier 4 ------
-- Radar & Vision = corarad
-- Jammer = corshroud
-- Safe E Store = armuwadves
-- Safe M Store = armuwadvms
-- Wall = armfort
-- Shield = armgate
-- Anti Nuke = armamd


--  Underwater Sonar, will be advanced vision if buildable on land ---

armason = {
	acceleration = 0,
	activatewhenbuilt = true,
	brakerate = 0,
	buildangle = 8192,
	buildcostenergy = 2600,
	buildcostmetal = 170,
	buildpic = "ARMASON.DDS",
	buildtime = 6152,
	canattack = false,
	canrepeat = false,
	category = "ALL UNDERWATER NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	damagemodifier = 0.46,
	explodeas = "mediumBuildingexplosiongeneric-uw",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 2350,
	maxslope = 10,
	minwaterdepth = 0,
	maxwaterdeapth = 24
	objectname = "Units/ARMASON.s3o",
	onoffable = true,
	sightdistance = 3500,
	sonardistance = 0,
	customparams = {
		subfolder = "armbuildings/seautil",
		techlevel = 2,
	},
},



	-- Tier 1 --

armrad = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 630,
	metalcost = 60,
	buildpic = "ARMRAD.DDS",
	buildtime = 1140,
	canattack = false,
	canrepeat = false,
	cantbetransported = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 66,
	mass = 5100,
	health = 90,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMRAD.s3o",
	onoffable = false,
	radardistance = 2100,
	radaremitheight = 66,
	script = "Units/ARMRAD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 680,
	usepiececollisionvolumes = 1,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armrad_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-1.52809143066 -0.0377662597656 8.02375793457",
			collisionvolumescales = "46.8276062012 74.2716674805 38.2336730957",
			collisionvolumetype = "Box",
			damage = 49,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 35,
			object = "Units/armrad_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 25,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 14,
			object = "Units/arm2X2A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t1_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		activate = "cmd-on",
		canceldestruct = "cancel2",
		deactivate = "cmd-off",
		underattack = "warning1",
		working = "cmd-on",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "radarselect",
		},
	},
},

armjamt = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4400,
	energycost = 8500,
	metalcost = 240,
	buildpic = "ARMJAMT.DDS",
	buildtime = 9950,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	cloakcost = 25,
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "32 82 32",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energyupkeep = 40,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 790,
	maxslope = 10,
	maxwaterdepth = 0,
	mincloakdistance = 35,
	objectname = "Units/ARMJAMT.s3o",
	onoffable = true,
	radardistancejam = 500,
	script = "Units/ARMJAMT.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 195,
	yardmap = "oooo",
	customparams = {
		unitgroup = 'util',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-7.62939453125e-06 -2.49999949951 -0.0",
			collisionvolumescales = "28.2096405029 67.270401001 28.2096252441",
			collisionvolumetype = "Box",
			damage = 427,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 3,
			hitdensity = 100,
			metal = 147,
			object = "Units/armjamt_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "kbarmmov",
		},
		select = {
			[1] = "radjam1",
		},
	},
},

corestor = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8196,
	energycost = 1800,
	metalcost = 175,
	buildpic = "CORESTOR.DDS",
	buildtime = 4260,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -1 0",
	collisionvolumescales = "60 35 60",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 6000,
	explodeas = "energystorage",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 2000,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORESTOR.s3o",
	script = "Units/CORESTOR.cob",
	seismicsignature = 0,
	selfdestructas = "energystorageSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corestor_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-1.1330871582 -3.52050781238e-05 -0.0",
			collisionvolumescales = "61.5478820801 36.5253295898 59.2817077637",
			collisionvolumetype = "Box",
			damage = 1080,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 108,
			object = "Units/corestor_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 540,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 43,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "storngy2",
		},
	},
},

cormstor = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	energycost = 590,
	metalcost = 340,
	buildpic = "CORMSTOR.DDS",
	buildtime = 2920,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -10 0",
	collisionvolumescales = "64 60 64",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 2100,
	maxslope = 10,
	maxwaterdepth = 0,
	metalstorage = 3000,
	objectname = "Units/CORMSTOR.s3o",
	script = "Units/CORMSTOR.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "oooo oooo oooo oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cormstor_aoplane.dds",
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "80 40 80",
			collisionvolumetype = "Box",
			damage = 1567,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 208,
			object = "Units/cormstor_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 784,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 83,
			object = "Units/cor5X5A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "stormtl2",
		},
	},
},

corscavdrag = {
	maxacc = 0,
	autoheal = 4,
	blocking = true,
	maxdec = 0,
	energycost = 0,
	metalcost = 8,
	buildpic = "scavengers/CORSCAVDRAG.DDS",
	buildtime = 255,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "32 22 32",
	collisionvolumetype = "CylY",
	corpse = "ROCKTEETH",
	crushresistance = 250,
	explodeas = "WallExplosionConcrete",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	idleautoheal = 0,
	levelground = false,
	health = 2800,
	maxslope = 64,
	maxwaterdepth = 0,
	objectname = "scavs/scavdrag.s3o",
	repairable = false,
	script = "Units/cordrag.cob",
	seismicsignature = 0,
	selfdestructas = "WallExplosionConcrete",
	selfdestructcountdown = 1,
	sightdistance = 1,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = false,
		buildinggrounddecaltype = "decals/scavdtf_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		objectify = true,
		paralyzemultiplier = 0,
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
	},
	featuredefs = {
		rockteeth = {
			animating = 0,
			animtrans = 0,
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			crushresistance = 0,
			damage = 500,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2,
			object = "Units/cor1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {},
	},
},

	-- Tier 2 ---

corrad = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 16000,
	energycost = 630,
	metalcost = 60,
	buildpic = "CORRAD.DDS",
	buildtime = 1140,
	canattack = false,
	canrepeat = false,
	cantbetransported = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -12 0",
	collisionvolumescales = "32 99 32",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 72,
	mass = 5100,
	health = 90,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORRAD.s3o",
	onoffable = false,
	radardistance = 2100,
	radaremitheight = 72,
	script = "Units/CORRAD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 680,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corrad_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.353988647461 -0.0323567626953 1.37395477295",
			collisionvolumescales = "34.8413696289 57.1648864746 30.8629608154",
			collisionvolumetype = "Box",
			damage = 49,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 36,
			object = "Units/corrad_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 25,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 14,
			object = "Units/cor2X2D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t1_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		activate = "cmd-on",
		canceldestruct = "cancel2",
		deactivate = "cmd-off",
		underattack = "warning1",
		working = "cmd-on",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "radarselect",
		},
	},
},

corjamt = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 9821,
	energycost = 5200,
	metalcost = 115,
	buildpic = "CORJAMT.DDS",
	buildtime = 4570,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "30 37 30",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energyupkeep = 25,
	explodeas = "smallexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1070,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORJAMT.s3o",
	onoffable = true,
	radardistancejam = 360,
	script = "Units/CORJAMT.cob",
	seismicsignature = 0,
	selfdestructas = "smallExplosionGenericSelfd",
	sightdistance = 104,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corjamt_aoplane.dds",
		buildinggrounddecalsizey = 3.6,
		buildinggrounddecalsizex = 3.6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -2 0",
			collisionvolumescales = "30 35 30",
			collisionvolumetype = "CylY",
			damage = 576,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 3,
			hitdensity = 100,
			metal = 71,
			object = "Units/corjamt_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "kbcormov",
		},
		select = {
			[1] = "radjam2",
		},
	},
},

armestor = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 1700,
	metalcost = 170,
	buildpic = "ARMESTOR.DDS",
	buildtime = 4110,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "42 34 42",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 6000,
	explodeas = "energystorage",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1890,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMESTOR.s3o",
	script = "Units/ARMESTOR.cob",
	seismicsignature = 0,
	selfdestructas = "energystorageSelfd",
	sightdistance = 273,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armestor_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0361251831055 -3.17626953112e-05 -0.330192565918",
			collisionvolumescales = "39.6697540283 34.9461364746 42.0973052979",
			collisionvolumetype = "Box",
			damage = 1020,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 103,
			object = "Units/armestor_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 510,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 41,
			object = "Units/arm4X4C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "storngy1",
		},
	},
},

armmstor = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 570,
	metalcost = 330,
	buildpic = "ARMMSTOR.DDS",
	buildtime = 2920,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "56 61 56",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 2100,
	maxslope = 10,
	maxwaterdepth = 0,
	metalstorage = 3000,
	objectname = "Units/ARMMSTOR.s3o",
	script = "Units/ARMMSTOR.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armmstor_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.224998474121 -2.43896484378e-05 0.229019165039",
			collisionvolumescales = "55.897567749 35.6887512207 72.7919311523",
			collisionvolumetype = "Box",
			damage = 1595,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 198,
			object = "Units/armmstor_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 798,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 79,
			object = "Units/arm4X4E.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "stormtl1",
		},
	},
},

corfort = {
	maxacc = 0,
	autoheal = 12,
	blocking = true,
	maxdec = 0,
	buildangle = 0,
	energycost = 500,
	metalcost = 40,
	buildpic = "CORFORT.DDS",
	buildtime = 900,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	collisionvolumeoffsets = "0 -4 0",
	collisionvolumescales = "32 52 32",
	collisionvolumetype = "CylY",
	corpse = "ROCKTEETHX",
	crushresistance = 1000,
	explodeas = "WallExplosionConcreteXL",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	idleautoheal = 0,
	levelground = false,
	health = 8900,
	maxslope = 24,
	maxwaterdepth = 0,
	objectname = "Units/CORFORT.s3o",
	repairable = false,
	script = "Units/CORFORT.cob",
	seismicsignature = 0,
	selfdestructas = "WallExplosionConcrete",
	selfdestructcountdown = 1,
	sightdistance = 1,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corfort_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		objectify = true,
		paralyzemultiplier = 0,
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		rockteethx = {
			animating = 0,
			animtrans = 0,
			blocking = true,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			crushresistance = 0,
			damage = 3000,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 7,
			object = "Units/cor1X1B.s3o",
			reclaimable = true,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},

corgate = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 2048,
	energycost = 55000,
	metalcost = 3200,
	buildpic = "CORGATE.DDS",
	buildtime = 55000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -4 1",
	collisionvolumescales = "57 38 57",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 1000,
	explodeas = "hugeBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3550,
	maxslope = 10,
	maxwaterdepth = 0,
	noautofire = true,
	objectname = "Units/CORGATE.s3o",
	onoffable = false,
	script = "Units/CORGATE.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corgate_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		shield_color_mult = 0.8,
		shield_power = 3250,
		shield_radius = 550,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -0.00271934814453 -1.05072021484",
			collisionvolumescales = "65.7474060059 27.1259613037 55.6685791016",
			collisionvolumetype = "Box",
			damage = 1900,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2000,
			object = "Units/corgate_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 960,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 800,
			object = "Units/cor2X2E.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "drone1",
		},
		select = {
			[1] = "drone1",
		},
	},
	weapondefs = {
		repulsor = {
			avoidfeature = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			name = "PlasmaRepulsor",
			range = 550,
			soundhitwet = "sizzle",
			weapontype = "Shield",
			damage = {
				default = 100,
			},
			shield = {
				alpha = 0.17,
				armortype = "shields",
				energyupkeep = 0,
				force = 2.5,
				intercepttype = 1,
				power = 3250,
				powerregen = 52,
				powerregenenergy = 562.5,
				radius = 550,
				repulser = true,
				smart = true,
				startingpower = 1100,
				visiblerepulse = true,
				badcolor = {
					[1] = 1,
					[2] = 0.2,
					[3] = 0.2,
					[4] = 0.2,
				},
				goodcolor = {
					[1] = 0.2,
					[2] = 1,
					[3] = 0.2,
					[4] = 0.17,
				},
			},
		},
	},
	weapons = {
		[1] = {
			def = "REPULSOR",
			onlytargetcategory = "NOTSUB",
		},
	},
},

corfmd = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 4096,
	energycost = 40000,
	metalcost = 1500,
	buildpic = "CORFMD.DDS",
	buildtime = 60000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -19 0",
	collisionvolumescales = "48 78 48",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "largeexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3650,
	maxslope = 10,
	maxwaterdepth = 0,
	noautofire = true,
	objectname = "Units/CORFMD.s3o",
	radardistance = 50,
	script = "Units/CORFMD.cob",
	seismicsignature = 0,
	selfdestructas = "largeExplosionGenericSelfd",
	sightdistance = 195,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corfmd_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'antinuke',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -1.36962890629e-05 -0.0",
			collisionvolumescales = "48.0 37.2831726074 48.0",
			collisionvolumetype = "Box",
			damage = 1968,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 980,
			object = "Units/corfmd_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 984,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 392,
			object = "Units/cor5X5D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "loadwtr1",
		},
		select = {
			[1] = "loadwtr1",
		},
	},
	weapondefs = {
		fmd_rocket = {
			areaofeffect = 420,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			cegtag = "antimissiletrail",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			coverage = 2000,
			craterareaofeffect = 420,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 7500,
			explosiongenerator = "custom:antinuke",
			firestarter = 100,
			flighttime = 20,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			interceptor = 1,
			metalpershot = 150,
			model = "fmdmissile.s3o",
			name = "ICBM intercepting missile launcher",
			noselfdamage = true,
			range = 72000,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 110,
			smokesize = 27,
			smokecolor = 0.70,
			smokeTrailCastShadow = true,
			soundhit = "xplomed4",
			soundhitwet = "splslrg",
			soundstart = "antinukelaunch",
			stockpile = true,
			stockpiletime = 90,
			texture1 = "bluenovaexplo",
			texture2 = "smoketrailbar",
			texture3 = "null",
			tolerance = 7000,
			tracks = true,
			turnrate = 10000,
			weaponacceleration = 150,
			weapontimer = 2.5,
			weapontype = "StarburstLauncher",
			weaponvelocity = 6000,
			damage = {
				default = 1500,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "ALL",
			def = "FMD_ROCKET",
		},
	},
},

		-- Tier 3 ---

armarad = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 19000,
	metalcost = 560,
	buildpic = "ARMARAD.DDS",
	buildtime = 11800,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 40,
	health = 355,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMARAD.s3o",
	onoffable = false,
	radardistance = 3500,
	radaremitheight = 66,
	script = "Units/ARMARAD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 820,
	usepiececollisionvolumes = 1,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armarad_aoplane.dds",
		buildinggrounddecalsizey = 3.6,
		buildinggrounddecalsizex = 3.6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "6.23959350586 -0.334806103516 -0.00547027587891",
			collisionvolumescales = "37.4791870117 33.549987793 30.0109405518",
			collisionvolumetype = "Box",
			damage = 192,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 40,
			hitdensity = 100,
			metal = 341,
			object = "Units/armarad_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 96,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 136,
			object = "Units/arm2X2C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t2_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "cmd-on",
		canceldestruct = "cancel2",
		deactivate = "cmd-off",
		underattack = "warning1",
		working = "cmd-on",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "radadvn1",
		},
	},
},

armveil = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 19000,
	metalcost = 125,
	buildpic = "ARMVEIL.DDS",
	buildtime = 9100,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	energyupkeep = 125,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 830,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMVEIL.s3o",
	onoffable = true,
	radardistancejam = 760,
	script = "Units/ARMVEIL.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 155,
	usepiececollisionvolumes = 1,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armveil_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-7.16355133057 1.47216796904e-05 -4.91466522217",
			collisionvolumescales = "47.5629425049 83.2464294434 33.8293304443",
			collisionvolumetype = "Box",
			damage = 450,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 77,
			object = "Units/armveil_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 225,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 31,
			object = "Units/arm2X2A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "kbarmmov",
		},
		select = {
			[1] = "radjam1",
		},
	},
},

coruwadves = {
	buildangle = 7822,
	energycost = 11000,
	metalcost = 840,
	buildpic = "CORUWADVES.DDS",
	buildtime = 20400,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE UNDERWATER EMPABLE",
	collisionvolumeoffsets = "0 -16 0",
	collisionvolumescales = "90 65 90",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 40000,
	explodeas = "advenergystorage",
	footprintx = 5,
	footprintz = 5,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 12700,
	maxslope = 20,
	maxwaterdepth = 9999,
	objectname = "Units/CORUWADVES.s3o",
	script = "Units/CORUWADVES.cob",
	seismicsignature = 0,
	selfdestructas = "advenergystorageSelfd",
	sightdistance = 192,
	yardmap = "ooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/coruwadves_aoplane.dds",
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/seaeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-2.07458496094 4.21508789046e-05 -0.501388549805",
			collisionvolumescales = "87.0777893066 35.5382843018 90.1298522949",
			collisionvolumetype = "Box",
			damage = 4560,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 9,
			hitdensity = 100,
			metal = 514,
			object = "Units/coruwadves_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 2280,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			hitdensity = 100,
			metal = 206,
			object = "Units/cor5X5A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "storngy2",
		},
	},
},

coruwadvms = {
	buildangle = 6093,
	energycost = 11000,
	metalcost = 760,
	buildpic = "CORUWADVMS.DDS",
	buildtime = 20500,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE UNDERWATER EMPABLE",
	collisionvolumeoffsets = "-6 0 0",
	collisionvolumescales = "46 40 58",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 11200,
	maxslope = 20,
	maxwaterdepth = 9999,
	metalstorage = 10000,
	objectname = "Units/CORUWADVMS.s3o",
	script = "Units/CORUWADVMS.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 182,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/coruwadvms_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/seaeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-8.0463180542 -4.28710937506e-05 2.1676940918",
			collisionvolumescales = "49.8645172119 42.9171142578 64.3353881836",
			collisionvolumetype = "Box",
			damage = 4020,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 9,
			hitdensity = 100,
			metal = 462,
			object = "Units/coruwadvms_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 2010,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 185,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "stormtl2",
		},
	},
},

corscavfort = {
	maxacc = 0,
	autoheal = 12,
	blocking = true,
	maxdec = 0,
	buildangle = 0,
	energycost = 500,
	metalcost = 40,
	buildpic = "scavengers/SCAVFORT.DDS",
	buildtime = 1000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "32 50 32",
	collisionvolumetype = "CylY",
	corpse = "ROCKTEETHX",
	crushresistance = 1000,
	explodeas = "WallExplosionConcreteXL",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	idleautoheal = 0,
	levelground = false,
	health = 8900,
	maxslope = 24,
	maxwaterdepth = 0,
	objectname = "scavs/SCAVFORT.s3o",
	repairable = false,
	script = "scavs/SCAVFORT.cob",
	seismicsignature = 0,
	selfdestructas = "WallExplosionConcrete",
	selfdestructcountdown = 1,
	sightdistance = 1,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = false,
		buildinggrounddecaltype = "decals/corscavfort_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		model_author = "FireStorm",
		normaltex = "unittextures/cor_normal.dds",
		objectify = true,
		paralyzemultiplier = 0,
		removestop = true,
		removewait = true,
		subfolder = "other/scavengers",
		--techlevel = 2,
	},
	featuredefs = {
		rockteethx = {
			animating = 0,
			animtrans = 0,
			blocking = true,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			crushresistance = 0,
			damage = 3000,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 7,
			object = "Units/cor1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},

corsd = {
	activatewhenbuilt = true,
	buildangle = 4096,
	energycost = 6700,
	metalcost = 750,
	buildpic = "CORSD.DDS",
	buildtime = 12000,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -1 0",
	collisionvolumescales = "65 10 60",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energyupkeep = 125,
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	levelground = false,
	health = 2800,
	maxslope = 36,
	maxwaterdepth = 0,
	objectname = "Units/CORSD.s3o",
	onoffable = true,
	script = "Units/CORSD.cob",
	seismicdistance = 2000,
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 225,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corsd_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-1.15772247314 -1.86200052979 2.43579101563",
			collisionvolumescales = "68.8967437744 12.3805389404 66.8254699707",
			collisionvolumetype = "Box",
			damage = 1500,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 15,
			hitdensity = 100,
			metal = 584,
			object = "Units/corsd_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 750,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 234,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "targon2",
		canceldestruct = "cancel2",
		deactivate = "targoff2",
		underattack = "warning1",
		working = "targsel2",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "targsel2",
		},
	},
},


		--Tier 4 ---

corarad = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 19000,
	metalcost = 560,
	buildpic = "CORARAD.DDS",
	buildtime = 12000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "35 98 35",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "smallBuildingExplosionGeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 87,
	health = 365,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORARAD.s3o",
	onoffable = false,
	radardistance = 3500,
	radaremitheight = 87,
	script = "Units/CORARAD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 780,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corarad_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0 ",
			collisionvolumescales = "37.4503479004 89.5777740479 30.4736785889",
			collisionvolumetype = "Cyly",
			damage = 198,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			hitdensity = 100,
			metal = 339,
			object = "Units/corarad_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 99,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 136,
			object = "Units/cor3X3C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t2_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "radadvn2",
		canceldestruct = "cancel2",
		deactivate = "radadde2",
		underattack = "warning1",
		working = "radar2",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "radadvn2",
		},
	},
},

corshroud = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 20000,
	metalcost = 130,
	buildpic = "CORSHROUD.DDS",
	buildtime = 9400,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 16 -2",
	collisionvolumescales = "34 93 34",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energyupkeep = 125,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 890,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORSHROUD.s3o",
	onoffable = true,
	radardistancejam = 700,
	script = "Units/CORSHROUD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 155,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corshroud_aoplane.dds",
		buildinggrounddecalsizey = 3.8,
		buildinggrounddecalsizex = 3.8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-7.38106536865 2.64404296892e-05 2.18940734863",
			collisionvolumescales = "57.2317047119 61.2454528809 48.0499572754",
			collisionvolumetype = "Box",
			damage = 480,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 81,
			object = "Units/corshroud_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 240,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 32,
			object = "Units/cor2X2A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "kbcormov",
		},
		select = {
			[1] = "radjam2",
		},
	},
},

armuwadves = {
	buildangle = 8192,
	energycost = 10000,
	metalcost = 830,
	buildpic = "ARMUWADVES.DDS",
	buildtime = 20300,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE UNDERWATER EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "42 62 62",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energystorage = 40000,
	explodeas = "advenergystorage",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 11700,
	maxslope = 20,
	maxwaterdepth = 9999,
	objectname = "Units/ARMUWADVES.s3o",
	script = "Units/ARMUWADVES.cob",
	seismicsignature = 0,
	selfdestructas = "advenergystorageSelfd",
	sightdistance = 169,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armuwadves_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/seaeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "42 62 62",
			collisionvolumetype = "Box",
			damage = 4200,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 9,
			hitdensity = 100,
			metal = 502,
			object = "Units/armuwadves_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 2100,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 201,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "storngy1",
		},
	},
},


armuwadvms = {
	buildangle = 5049,
	energycost = 11500,
	metalcost = 750,
	buildpic = "ARMUWADVMS.DDS",
	buildtime = 20400,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE UNDERWATER EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "88 38 72",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 10300,
	maxslope = 20,
	maxwaterdepth = 9999,
	metalstorage = 10000,
	objectname = "Units/ARMUWADVMS.s3o",
	script = "Units/ARMUWADVMS.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 195,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armuwadvms_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 5.4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/seaeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "7.62939453125e-06 -3.51196289046e-05 -0.0",
			collisionvolumescales = "45.1519927979 49.1111297607 45.1520080566",
			collisionvolumetype = "Box",
			damage = 3720,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 9,
			hitdensity = 100,
			metal = 458,
			object = "Units/armuwadvms_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1860,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 183,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "stormtl1",
		},
	},
},

armfort = {
	maxacc = 0,
	autoheal = 12,
	blocking = true,
	maxdec = 0,
	buildangle = 0,
	energycost = 500,
	metalcost = 40,
	buildpic = "ARMFORT.DDS",
	buildtime = 900,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "32 50 32",
	collisionvolumetype = "CylY",
	corpse = "ROCKTEETHX",
	crushresistance = 1000,
	explodeas = "WallExplosionMetalXL",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	idleautoheal = 0,
	levelground = false,
	health = 8900,
	maxslope = 24,
	maxwaterdepth = 0,
	objectname = "Units/ARMFORT.s3o",
	repairable = false,
	script = "Units/ARMFORT.cob",
	seismicsignature = 0,
	selfdestructas = "WallExplosionMetal",
	selfdestructcountdown = 1,
	sightdistance = 1,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armfort_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		objectify = true,
		paralyzemultiplier = 0,
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		rockteethx = {
			animating = 0,
			animtrans = 0,
			blocking = true,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			crushresistance = 0,
			damage = 3000,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 7,
			object = "Units/arm1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},

armgate = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 2048,
	energycost = 54000,
	metalcost = 3000,
	buildpic = "ARMGATE.DDS",
	buildtime = 55000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 1",
	collisionvolumescales = "57 37 57",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 1000,
	explodeas = "hugeBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3550,
	maxslope = 10,
	maxwaterdepth = 0,
	noautofire = true,
	objectname = "Units/ARMGATE.s3o",
	onoffable = false,
	script = "Units/ARMGATE.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armgate_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		shield_color_mult = 0.8,
		shield_power = 3250,
		shield_radius = 550,
		subfolder = "armbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -2.91625976558e-05 -0.414924621582",
			collisionvolumescales = "57.2399902344 32.5033416748 63.3298492432",
			collisionvolumetype = "Box",
			damage = 1900,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2000,
			object = "Units/armgate_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 900,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 800,
			object = "Units/arm2X2D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "drone1",
		},
		select = {
			[1] = "drone1",
		},
	},
	weapondefs = {
		repulsor = {
			avoidfeature = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			name = "PlasmaRepulsor",
			range = 550,
			soundhitwet = "sizzle",
			weapontype = "Shield",
			damage = {
				default = 100,
			},
			shield = {
				alpha = 0.17,
				armortype = "shields",
				energyupkeep = 0,
				force = 2.5,
				intercepttype = 1,
				power = 3250,
				powerregen = 52,
				powerregenenergy = 562.5,
				radius = 550,
				repulser = true,
				smart = true,
				startingpower = 1100,
				visiblerepulse = true,
				badcolor = {
					[1] = 1,
					[2] = 0.2,
					[3] = 0.2,
					[4] = 0.2,
				},
				goodcolor = {
					[1] = 0.2,
					[2] = 1,
					[3] = 0.2,
					[4] = 0.17,
				},
			},
		},
	},
	weapons = {
		[1] = {
			def = "REPULSOR",
			onlytargetcategory = "NOTSUB",
		},
	},
},

armamd = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 4096,
	energycost = 38000,
	metalcost = 1500,
	buildpic = "ARMAMD.DDS",
	buildtime = 60000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -1",
	collisionvolumescales = "53 78 53",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "largeexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3650,
	maxslope = 10,
	maxwaterdepth = 0,
	noautofire = true,
	objectname = "Units/ARMAMD.s3o",
	radardistance = 50,
	script = "Units/ARMAMD.cob",
	seismicsignature = 0,
	selfdestructas = "largeExplosionGenericSelfd",
	sightdistance = 201,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armamd_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'antinuke',
		model_author = "FireStorm",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "53 78 53",
			collisionvolumetype = "Box",
			damage = 1980,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 6,
			height = 20,
			hitdensity = 100,
			metal = 934,
			object = "Units/armamd_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 990,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 374,
			object = "Units/arm5X5B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "loadwtr2",
		},
		select = {
			[1] = "loadwtr2",
		},
	},
	weapondefs = {
		amd_rocket = {
			areaofeffect = 420,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			cegtag = "antimissiletrail",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			coverage = 2000,
			craterareaofeffect = 420,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 7500,
			explosiongenerator = "custom:antinuke",
			firestarter = 100,
			flighttime = 20,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			interceptor = 1,
			metalpershot = 150,
			model = "fmdmissile.s3o",
			name = "ICBM intercepting missile launcher",
			noselfdamage = true,
			range = 72000,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 110,
			smokesize = 27,
			smokecolor = 0.70,
			smokeTrailCastShadow = true,
			soundhit = "xplomed4",
			soundhitwet = "splslrg",
			soundstart = "antinukelaunch",
			stockpile = true,
			stockpiletime = 90,
			texture1 = "bluenovaexplo",
			texture2 = "smoketrailbar",
			texture3 = "null",
			tolerance = 7000,
			tracks = true,
			turnrate = 10000,
			weaponacceleration = 150,
			weapontimer = 3,
			weapontype = "StarburstLauncher",
			weaponvelocity = 6000,
			damage = {
				default = 1500,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "ALL",
			def = "AMD_ROCKET",
		},
	},
},
