--  Underwater Sonar, will be advanced vision ---

armason = {
	acceleration = 0,
	activatewhenbuilt = true,
	brakerate = 0,
	buildangle = 8192,
	buildcostenergy = 2600,
	buildcostmetal = 170,
	buildpic = "ARMASON.DDS",
	buildtime = 6152,
	canattack = false,
	canrepeat = false,
	category = "ALL UNDERWATER NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	damagemodifier = 0.46,
	explodeas = "mediumBuildingexplosiongeneric-uw",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	maxdamage = 2350,
	maxslope = 10,
	minwaterdepth = 0,
	maxwaterdeapth = 24
	objectname = "Units/ARMASON.s3o",
	onoffable = true,
	sightdistance = 2500,
	sonardistance = 0,
	customparams = {
		subfolder = "armbuildings/seautil",
		techlevel = 2,
	},
},
