Tachyon Sniper "armannit3",
Constant firing "legbastion",
Arm Vulcan Rapid firing Tachyon beams "armvulc",
AD - "legstarfall",
SRAA - "corscreamer",




armannit3 = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 450000,
	metalcost = 13500,
	buildpic = "ARMANNIT3.DDS",
	buildtime = 190000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 15 0",
	collisionvolumescales = "81 122 81",
	collisionvolumetype = "BoxY",
	corpse = "DEAD",
	damagemodifier = 0.25,
	energystorage = 3000,
	explodeas = "fusionExplosion",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 72,
	health = 28000,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "MOBILE",
	objectname = "Units/scavbuildings/ARMANNIT3.s3o",
	onoffable = true,
	radardistance = 1500,
	radaremitheight = 72,
	script = "Units/ARMANNI.cob",
	seismicsignature = 0,
	selfdestructas = "fusionExplosion",
	sightdistance = 900,
	yardmap = "oooooo oooooo oooooo oooooo oooooo oooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armannit3_aoplane.dds",
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 3,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 1.06567382829e-05 -0.0",
			collisionvolumescales = "62.5 81.7362213135 62.5",
			collisionvolumetype = "Box",
			damage = 1800,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 5820,
			object = "Units/scavbuildings/armannit3_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 900,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 2328,
			object = "Units/arm3X3B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:tachyonshot",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "obli",
		},
		select = {
			[1] = "obli",
		},
	},
	weapondefs = {
		ata = {
			areaofeffect = 16,
			avoidfeature = false,
			beamtime = 1,
			collidefriendly = false,
			corethickness = 0.5,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.30,
			energypershot = 7000,
			explosiongenerator = "custom:laserhit-large-blue",
			firestarter = 90,
			impulseboost = 0,
			impulsefactor = 0,
			largebeamlaser = true,
			laserflaresize = 8,
			name = "Heavy long-range g2g tachyon accelerator beam",
			noselfdamage = true,
			range = 1800,
			reloadtime = 15,
			rgbcolor = "0 0 1",
			scrollspeed = 5,
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "annigun1",
			soundtrigger = 1,
			targetmoveerror = 0.3,
			texture3 = "largebeam",
			thickness = 10,
			tilelength = 150,
			tolerance = 10000,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 3100,
			damage = {
				commanders = 480,
				default = 48000,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "ATA",
			onlytargetcategory = "SURFACE",
		},
	},
},






legbastion = {
	maxacc= 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 58000,
	metalcost = 4200,
	buildpic = "legbastion.DDS",
	buildtime = 79000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0.0 0.0 0.0",
	collisionvolumescales = "60 150 60",
	collisionvolumetype = "box",
	corpse = "DEAD",
	damagemodifier = 0.25,
	energystorage = 1000,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 5,
	footprintz = 5,
	icontype = "building",
	idleautoheal = 2,
	idletime = 1800,
	losemitheight = 80,
	health = 15000,
	maxslope = 10,
	maxwaterdepth = 0,
	nochasecategory = "VTOL",
	objectname = "Units/legbastion.s3o",
	onoffable = true,
	radardistance = 1200,
	radaremitheight = 80,
	script = "Units/legbastion.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 780,
	yardmap = "yoo0y o0ooo o0ooo yo0oy",
	customparams = {
		maxrange = 1125,
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corjuno_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Hornet",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 150 60",
			collisionvolumetype = "Box",
			damage = 5400,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			hitdensity = 100,
			metal = 2911,
			object = "Units/legbastion_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 2700,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 3,
			footprintz = 3,
			height = 4,
			hitdensity = 100,
			metal = 1644,
			object = "Units/cor3X3E.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "doom",
		},
		select = {
			[1] = "doom",
		},
	},
	weapondefs = {
		pineappleofdoom = {
			areaofeffect = 120,
			avoidfeature = false,
			avoidfriendly = true,
			beamtime = 1,
			camerashake = 0.1,
			--collidefriendly = false,
			corethickness = 0.4,
			craterareaofeffect = 120,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.45,
			energypershot = 500,
			explosiongenerator = "custom:genericshellexplosion-medium-beam",
			firestarter = 90,
			firetolerance = 300,
			impulseboost = 0,
			impulsefactor = 0,
			laserflaresize = 6,
			name = "Cleansing Light",
			noselfdamage = true,
			predictboost = 0.3,
			proximitypriority = 1,
			range = 1100,
			reloadtime = 2.5,
			rgbcolor = "1 0.5 0",
			rgbcolor2 = "0.9 1.0 0.5",
			soundhitdry = "",
			soundhitwet = "sizzle",
			soundstart = "heatray3",
			soundstartvolume = 38,
			soundtrigger = 1,
			--sweepfire = true,
			targetmoveerror = 0.001,
			thickness = 5.5,
			turret = true,
			weapontype = "BeamLaser",
			weaponvelocity = 1500,
			damage = {
				default = 4500,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL GROUNDSCOUT",
			def = "pineappleofdoom",
			onlytargetcategory = "SURFACE",
			--fastautoretargeting = true,
		}
	},
},



armvulc = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 29096,
	energycost = 752000,
	metalcost = 63000,
	buildpic = "ARMVULC.DDS",
	buildtime = 1400000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -45",
	collisionvolumescales = "90 145 90",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "advancedFusionExplosion",
	firestate = 0,
	footprintx = 8,
	footprintz = 8,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 32000,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/ARMVULC.s3o",
	script = "Units/ARMVULC.cob",
	seismicsignature = 0,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 700,
	usepiececollisionvolumes = 1,
	yardmap = "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armvulc_aoplane.dds",
		buildinggrounddecalsizey = 7.5,
		buildinggrounddecalsizex = 7.5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-30.100944519 -5.74996727295 19.3314819336",
			collisionvolumescales = "169.401870728 123.486465454 147.862945557",
			collisionvolumetype = "Box",
			damage = 26000,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 7,
			footprintz = 7,
			height = 20,
			hitdensity = 100,
			metal = 30000,
			object = "Units/armvulc_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 12000,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 7,
			footprintz = 7,
			height = 4,
			hitdensity = 100,
			metal = 14000,
			object = "Units/arm7X7A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:tachyonshot",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servlrg3",
		},
		select = {
			[1] = "servlrg3",
		},
	},
	weapondefs = {
		ata = {
            areaofeffect = 10,
            avoidfeature = false,
            beamtime = 0.3,
            collidefriendly = false,
            corethickness = 0.5,
            craterareaofeffect = 0,
            craterboost = 0,
            cratermult = 0,
            edgeeffectiveness = 0.5,
            energypershot = 25000,
            explosiongenerator = "custom:laserhit-large-blue",
            firestarter = 90,
            impulseboost = 0,
            impulsefactor = 0,
            largebeamlaser = true,
            laserflaresize = 30,
            name = "Rapid-fire extended-range g2g tachyon accelerator",
            noselfdamage = true,
            range = 2500,
            reloadtime = 2,
            rgbcolor = "0 0 1",
            scrollspeed = 5,
            soundhitdry = "",
            soundhitwet = "sizzle",
            soundstart = "annigun1",
            soundtrigger = 0.5,
            targetmoveerror = 0.3,
            texture3 = "largebeam",
            thickness = 9,
            tilelength = 150,
            tolerance = 10000,
            turret = true,
            weapontype = "BeamLaser",
            weaponvelocity = 3100,
            damage = {
                commanders = 4800,
                default = 50000,
            },
        },
    },
    weapons = {
        [1] = {
            badtargetcategory = "VTOL GROUNDSCOUT",
            def = "ATA",
            onlytargetcategory = "SURFACE",	
            },
        },
},



legstarfall = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 29096,
	energycost = 600000,
	metalcost = 52500,
	buildpic = "legstarfall.DDS",
	buildtime = 1400000,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "120 165 120",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "advancedFusionExplosion",
	hightrajectory = 1,
	firestate = 0,
	footprintx = 8,
	footprintz = 8,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 33500,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/legstarfall.s3o",
	script = "Units/legstarfall.cob",
	seismicsignature = 0,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 700,
	yardmap = "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corbhmth_aoplane.dds",
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		model_author = "Hornet",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "120 125 120",
			collisionvolumetype = "CylY",
			damage = 26000,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 7,
			footprintz = 7,
			height = 20,
			hitdensity = 100,
			metal = 25000,
			object = "Units/legstarfall_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "80 10 80",
			damage = 12000,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 7,
			footprintz = 7,
			height = 4,
			hitdensity = 100,
			metal = 12000,
			object = "Units/cor7X7A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {

		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "servlrg4",
		},
		select = {
			[1] = "servlrg4",
		},
	},
	weapondefs = {
		starfire = {
			accuracy = 0,
			areaofeffect = 256,
			avoidfeature = false,
			avoidfriendly = false,
			avoidground = false,
			burst = 61,
			burstrate = 0.01,
			
			sprayangle = 500,
			highTrajectory = 1,
			
			cegtag = "starfire",
			collidefriendly = false,
			craterboost = 0.1,
			cratermult = 0.1,
			edgeeffectiveness = 0.95,
			energypershot = 360000,
			
			explosiongenerator = "custom:starfire-explosion",
			gravityaffected = "true",
			impulseboost = 0.5,
			impulsefactor = 0.5,
			name = "Starfire Barrage Launcher",
			noselfdamage = true,
			range = 6100,
			reloadtime = 15,
			rgbcolor = "0.7 0.7 1.0 1.0 1.0 1.0 1.0 1.0",
			soundhit = "rflrpcexplo",
			soundhitwet = "splshbig",
			soundstart = "lrpcshot",
			soundhitvolume = 36,
			turret = true,
			weapontimer = 14,
			weapontype = "Cannon",
			weaponvelocity = 900,
			damage = {
				default = 600,
				shields = 375,
				subs = 200,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "starfire",
			onlytargetcategory = "SURFACE",
		},
	},
},


corscreamer = {
	maxacc = 0,
	activatewhenbuilt = true,
	airsightdistance = 2400,
	maxdec = 0,
	energycost = 32000,
	metalcost = 1650,
	buildpic = "CORSCREAMER.DDS",
	buildtime = 28000,
	canrepeat = false,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "63 57 63",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "largeBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1670,
	maxslope = 20,
	maxwaterdepth = 0,
	objectname = "Units/CORSCREAMER.s3o",
	script = "Units/CORSCREAMER.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 600,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corscreamer_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'aa',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "63 57 63",
			collisionvolumetype = "CylY",
			damage = 942,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 1145,
			object = "Units/corscreamer_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 471,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 458,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "targon2",
		canceldestruct = "cancel2",
		deactivate = "targoff2",
		underattack = "warning1",
		working = "targsel2",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "targsel2",
		},
	},
	weapondefs = {
		cor_advsam = {
			areaofeffect = 425,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			canattackground = false,
			cegtag = "missiletrailaa-large",
			collidefriendly = false,
			craterareaofeffect = 425,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.75,
			energypershot = 1800,
			explosiongenerator = "custom:genericshellexplosion-huge-aa",
			firestarter = 90,
			flighttime = 2.2,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 0,
			model = "corscreamermissile.s3o",
			name = "Long-range heavy g2a missile launcher",
			noselfdamage = true,
			proximitypriority = -2,
			range = 2400,
			reloadtime = 1.8,
			smoketrail = true,
			smokePeriod = 3,
			smoketime = 24,
			smokesize = 11,
			smokecolor = 0.9,
			smokeTrailCastShadow = false,
			castshadow = false,
			soundhit = "impact",
			soundhitwet = "splslrg",
			soundstart = "aarocket",
			soundhitvolume = 8,
			soundstartvolume = 8,
			sprayangle = 10000,
			startvelocity = 1400,
			stockpile = true,
			stockpiletime = 14,
			texture1 = "null",
			texture2 = "smoketrailaaflak",
			tolerance = 10000,
			tracks = true,
			trajectoryheight = 0.55,
			turnrate = 99000,
			turret = true,
			weaponacceleration = 1000,
			weapontype = "MissileLauncher",
			weaponvelocity = 1850,
			damage = {
				vtol = 750,
				space = 750,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
			def = "COR_ADVSAM",
			onlytargetcategory = "VTOL SPACE",
		},
	},
},




corbuzz = {
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:barrelshot-huge",
		},
	},
	weapondefs = {
		crblmssl = {
			areaofeffect = 1920,
			avoidfeature = false,
			avoidfriendly = false,
			cegtag = "NUKETRAIL",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			commandfire = true,
			craterareaofeffect = 1920,
			craterboost = 2.4,
			cratermult = 1.2,
			edgeeffectiveness = 0.45,
			energypershot = 187500,
			explosiongenerator = "custom:newnukecor",
			firestarter = 100,
			flighttime = 400,
			impulseboost = 0.5,
			impulsefactor = 0.5,
			metalpershot = 1500,
			model = "crblmssl.s3o",
			name = "Intercontinental thermonuclear ballistic missile",
			range = 10000,
			reloadtime = 10,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 130,
			smokesize = 28,
			smokecolor = 0.85,
			smokeTrailCastShadow = true,
			soundhit = "nukecor",
			soundhitwet = "nukewater",
			soundstart = "nukelaunch",
			soundhitwetvolume = 56,
			soundstartvolume = 20,
			stockpile = true,
			stockpiletime = 10,
			texture1 = "null",
			texture2 = "railguntrail",
			texture3 = "null",
			targetable = 1,
			tolerance = 4000,
			tracks = true,
			turnrate = 5500,
			weaponacceleration = 100,
			weapontimer = 5.5,
			weapontype = "Cannon",
			weaponvelocity = 1600,
			customparams = {
				place_target_on_ground = "true",
			},
			damage = {
				commanders = 2500,
				default = 11500,
			},
		},
		nuclear_launch = {
			areaofeffect = 0,
			avoidfeature = false,
			avoidfriendly = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 0,
			name = "Nuclear Launch",
			range = 0,
			reloadtime = 10,
			soundhit = "nukelaunchalarm",
			soundhitvolume = 50,
			tolerance = 10000,
			turnrate = 10000,
			weaponacceleration = 101,
			weapontimer = 0.1,
			weapontype = "StarburstLauncher",
			weaponvelocity = 100,
			damage = {
				default = 0,
			},
		},
	},
	weapons = {
		[1] = {
			def = "CRBLMSSL",
			onlytargetcategory = "NOTSUB",
		},
		[2] = {
			def = "NUCLEAR_LAUNCH",
			onlytargetcategory = "NOTSUB",
		},
	},
},