Wall - "corfort",
Radar & Vision - "corrad",
Jammer - "corjamt",
Shield - "corgate",
Alt - "corfmd",



corfort = {
	maxacc = 0,
	autoheal = 12,
	blocking = true,
	maxdec = 0,
	buildangle = 0,
	energycost = 500,
	metalcost = 40,
	buildpic = "CORFORT.DDS",
	buildtime = 900,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	collisionvolumeoffsets = "0 -4 0",
	collisionvolumescales = "32 52 32",
	collisionvolumetype = "CylY",
	corpse = "ROCKTEETHX",
	crushresistance = 1000,
	explodeas = "WallExplosionConcreteXL",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	idleautoheal = 0,
	levelground = false,
	health = 8900,
	maxslope = 24,
	maxwaterdepth = 0,
	objectname = "Units/CORFORT.s3o",
	repairable = false,
	script = "Units/CORFORT.cob",
	seismicsignature = 0,
	selfdestructas = "WallExplosionConcrete",
	selfdestructcountdown = 1,
	sightdistance = 1,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corfort_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		objectify = true,
		paralyzemultiplier = 0,
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		rockteethx = {
			animating = 0,
			animtrans = 0,
			blocking = true,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			crushresistance = 0,
			damage = 3000,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 7,
			object = "Units/cor1X1B.s3o",
			reclaimable = true,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},



corrad = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 16000,
	energycost = 630,
	metalcost = 60,
	buildpic = "CORRAD.DDS",
	buildtime = 1140,
	canattack = false,
	canrepeat = false,
	cantbetransported = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -12 0",
	collisionvolumescales = "32 99 32",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 72,
	mass = 5100,
	health = 90,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORRAD.s3o",
	onoffable = false,
	radardistance = 2100,
	radaremitheight = 72,
	script = "Units/CORRAD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 680,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corrad_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.353988647461 -0.0323567626953 1.37395477295",
			collisionvolumescales = "34.8413696289 57.1648864746 30.8629608154",
			collisionvolumetype = "Box",
			damage = 49,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 36,
			object = "Units/corrad_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 25,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 14,
			object = "Units/cor2X2D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t1_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		activate = "cmd-on",
		canceldestruct = "cancel2",
		deactivate = "cmd-off",
		underattack = "warning1",
		working = "cmd-on",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "radarselect",
		},
	},
},




corjamt = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 9821,
	energycost = 5200,
	metalcost = 115,
	buildpic = "CORJAMT.DDS",
	buildtime = 4570,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "30 37 30",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energyupkeep = 25,
	explodeas = "smallexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1070,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORJAMT.s3o",
	onoffable = true,
	radardistancejam = 360,
	script = "Units/CORJAMT.cob",
	seismicsignature = 0,
	selfdestructas = "smallExplosionGenericSelfd",
	sightdistance = 104,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corjamt_aoplane.dds",
		buildinggrounddecalsizey = 3.6,
		buildinggrounddecalsizex = 3.6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -2 0",
			collisionvolumescales = "30 35 30",
			collisionvolumetype = "CylY",
			damage = 576,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 3,
			hitdensity = 100,
			metal = 71,
			object = "Units/corjamt_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "kbcormov",
		},
		select = {
			[1] = "radjam2",
		},
	},
},



corgate = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 2048,
	energycost = 55000,
	metalcost = 3200,
	buildpic = "CORGATE.DDS",
	buildtime = 55000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -4 1",
	collisionvolumescales = "57 38 57",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 1000,
	explodeas = "hugeBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3550,
	maxslope = 10,
	maxwaterdepth = 0,
	noautofire = true,
	objectname = "Units/CORGATE.s3o",
	onoffable = false,
	script = "Units/CORGATE.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corgate_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		shield_color_mult = 0.8,
		shield_power = 3250,
		shield_radius = 550,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -0.00271934814453 -1.05072021484",
			collisionvolumescales = "65.7474060059 27.1259613037 55.6685791016",
			collisionvolumetype = "Box",
			damage = 1900,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2000,
			object = "Units/corgate_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 960,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 800,
			object = "Units/cor2X2E.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "drone1",
		},
		select = {
			[1] = "drone1",
		},
	},
	weapondefs = {
		repulsor = {
			avoidfeature = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			name = "PlasmaRepulsor",
			range = 550,
			soundhitwet = "sizzle",
			weapontype = "Shield",
			damage = {
				default = 100,
			},
			shield = {
				alpha = 0.17,
				armortype = "shields",
				energyupkeep = 0,
				force = 2.5,
				intercepttype = 1,
				power = 3250,
				powerregen = 52,
				powerregenenergy = 562.5,
				radius = 550,
				repulser = true,
				smart = true,
				startingpower = 1100,
				visiblerepulse = true,
				badcolor = {
					[1] = 1,
					[2] = 0.2,
					[3] = 0.2,
					[4] = 0.2,
				},
				goodcolor = {
					[1] = 0.2,
					[2] = 1,
					[3] = 0.2,
					[4] = 0.17,
				},
			},
		},
	},
	weapons = {
		[1] = {
			def = "REPULSOR",
			onlytargetcategory = "NOTSUB",
		},
	},
},




corfmd = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 4096,
	energycost = 40000,
	metalcost = 1500,
	buildpic = "CORFMD.DDS",
	buildtime = 60000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -19 0",
	collisionvolumescales = "48 78 48",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "largeexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3650,
	maxslope = 10,
	maxwaterdepth = 0,
	noautofire = true,
	objectname = "Units/CORFMD.s3o",
	radardistance = 50,
	script = "Units/CORFMD.cob",
	seismicsignature = 0,
	selfdestructas = "largeExplosionGenericSelfd",
	sightdistance = 195,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corfmd_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'antinuke',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landdefenceoffence",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -1.36962890629e-05 -0.0",
			collisionvolumescales = "48.0 37.2831726074 48.0",
			collisionvolumetype = "Box",
			damage = 1968,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 980,
			object = "Units/corfmd_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 984,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 392,
			object = "Units/cor5X5D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "loadwtr1",
		},
		select = {
			[1] = "loadwtr1",
		},
	},
	weapondefs = {
		fmd_rocket = {
			areaofeffect = 420,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			cegtag = "antimissiletrail",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			coverage = 2000,
			craterareaofeffect = 420,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			energypershot = 7500,
			explosiongenerator = "custom:antinuke",
			firestarter = 100,
			flighttime = 20,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			interceptor = 1,
			metalpershot = 150,
			model = "fmdmissile.s3o",
			name = "ICBM intercepting missile launcher",
			noselfdamage = true,
			range = 72000,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 10,
			smoketime = 110,
			smokesize = 27,
			smokecolor = 0.70,
			smokeTrailCastShadow = true,
			soundhit = "xplomed4",
			soundhitwet = "splslrg",
			soundstart = "antinukelaunch",
			stockpile = true,
			stockpiletime = 90,
			texture1 = "bluenovaexplo",
			texture2 = "smoketrailbar",
			texture3 = "null",
			tolerance = 7000,
			tracks = true,
			turnrate = 10000,
			weaponacceleration = 150,
			weapontimer = 2.5,
			weapontype = "StarburstLauncher",
			weaponvelocity = 6000,
			damage = {
				default = 1500,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "ALL",
			def = "FMD_ROCKET",
		},
	},
},