Wall - "corscavfort",
Radar - "armarad",
Jammer - "armveil",
Shield - "armgate",
Alt - "corsd",



corscavfort = {
	maxacc = 0,
	autoheal = 12,
	blocking = true,
	maxdec = 0,
	buildangle = 0,
	energycost = 500,
	metalcost = 40,
	buildpic = "scavengers/SCAVFORT.DDS",
	buildtime = 1000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "32 50 32",
	collisionvolumetype = "CylY",
	corpse = "ROCKTEETHX",
	crushresistance = 1000,
	explodeas = "WallExplosionConcreteXL",
	footprintx = 2,
	footprintz = 2,
	hidedamage = true,
	idleautoheal = 0,
	levelground = false,
	health = 8900,
	maxslope = 24,
	maxwaterdepth = 0,
	objectname = "scavs/SCAVFORT.s3o",
	repairable = false,
	script = "scavs/SCAVFORT.cob",
	seismicsignature = 0,
	selfdestructas = "WallExplosionConcrete",
	selfdestructcountdown = 1,
	sightdistance = 1,
	yardmap = "ffff",
	customparams = {
		usebuildinggrounddecal = false,
		buildinggrounddecaltype = "decals/corscavfort_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		model_author = "FireStorm",
		normaltex = "unittextures/cor_normal.dds",
		objectify = true,
		paralyzemultiplier = 0,
		removestop = true,
		removewait = true,
		subfolder = "other/scavengers",
		--techlevel = 2,
	},
	featuredefs = {
		rockteethx = {
			animating = 0,
			animtrans = 0,
			blocking = true,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			crushresistance = 0,
			damage = 3000,
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 7,
			object = "Units/cor1X1A.s3o",
			reclaimable = true,
			resurrectable = 0,
			shadtrans = 1,
			world = "greenworld",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},



armarad = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 19000,
	metalcost = 560,
	buildpic = "ARMARAD.DDS",
	buildtime = 11800,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	sightemitheight = 40,
	health = 355,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMARAD.s3o",
	onoffable = false,
	radardistance = 3500,
	radaremitheight = 66,
	script = "Units/ARMARAD.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 820,
	usepiececollisionvolumes = 1,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armarad_aoplane.dds",
		buildinggrounddecalsizey = 3.6,
		buildinggrounddecalsizex = 3.6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "6.23959350586 -0.334806103516 -0.00547027587891",
			collisionvolumescales = "37.4791870117 33.549987793 30.0109405518",
			collisionvolumetype = "Box",
			damage = 192,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 40,
			hitdensity = 100,
			metal = 341,
			object = "Units/armarad_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 96,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 136,
			object = "Units/arm2X2C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t2_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "cmd-on",
		canceldestruct = "cancel2",
		deactivate = "cmd-off",
		underattack = "warning1",
		working = "cmd-on",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "radadvn1",
		},
	},
},



armveil = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 19000,
	metalcost = 125,
	buildpic = "ARMVEIL.DDS",
	buildtime = 9100,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	energyupkeep = 125,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 2,
	footprintz = 2,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 830,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMVEIL.s3o",
	onoffable = true,
	radardistancejam = 760,
	script = "Units/ARMVEIL.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 155,
	usepiececollisionvolumes = 1,
	yardmap = "oooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armveil_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-7.16355133057 1.47216796904e-05 -4.91466522217",
			collisionvolumescales = "47.5629425049 83.2464294434 33.8293304443",
			collisionvolumetype = "Box",
			damage = 450,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 77,
			object = "Units/armveil_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 225,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 31,
			object = "Units/arm2X2A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "kbarmmov",
		},
		select = {
			[1] = "radjam1",
		},
	},
},




armgate = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 2048,
	energycost = 54000,
	metalcost = 3000,
	buildpic = "ARMGATE.DDS",
	buildtime = 55000,
	canattack = false,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 1",
	collisionvolumescales = "57 37 57",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energystorage = 1000,
	explodeas = "hugeBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3550,
	maxslope = 10,
	maxwaterdepth = 0,
	noautofire = true,
	objectname = "Units/ARMGATE.s3o",
	onoffable = false,
	script = "Units/ARMGATE.cob",
	seismicsignature = 0,
	selfdestructas = "hugeBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armgate_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		shield_color_mult = 0.8,
		shield_power = 3250,
		shield_radius = 550,
		subfolder = "armbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -2.91625976558e-05 -0.414924621582",
			collisionvolumescales = "57.2399902344 32.5033416748 63.3298492432",
			collisionvolumetype = "Box",
			damage = 1900,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 20,
			hitdensity = 100,
			metal = 2000,
			object = "Units/armgate_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "35.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 900,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 2,
			footprintz = 2,
			height = 4,
			hitdensity = 100,
			metal = 800,
			object = "Units/arm2X2D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "drone1",
		},
		select = {
			[1] = "drone1",
		},
	},
	weapondefs = {
		repulsor = {
			avoidfeature = false,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			name = "PlasmaRepulsor",
			range = 550,
			soundhitwet = "sizzle",
			weapontype = "Shield",
			damage = {
				default = 100,
			},
			shield = {
				alpha = 0.17,
				armortype = "shields",
				energyupkeep = 0,
				force = 2.5,
				intercepttype = 1,
				power = 3250,
				powerregen = 52,
				powerregenenergy = 562.5,
				radius = 550,
				repulser = true,
				smart = true,
				startingpower = 1100,
				visiblerepulse = true,
				badcolor = {
					[1] = 1,
					[2] = 0.2,
					[3] = 0.2,
					[4] = 0.2,
				},
				goodcolor = {
					[1] = 0.2,
					[2] = 1,
					[3] = 0.2,
					[4] = 0.17,
				},
			},
		},
	},
	weapons = {
		[1] = {
			def = "REPULSOR",
			onlytargetcategory = "NOTSUB",
		},
	},
},




corsd = {
	activatewhenbuilt = true,
	buildangle = 4096,
	energycost = 6700,
	metalcost = 750,
	buildpic = "CORSD.DDS",
	buildtime = 12000,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -1 0",
	collisionvolumescales = "65 10 60",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energyupkeep = 125,
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	levelground = false,
	health = 2800,
	maxslope = 36,
	maxwaterdepth = 0,
	objectname = "Units/CORSD.s3o",
	onoffable = true,
	script = "Units/CORSD.cob",
	seismicdistance = 2000,
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 225,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corsd_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'util',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landutil",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-1.15772247314 -1.86200052979 2.43579101563",
			collisionvolumescales = "68.8967437744 12.3805389404 66.8254699707",
			collisionvolumetype = "Box",
			damage = 1500,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 15,
			hitdensity = 100,
			metal = 584,
			object = "Units/corsd_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 750,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 234,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "targon2",
		canceldestruct = "cancel2",
		deactivate = "targoff2",
		underattack = "warning1",
		working = "targsel2",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "targsel2",
		},
	},
},