		-- Metal 
-- Tier 1 & Safe cormakr
-- Tier 2 & Volatile armmakr
-- Tier 3 & Safe cormmkr
-- Tier 4 & Volatile armmmkr

		--Energy
-- Safe by Tier armadvsol , lootboxplatinum , lootboxgold , armfus
-- Volatile by Tier freefusion , corfus , armafus , lootboxbronze
-- Alternative by Tier armgeo , armgmm , armageo , corafus

		-- Metal 
-- Tier 1 & Safe cormakr

cormakr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 1250,
	metalcost = 1,
	buildpic = "CORMAKR.DDS",
	buildtime = 2680,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -1 0",
	collisionvolumescales = "32 25 32",
	collisionvolumetype = "Box",
	explodeas = "metalmaker",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 167,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORMAKR.s3o",
	script = "Units/CORMAKR.cob",
	seismicsignature = 0,
	selfdestructas = "metalmakerSelfd",
	sightdistance = 273,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cormakr_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		energyconv_capacity = 70,
		energyconv_efficiency = 1/70,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-mm-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-mm-deactivate",
		underattack = "warning1",
		working = "arm-bld-metalmaker",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon2",
		},
	},
},


-- Tier 2 & Volatile armmakr

armmakr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 1150,
	metalcost = 1,
	buildpic = "ARMMAKR.DDS",
	buildtime = 2600,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "40 40 40",
	collisionvolumetype = "CYLY",
	explodeas = "metalmaker",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 167,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMMAKR.s3o",
	script = "Units/ARMMAKR.cob",
	seismicsignature = 0,
	selfdestructas = "metalmakerSelfd",
	sightdistance = 273,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armmakr_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		energyconv_capacity = 70,
		energyconv_efficiency = 1/70,
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-mm-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-mm-deactivate",
		underattack = "warning1",
		working = "arm-bld-metalmaker",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon1",
		},
	},
},



------------------ Safe Energy -----------------------------


coradvsol = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 4000,
	metalcost = 370,
	buildpic = "CORADVSOL.DDS",
	buildtime = 8150,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -2",
	collisionvolumescales = "57 35 57",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	damagemodifier = 0.9,
	energymake = 75,
	energystorage = 100,
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1200,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORADVSOL.s3o",
	script = "Units/CORADVSOL.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 260,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/coradvsol_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		solar = true,
		subfolder = "corbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -27 -1",
			collisionvolumescales = "60 112 58",
			collisionvolumetype = "Ell",
			damage = 648,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 12,
			hitdensity = 100,
			metal = 231,
			object = "Units/coradvsol_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 324,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 92,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "solar2",
		canceldestruct = "cancel2",
		deactivate = "solar2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "solar2",
		},
	},
},


freefusion = {
    unitrestricted = 1,
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 50,
	metalcost = 40,
	buildpic = "FREEFUSION.DDS",
	buildtime = 800,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	corpse = "DEAD",
	energymake = 850,
	energystorage = 150,
	explodeas = "fusionExplosion",
	footprintx = 5,
	footprintz = 5,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 560,
	maxslope = 20,
	maxwaterdepth = 0,
	objectname = "Units/freefusion.s3o",
	seismicsignature = 0,
	selfdestructas = "fusionExplosionSelfd",
	sightdistance = 250,
	yardmap = "ooooooooooooooooooooooooo",
	customparams = {
		removestop = true,
		removewait = true,
		subfolder = "other",
		techlevel = 1,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			damage = 2500,
			energy = 0,
			featuredead = "HEAP",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 30,
			object = "Units/freefusion_dead.s3o",
			reclaimable = true,
			customparams = {
				faction = "none",
			},
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1350,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 5,
			hitdensity = 100,
			metal = 10,
			object = "Units/arm5X5A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},
	 -- Alternative Energy ----------------


armgeo = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 2048,
	energycost = 13000,
	metalcost = 560,
	buildpic = "ARMGEO.DDS",
	buildtime = 13100,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -4 0",
	collisionvolumescales = "60 70 60",
	collisionvolumetype = "Box",
	corpse = "dead",
	energymake = 300,
	energystorage = 1000,
	explodeas = "geo",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1940,
	maxslope = 20,
	maxwaterdepth = 5,
	objectname = "Units/ARMGEO.s3o",
	script = "Units/ARMGEO.cob",
	seismicsignature = 0,
	selfdestructas = "geo",
	sightdistance = 273,
	yardmap = "h cbobbobc boboobob obbggbbo bogbbgob bogbbgob obbggbbo boboobob cbobbobc",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armgeo_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		cvbuildable = true,
		geothermal = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 70 60",
			collisionvolumetype = "Box",
			damage = 1050,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 338,
			object = "Units/armgeo_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 525,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 135,
			object = "Units/arm4X4B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "geothrm1",
		},
	},
},










