-- Reinforced Scav Flammer 
corscavdtf = {
	buildcostenergy = 1550,
	buildcostmetal = 290,
	buildtime = 4419,
	damagemodifier = 0.25,
	idleautoheal = 10,
	idletime = 900,
	maxdamage = 1610,
	weapondefs = {
		dmaw = {
			areaofeffect = 64,
			burst = 22,
			burstrate = 0.03333,
			edgeeffectiveness = 0.15,
			firestarter = 100,
			flamegfxtime = 1,
			intensity = 0.75,
			name = "Pop-up anti-swarm AoE flamethrower",
			noselfdamage = true,
			proximitypriority = 3,
			range = 410,
			reloadtime = 1.1,
			sizegrowth = 0.7,
			sprayangle = 100,
			weaponvelocity = 300,
			damage = {
				commanders = 12,
				default = 16,
				subs = 5,
			},
		},
	},
},




-- Arm Lightning - Includes EMP


armclaw = {
	energycost = 1600,
	metalcost = 340,
	buildtime = 4650,
	damagemodifier = 0.25,
	hidedamage = true,
	icontype = "building",
	health = 1330,
	sightdistance = 440,
	weapondefs = {
		dclaw = {
			areaofeffect = 8,
			avoidfeature = false,
			beamttl = 1,
			burst = 10,
			burstrate = 0.03333,
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			duration = 1,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-medium-lightning2",
			firestarter = 50,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			intensity = 24,
			name = "Close-quarters g2g lightning turret",
			noselfdamage = true,
			paralyzer = true,--false
			paralyzetime = 5,
			range = 440,
			reloadtime = 1.13333,
			rgbcolor = "0.5 0.5 1",
			soundhit = "lashit",
			soundhitwet = "sizzle",
			soundstart = "lghthvy1",
			soundtrigger = true,
			thickness = 1.5,
			turret = true,
			weapontype = "LightningCannon",
			weaponvelocity = 450,
			customparams = {
				spark_ceg = "genericshellexplosion-splash-lightning",
				spark_forkdamage = "0.33",
				spark_maxunits = "2",
				spark_range = "60",
			},
			damage = {
				commanders = 31.5,
				default = 21,
				vtol = 2.5,
			},
		},
	},
	weapons = {
		[1] = {
			def = "DCLAW",
			onlytargetcategory = "SURFACE",
			fastautoretargeting = true,
		},
	},
},
-- Recinforced Scav Lightning - Includes EMP
corscavdtl = {
	buildcostenergy = 1600,
	buildcostmetal = 340,
	buildtime = 4638,
	damagemodifier = 0.25,
	maxdamage = 1330,
	weapondefs = {
		dclaw = {
			areaofeffect = 8,
			beamttl = 1,
			burst = 10,
			burstrate = 0.03333,
			duration = 1,
			firestarter = 50,
			impactonly = 1,
			impulseboost = 0,
			impulsefactor = 0,
			intensity = 24,
			range = 440,
			reloadtime = 1.13333,
			thickness = 1.5,
			turret = true,
			weaponvelocity = 450,
			customparams = {
				spark_ceg = "genericshellexplosion-splash-lightning",
				spark_forkdamage = "0.33",
				spark_maxunits = "2",
				spark_range = "60",
			},
			damage = {
				bombers = 2.5,
				commanders = 39,
				default = 21,
				fighters = 2.5,
				vtol = 2.5,
			},
		},
	},
},

-- Arm T1 AA, Good model for this though.
armrl = {
	maxacc = 0,
	airsightdistance = 700,
	maxdec = 0,
	energycost = 900,
	metalcost = 80,
	buildpic = "ARMRL.DDS",
	buildtime = 1800,
	canrepeat = false,
	cantbetransported = false,
	category = "ALL NOTLAND WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "48 60 48",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 5100,
	health = 330,
	maxslope = 20,
	maxwaterdepth = 0,
	nochasecategory = "ALL",
	objectname = "Units/ARMRL.s3o",
	script = "Units/ARMRL.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 455,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armrl_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'aa',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		removewait = true,
		subfolder = "armbuildings/landdefenceoffence",
	},
	weapondefs = {
		armrl_missile = {
			areaofeffect = 48,
			avoidfeature = false,
			burnblow = true,
			canattackground = false,
			cegtag = "missiletrailaa",
			craterareaofeffect = 0,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-tiny-aa",
			firestarter = 70,
			flighttime = 1.9,
			impulseboost = 0.123,
			impulsefactor = 0.123,
			metalpershot = 0,
			model = "cormissile.s3o",
			name = "Light g2a missile launcher",
			noselfdamage = true,
			range = 765,
			reloadtime = 1.7,
			smoketrail = true,
			smokePeriod = 6,
			smoketime = 12,
			smokesize = 4.8,
			smokecolor = 0.95,
			smokeTrailCastShadow = false,
			castshadow = false,
			soundhit = "xplomed2",
			soundhitwet = "splshbig",
			soundstart = "rockhvy2",
			texture1 = "null",
			texture2 = "smoketrailaa",
			tolerance = 10000,
			tracks = true,
			turnrate = 63000,
			turret = true,
			startvelocity = 300,
			weaponacceleration = 200,
			weapontimer = 5,
			weapontype = "MissileLauncher",
			weaponvelocity = 800,
			damage = {
				vtol = 115,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
			def = "ARMRL_MISSILE",
			onlytargetcategory = "VTOL",
			fastautoretargeting = true,
		},
	},
},

-- Low tier narrow radius, single missile for perma field

armjuno = {
	buildcostenergy = 17000,
	buildcostmetal = 640,
	buildtime = 21833,
	footprintx = 4,
	footprintz = 4,
	maxdamage = 2350,
	customparams = {
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
	},
	weapondefs = {
		juno_pulse = {
			areaofeffect = 1400,
			craterareaofeffect = 1400,
			energypershot = 12000,
			metalpershot = 200,
			name = "Anti radar/minefield/jammer magnetic impulse rocket",
			range = 32000,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 8,
			smoketime = 45,
			smokesize = 14.0,
			smokecolor = 0.7,
			stockpile = true,
			stockpiletime = 75,
			tolerance = 4000,
			weaponacceleration = 75,
			weapontimer = 4,
			weapontype = "StarburstLauncher",
			customparams = {
				lups_noshockwave = 1,
				nofire = true,
			},
		},
	},
},

-- Long range flak.  low damage wide area, medium rate of fire.
corflak = {
	airsightdistance = 1000,
	buildcostenergy = 14000,
	buildcostmetal = 850,
	buildtime = 20112,
	maxdamage = 1840,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		armflak_gun = {
			accuracy = 1000,
			areaofeffect = 172,
			craterareaofeffect = 192,
			name = "Heavy g2a flak cannon",
			range = 775,
			reloadtime = 0.53333,
			weaponvelocity = 1600,
			damage = {
				default = 125,
				bombers = 250,
				fighters = 500,
				vtol = 250,
			},
			rgbcolor = {
				[1] = 1,
				[2] = 0.33,
				[3] = 0.7,
			},
		},
	},
},

-- Short range medium damage tracking AA missiles
cormadsam = {
	airsightdistance = 850,
	buildcostenergy = 6100,
	buildcostmetal = 315,
	buildtime = 5237,
	energyuse = 5,
	maxdamage = 2800,
	weapondefs = {
		madsam_missile = {
			areaofeffect = 16,
			edgeeffectiveness = 0.15,
			flighttime = 2.5,
			range = 840,
			reloadtime = 0.4,
			startvelocity = 800,
			tolerance = 9950,
			tracks = true,
			turnrate = 68000,
			weaponacceleration = 160,
			weapontimer = 2,
			weapontype = "MissileLauncher",
			weaponvelocity = 1250,
			damage = {
				bombers = 76,
				fighters = 76,
				vtol = 76,
			},
		},
	},
},





--  Wishing to make this Napalm mobile unit a structure.

leginf = {
	acceleration = 0,
	airsightdistance = 1050,
	brakerate = 0,
	buildcostenergy = 30000,
	buildcostmetal = 2000,
	buildpic = "LEGINF.DDS",
	buildtime = 33000,
	canmove = true,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE TANK EMPABLE",
	collisionvolumeoffsets = "0 -5 3",
	collisionvolumescales = "37 51 51",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	explodeas = "hugeexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	idleautoheal = 5,
	idletime = 1800,
	leavetracks = true,
	mass = 5001,
	maxdamage = 3650,
	maxreversevelocity = 0,
	maxslope = 14,
	maxvelocity = 1.25,
	maxwaterdepth = 15,
	movementclass = "HTANK4",
	selfdestructas = "hugeExplosionGenericSelfd",
	sightdistance = 351,
	turninplace = true,
	turninplaceanglelimit = 90,
	turninplacespeedlimit = 0.95832,
	turnrate = 169.39999,
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armason_aoplane.dds",
		buildinggrounddecalsizey = 2,
		buildinggrounddecalsizex = 2,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'weapon',
		subfolder = "corvehicles/t2",
		techlevel = 2,
	},
	weapondefs = {
		rapidnapalm = {
			areaofeffect = 150,
			cegtag = "burnflame",
			colormap = "0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008",
			craterareaofeffect = 90,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:burnblack",
			flamegfxtime = 1,
			gravityaffected = "true",
			mygravity = 0.08,
			name = "HeavyCannon",
			noselfdamage = true,
			projectiles = 1,
			range = 1100,
			reloadtime = 0.6,
			rgbcolor = "1 0.25 0.1",
			size = 4,
			sprayangle = 2500,
			turret = true,
			weapontype = "Cannon",
			weaponvelocity = 300,
			damage = {
				bombers = 10,
				default = 30,
				fighters = 10,
				subs = 10,
				vtol = 10,
			},
		},
	},
},

-- Arm Bomb Resistant 

armcir = {
	airsightdistance = 1060,
	buildcostenergy = 7300,
	buildcostmetal = 750,
	buildtime = 12000,
	canrepeat = false,
	category = "ALL WEAPON NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "50 77 50",
	collisionvolumetype = "CylY",
	explodeas = "mediumBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	maxdamage = 4450,
	customparams = {
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
	},
	weapondefs = {
		arm_cir = {
			areaofeffect = 48,
			burst = 4,
			burstrate = 0.26667,
			edgeeffectiveness = 0.15,
			explosiongenerator = "custom:genericshellexplosion-tiny-aa",
			flighttime = 2.3,
			impulseboost = 0,
			impulsefactor = 0,
			name = "Rapid-fire long-range g2a missile barrel",
			projectiles = 1,
			proximitypriority = -2,
			range = 1125,
			reloadtime = 1.6,
			smoketrail = true,
			smokePeriod = 8,
			smoketime = 12,
			smokesize = 5.4,
			smokecolor = 0.95,
			smokeTrailCastShadow = false,
			castshadow = false,
			soundhit = "xplosml2",
			soundhitwet = "splshbig",
			soundstart = "rocklit1",
			soundtrigger = true,
			texture1 = "null",
			texture2 = "smoketrailaa3",
			tolerance = 100000,
			tracks = true,
			turnrate = 42000,
			turret = true,
			startvelocity = 250,
			weaponacceleration = 300,
			weapontype = "MissileLauncher",
			weaponvelocity = 1300,
			damage = {
				bombers = 265,
				fighters = 215,
				vtol = 170,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "VTOL",
			def = "ARM_CIR",
			onlytargetcategory = "VTOL",
			fastautoretargeting = true,
		},
	},
},

-- Wide aoe light EMP stun, high firerate, long range

legministarfall = {
	buildcostenergy = 60000,
	buildcostmetal = 2000,
	buildtime = 65000,
	explodeas = "hugeBuildingexplosiongeneric",
	maxdamage = 7000,
	sightdistance = 700,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		ministarfire = {
			accuracy = 0,
			areaofeffect = 55,
			avoidfeature = false,
			avoidfriendly = false,
			avoidground = false,
			burst = 61,
			burstrate = 0.01,
			
			sprayangle = 400,
			highTrajectory = 1,
			
			cegtag = "ministarfire",
			collidefriendly = false,
			craterboost = 0.1,
			cratermult = 0.1,
			edgeeffectiveness = 0.95,
			energypershot = 20000,
			
			explosiongenerator = "custom:ministarfire-explosion",
			gravityaffected = "true",
			impulseboost = 0.5,
			impulsefactor = 0.5,
			name = "Starfire Barrage Launcher",
			noselfdamage = true,
			range = 1400,
			reloadtime = 15,
			rgbcolor = "0.7 0.7 1.0 0.7 1.0 1.0 1.0 0.7",
			soundhit = "xplomed3",
			soundhitwet = "splshbig",
			soundstart = "cannon2",
			soundhitvolume = 20,
			turret = true,
			weapontimer = 14,
			weapontype = "Cannon",
			weaponvelocity = 500,
			damage = {
				default = 125,
				shields = 110,
				subs = 50,
			},
		},
	
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "ministarfire",
			onlytargetcategory = "SURFACE",
		},
	},
},


-- Long range EMP missile launcher, near fast enough to keep something stunned, but high energy cost.

armemp = {
	energycost = 29000,
	metalcost = 1600,
	buildtime = 79300,
	explodeas = "largeBuildingexplosiongeneric",
	health = 3350,
	sightdistance = 455,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		armemp_weapon = {
			areaofeffect = 312,
			avoidfeature = false,
			avoidfriendly = false,
			cegtag = "cruisemissiletrail-emp",
			collideenemy = false,
			collidefeature = false,
			collidefriendly = false,
			commandfire = true,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 1,
			energypershot = 15644,
			explosiongenerator = "custom:genericshellexplosion-huge-lightning",
			firestarter = 0,
			flighttime = 400,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 500,
			model = "cortronmissile.s3o",
			name = "Heavy long-range g2g EMP starburst rocket",
			noselfdamage = true,
			paralyzer = true,
			paralyzetime = 35,
			range = 3650,
			reloadtime = 2,
			smoketrail = true,
			smokePeriod = 8,
			smoketime = 60,
			smokesize = 7,
			smokecolor = 0.9,
			smokeTrailCastShadow = false,
			soundhit = "emgpuls1",
			soundstart = "mismed1emp1",
			stockpile = true,
			stockpiletime = 65,
			texture1 = "null",
			texture2 = "smoketrailbar",
			texture3 = "null",
			tolerance = 4000,
			turnrate = 10000,
			weaponacceleration = 150,
			weapontimer = 3,
			weapontype = "StarburstLauncher",
			weaponvelocity = 1200,
			damage = {
				default = 50000,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "ARMEMP_WEAPON",
			onlytargetcategory = "NOTSUB",
		},
	},
},


-- Very rapid fire flak, long range medium aoe, medium damage.


armflak = {
	airsightdistance = 1000,
	energycost = 13000,
	metalcost = 820,
	buildtime = 19000,
	explodeas = "mediumBuildingexplosiongeneric",
	health = 1750,
	maxslope = 10,
	sightdistance = 525,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		armflak_gun = {
			accuracy = 1000,
			areaofeffect = 172,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			canattackground = false,
			cegtag = "flaktrailaa",
			collidefriendly = false,
			craterareaofeffect = 192,
			craterboost = 0,
			cratermult = 0,
			cylindertargeting = 1,
			edgeeffectiveness = 1,
			explosiongenerator = "custom:flak",
			gravityaffected = "true",
			impulseboost = 0,
			impulsefactor = 0,
			mygravity = 0.01,
			name = "Heavy g2a flak cannon",
			noselfdamage = true,
			predictboost = 1,
			range = 775,
			reloadtime = 0.53333,
			size = 4.5,
			sizedecay = 0.08,
			smoketrail = false,
			soundhit = "flakhit2",
			soundhitwet = "splslrg",
			soundstart = "flakfire",
			soundhitvolume = 7.5,
			soundstartvolume = 9,
			stages = 0,
			turret = true,
			weapontimer = 1,
			weapontype = "Cannon",
			weaponvelocity = 1600,
			damage = {
				default = 125,
				vtol = 250,
			},
			rgbcolor = {
				[1] = 1,
				[2] = 0.33,
				[3] = 0.7,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
			def = "ARMFLAK_GUN",
			onlytargetcategory = "VTOL",
		},
	},
},

-- High damage, short range anti air missiles, medium firerate.


armmercury = {
    airsightdistance = 2400,
    energycost = 33000,
    metalcost = 1600,
    buildtime = 28000,
    explodeas = "largeBuildingExplosionGeneric",
    health = 1670,
    selfdestructas = "largeBuildingExplosionGenericSelfd",
    sightdistance = 600,
    customparams = {
        techlevel = 2,
    },
    weapondefs = {
        arm_advsam = {
            areaofeffect = 425,
            avoidfeature = false,
            avoidfriendly = false,
            burnblow = true,
            canattackground = false,
            cegtag = "missiletrailaa-large",
            collidefriendly = false,
            craterareaofeffect = 425,
            craterboost = 0,
            cratermult = 0,
            edgeeffectiveness = 0.75,
            energypershot = 1800,
            explosiongenerator = "custom:genericshellexplosion-huge-aa",
            firestarter = 90,
            flighttime = 2.2,
            impulseboost = 0,
            impulsefactor = 0,
            metalpershot = 0,
            model = "corscreamermissile.s3o",
            name = "Heavy long-range g2a guided missile launcher",
            noselfdamage = true,
            proximitypriority = -2,
            range = 2400,
            reloadtime = 1.8,
            smoketrail = true,
            smokePeriod = 3,
            smoketime = 24,
            smokesize = 11,
            smokecolor = 0.9,
            smokeTrailCastShadow = false,
            castshadow = false,
            soundhit = "impact",
            soundhitwet = "splslrg",
            soundstart = "aarocket",
            soundhitvolume = 8,
            soundstartvolume = 8,
            sprayangle = 10000,
            startvelocity = 1400,
            stockpile = true,
            stockpiletime = 14,
            texture1 = "null",
            texture2 = "smoketrailaaflak",
            tolerance = 10000,
            tracks = true,
            trajectoryheight = 0.55,
            turnrate = 99000,
            turret = true,
            weaponacceleration = 1000,
            weapontype = "MissileLauncher",
            weaponvelocity = 1850,
            damage = {
                vtol = 750,
                space = 750,
            },
        },
    },
    weapons = {
        [1] = {
            badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
            def = "ARM_ADVSAM",
            onlytargetcategory = "VTOL SPACE",
        },
    },
},








-- Wide aoe, medium EMP stun, zero damage, medium rate missile disperser.

legstarfall = {
	energycost = 600000,
	metalcost = 52500,
	buildtime = 1400000,
	explodeas = "advancedFusionExplosion",
	hightrajectory = 1,
	firestate = 0,
	health = 33500,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 700,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		starfire = {
			accuracy = 0,
			areaofeffect = 256,
			avoidfeature = false,
			avoidfriendly = false,
			avoidground = false,
			burst = 61,
			burstrate = 0.01,
			
			sprayangle = 500,
			highTrajectory = 1,
			
			cegtag = "starfire",
			collidefriendly = false,
			craterboost = 0.1,
			cratermult = 0.1,
			edgeeffectiveness = 0.95,
			energypershot = 360000,
			
			explosiongenerator = "custom:starfire-explosion",
			gravityaffected = "true",
			impulseboost = 0.5,
			impulsefactor = 0.5,
			name = "Starfire Barrage Launcher",
			noselfdamage = true,
			range = 6100,
			reloadtime = 15,
			rgbcolor = "0.7 0.7 1.0 1.0 1.0 1.0 1.0 1.0",
			soundhit = "rflrpcexplo",
			soundhitwet = "splshbig",
			soundstart = "lrpcshot",
			soundhitvolume = 36,
			turret = true,
			weapontimer = 14,
			weapontype = "Cannon",
			weaponvelocity = 900,
			damage = {
				default = 600,
				shields = 375,
				subs = 200,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "MOBILE",
			def = "starfire",
			onlytargetcategory = "SURFACE",
		},
	},
},

-- Ultra high damage, medium range and damge anti air missile launcher.
corscreamer = {
	airsightdistance = 2400,
	energycost = 32000,
	metalcost = 1650,
	buildtime = 28000,
	explodeas = "largeBuildingExplosionGeneric",
	health = 1670,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 600,
	customparams = {
		techlevel = 2,
	},
	weapondefs = {
		cor_advsam = {
			areaofeffect = 425,
			avoidfeature = false,
			avoidfriendly = false,
			burnblow = true,
			canattackground = false,
			cegtag = "missiletrailaa-large",
			collidefriendly = false,
			craterareaofeffect = 425,
			craterboost = 0,
			cratermult = 0,
			edgeeffectiveness = 0.75,
			energypershot = 1800,
			explosiongenerator = "custom:genericshellexplosion-huge-aa",
			firestarter = 90,
			flighttime = 2.2,
			impulseboost = 0,
			impulsefactor = 0,
			metalpershot = 0,
			model = "corscreamermissile.s3o",
			name = "Long-range heavy g2a missile launcher",
			noselfdamage = true,
			proximitypriority = -2,
			range = 2400,
			reloadtime = 1.8,
			smoketrail = true,
			smokePeriod = 3,
			smoketime = 24,
			smokesize = 11,
			smokecolor = 0.9,
			smokeTrailCastShadow = false,
			castshadow = false,
			soundhit = "impact",
			soundhitwet = "splslrg",
			soundstart = "aarocket",
			soundhitvolume = 8,
			soundstartvolume = 8,
			sprayangle = 10000,
			startvelocity = 1400,
			stockpile = true,
			stockpiletime = 14,
			texture1 = "null",
			texture2 = "smoketrailaaflak",
			tolerance = 10000,
			tracks = true,
			trajectoryheight = 0.55,
			turnrate = 99000,
			turret = true,
			weaponacceleration = 1000,
			weapontype = "MissileLauncher",
			weaponvelocity = 1850,
			damage = {
				vtol = 750,
				space = 750,
			},
		},
	},
	weapons = {
		[1] = {
			badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
			def = "COR_ADVSAM",
			onlytargetcategory = "VTOL SPACE",
		},
	},
},


