		-- Metal 
-- Tier 1 & Safe cormakr
-- Tier 2 & Volatile armmakr
-- Tier 3 & Safe cormmkr
-- Tier 4 & Volatile armmmkr

		--Energy
-- Safe by Tier armadvsol , lootboxplatinum , lootboxgold , armfus
-- Volatile by Tier freefusion , corfus , armafus , lootboxbronze
-- Alternative by Tier armgeo , armgmm , armageo , corafus

		-- Metal 
-- Tier 1 & Safe cormakr

cormakr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 1250,
	metalcost = 1,
	buildpic = "CORMAKR.DDS",
	buildtime = 2680,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -1 0",
	collisionvolumescales = "32 25 32",
	collisionvolumetype = "Box",
	explodeas = "metalmaker",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 167,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORMAKR.s3o",
	script = "Units/CORMAKR.cob",
	seismicsignature = 0,
	selfdestructas = "metalmakerSelfd",
	sightdistance = 273,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cormakr_aoplane.dds",
		buildinggrounddecalsizey = 4,
		buildinggrounddecalsizex = 4,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		energyconv_capacity = 70,
		energyconv_efficiency = 1/70,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-mm-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-mm-deactivate",
		underattack = "warning1",
		working = "arm-bld-metalmaker",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon2",
		},
	},
},


-- Tier 2 & Volatile armmakr

armmakr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 1150,
	metalcost = 1,
	buildpic = "ARMMAKR.DDS",
	buildtime = 2600,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -3 0",
	collisionvolumescales = "40 40 40",
	collisionvolumetype = "CYLY",
	explodeas = "metalmaker",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 167,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMMAKR.s3o",
	script = "Units/ARMMAKR.cob",
	seismicsignature = 0,
	selfdestructas = "metalmakerSelfd",
	sightdistance = 273,
	yardmap = "ooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armmakr_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		energyconv_capacity = 70,
		energyconv_efficiency = 1/70,
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-mm-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-mm-deactivate",
		underattack = "warning1",
		working = "arm-bld-metalmaker",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon1",
		},
	},
},

-- Tier 3 Safe

cormmkr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 21000,
	metalcost = 370,
	buildpic = "CORMMKR.DDS",
	buildtime = 31300,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	explodeas = "advmetalmaker",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 560,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORMMKR.s3o",
	script = "Units/CORMMKR.cob",
	seismicsignature = 0,
	selfdestructas = "advmetalmakerSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cormmkr_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		energyconv_capacity = 600,
		energyconv_efficiency = 1/58,
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		flashlightmin = 0.8,
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.0 -2.96020507804e-05 0.388763427734",
			collisionvolumescales = "61.3712463379 53.8299407959 60.5937194824",
			collisionvolumetype = "Box",
			damage = 300,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 228,
			object = "Units/cormmkr_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 150,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 91,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "metlon2",
		canceldestruct = "cancel2",
		deactivate = "metloff2",
		underattack = "warning1",
		working = "metlrun2",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon2",
		},
	},
},


-- Tier 4 Volative

armmmkr = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 8192,
	energycost = 21000,
	metalcost = 380,
	buildpic = "ARMMMKR.DDS",
	buildtime = 35000,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	explodeas = "advmetalmaker",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 445,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMMMKR.s3o",
	script = "Units/ARMMMKR.cob",
	seismicsignature = 0,
	selfdestructas = "advmetalmakerSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armmmkr_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'metal',
		energyconv_capacity = 600,
		energyconv_efficiency = 1/58,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-0.574371337891 -11.1292811768 1.24842834473",
			collisionvolumescales = "60.6127624512 52.6148376465 60.6127624512",
			collisionvolumetype = "Box",
			damage = 240,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 233,
			object = "Units/armmmkr_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 120,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 93,
			object = "Units/arm4X4C.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-mm-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-mm-deactivate",
		underattack = "warning1",
		working = "arm-bld-metalmaker",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "metlon1",
		},
	},
},



------------------ Safe Energy -----------------------------


-- Tier 1 Safe Energy

coradvsol = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 4000,
	metalcost = 370,
	buildpic = "CORADVSOL.DDS",
	buildtime = 8150,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -2",
	collisionvolumescales = "57 35 57",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	damagemodifier = 0.9,
	energymake = 75,
	energystorage = 100,
	explodeas = "mediumBuildingexplosiongeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1200,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/CORADVSOL.s3o",
	script = "Units/CORADVSOL.cob",
	seismicsignature = 0,
	selfdestructas = "mediumBuildingExplosionGenericSelfd",
	sightdistance = 260,
	yardmap = "oooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/coradvsol_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		solar = true,
		subfolder = "corbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -27 -1",
			collisionvolumescales = "60 112 58",
			collisionvolumetype = "Ell",
			damage = 648,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 12,
			hitdensity = 100,
			metal = 231,
			object = "Units/coradvsol_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 324,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			hitdensity = 100,
			metal = 92,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "all",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "solar2",
		canceldestruct = "cancel2",
		deactivate = "solar2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "solar2",
		},
	},
},


-- Tier 2 Safe Energy

lootboxplatinum = {
	maxacc = 0,
	activatewhenbuilt = true,
	autoheal = 1,
	maxdec = 1,
	energycost = 25000,
	metalcost = 2500,
	buildpic = "lootboxes/LOOTBOXPLATINUM.DDS",
	buildtime = 1000,
	canfight = false,
	canguard = false,
	canmove = true,
	canpatrol = false,
	canrepeat = false,
	canselfdestruct = true,
	canstop = false,
	cantbetransported = false,
	capturable = true,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "80 80 80",
	collisionvolumetype = "box",
	energymake = 2800,
	explodeas = "lootboxExplosion4",
	floater = true,
	footprintx = 4,
	footprintz = 4,
	icontype = "lootbox",
	idleautoheal = 10,
	idletime = 1800,
	levelground = false,
	mass = 4000,
	health = 67000,
	maxslope = 10,
	speed = 0.03,
	maxwaterdepth = 0,
	metalmake = 140,
	movementclass = "HOVER3",
	movestate = 0,
	noautofire = false,
	objectname = "lootboxes/lootboxv2_platinum.s3o",
	script = "lootboxes/lootboxv2.cob",
	seismicsignature = 0,
	selfdestructas = "lootboxExplosion4",
	selfdestructcountdown = 9,
	sightdistance = 96,
	transportbyenemy = true,
	turninplace = false,
	turnrate = 0,
	unitname = "lootboxplatinum",
	upright = true,
	usebuildinggrounddecal = false,
	--waterline = 0,
	yardmap = "oooo oooo oooo oooo",
	reclaimable = false,
	customparams = {
		unitgroup = 'energy',
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "other/lootboxes",
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:LootboxLightGold",
			[2] = "custom:LootboxBeaconPlatinum",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},


-- Tier 3 Safe Energy


lootboxgold = {
	maxacc = 0,
	activatewhenbuilt = true,
	autoheal = 1,
	maxdec = 1,
	energycost = 25000,
	metalcost = 1500,
	buildpic = "lootboxes/LOOTBOXGOLD.DDS",
	buildtime = 1000,
	canfight = false,
	canguard = false,
	canmove = true,
	canpatrol = false,
	canrepeat = false,
	canselfdestruct = true,
	canstop = false,
	cantbetransported = false,
	capturable = true,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "64 64 64",
	collisionvolumetype = "box",
	energymake = 1600,
	explodeas = "lootboxExplosion3",
	floater = true,
	footprintx = 4,
	footprintz = 4,
	icontype = "lootbox",
	idleautoheal = 10,
	idletime = 1800,
	levelground = false,
	mass = 4000,
	health = 56000,
	maxslope = 10,
	speed = 0.03,
	maxwaterdepth = 0,
	metalmake = 80,
	movementclass = "HOVER3",
	movestate = 0,
	noautofire = false,
	objectname = "lootboxes/lootboxv2_gold.s3o",
	script = "lootboxes/lootboxv2.cob",
	seismicsignature = 0,
	selfdestructas = "lootboxExplosion3",
	selfdestructcountdown = 9,
	sightdistance = 96,
	transportbyenemy = true,
	turninplace = false,
	turnrate = 0,
	unitname = "lootboxgold",
	upright = true,
	usebuildinggrounddecal = false,
	--waterline = 0,
	yardmap = "oooo oooo oooo oooo",
	reclaimable = false,
	customparams = {
		unitgroup = 'energy',
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "other/lootboxes",
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:LootboxLightGold",
			[2] = "custom:LootboxBeaconGold",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},


-- Tier 4 Safe Energy

armfus = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 21000,
	metalcost = 4300,
	buildpic = "ARMFUS.DDS",
	buildtime = 70000,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 -2",
	collisionvolumescales = "91 57 59",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energymake = 1000,
	energystorage = 2500,
	explodeas = "fusionExplosion",
	footprintx = 6,
	footprintz = 5,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 4450,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMFUS.s3o",
	script = "Units/ARMFUS.cob",
	seismicsignature = 0,
	selfdestructas = "fusionExplosionSelfd",
	sightdistance = 273,
	yardmap = "oooooo oooooo oooooo oooooo oooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armfus_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.420112609863 0.0956184448242 -0.353080749512",
			collisionvolumescales = "98.7820892334 38.6634368896 65.8547515869",
			collisionvolumetype = "Box",
			damage = 2700,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 2603,
			object = "Units/armfus_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1350,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 1041,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "fusion1",
		},
	},
},



		-- Volative Energy

-- Tier 1 Volatile

freefusion = {
    unitrestricted = 1,
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 4096,
	energycost = 50,
	metalcost = 40,
	buildpic = "FREEFUSION.DDS",
	buildtime = 800,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
	corpse = "DEAD",
	energymake = 850,
	energystorage = 150,
	explodeas = "fusionExplosion",
	footprintx = 5,
	footprintz = 5,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 560,
	maxslope = 20,
	maxwaterdepth = 0,
	objectname = "Units/freefusion.s3o",
	seismicsignature = 0,
	selfdestructas = "fusionExplosionSelfd",
	sightdistance = 250,
	yardmap = "ooooooooooooooooooooooooo",
	customparams = {
		removestop = true,
		removewait = true,
		subfolder = "other",
		techlevel = 1,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			damage = 2500,
			energy = 0,
			featuredead = "HEAP",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 30,
			object = "Units/freefusion_dead.s3o",
			reclaimable = true,
			customparams = {
				faction = "none",
			},
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 1350,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 5,
			hitdensity = 100,
			metal = 10,
			object = "Units/arm5X5A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},

-- Tier 2 Volative

corfus = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 16384,
	energycost = 26000,
	metalcost = 4500,
	buildpic = "CORFUS.DDS",
	buildtime = 75400,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	corpse = "DEAD",
	energymake = 1100,
	energystorage = 2500,
	explodeas = "fusionExplosion",
	footprintx = 5,
	footprintz = 5,
	hidedamage = true,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 5000,
	maxslope = 10,
	maxwaterdepth = 1,
	objectname = "Units/CORFUS.s3o",
	script = "Units/CORFUS.cob",
	seismicsignature = 0,
	selfdestructas = "fusionExplosionSelfd",
	sightdistance = 273,
	yardmap = "ooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corfus_aoplane.dds",
		buildinggrounddecalsizey = 7,
		buildinggrounddecalsizex = 7,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "3.32994842529 0.0812156738281 2.24537658691",
			collisionvolumescales = "116.287948608 73.0596313477 95.7222900391",
			collisionvolumetype = "Box",
			damage = 5100,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			hitdensity = 100,
			metal = 2927,
			object = "Units/corfus_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 2550,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 1171,
			object = "Units/cor5X5D.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "fusion2",
		},
	},
},

-- Tier 3 Volative

armafus = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 4096,
	energycost = 69000,
	metalcost = 9700,
	buildpic = "ARMAFUS.DDS",
	buildtime = 312500,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "96 96 96",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	damagemodifier = 0.95,
	energymake = 3000,
	energystorage = 9000,
	explodeas = "advancedFusionExplosion",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 7900,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/ARMAFUS.s3o",
	script = "Units/ARMAFUS.cob",
	seismicsignature = 0,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armafus_aoplane.dds",
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "96 96 96",
			collisionvolumetype = "Box",
			damage = 16290,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 6441,
			object = "Units/armafus_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "96.0 14.0 6.0",
			collisionvolumetype = "box",
			damage = 8145,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 2576,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "fusion1",
		},
	},
},


-- Tier 4 Resource Generator Bronze - Micro Singularity

lootboxbronze = {
	maxacc = 0,
	activatewhenbuilt = true,
	autoheal = 1,
	maxdec = 1,
	energycost = 25000,
	metalcost = 375,
	buildpic = "lootboxes/LOOTBOXBRONZE.DDS",
	buildtime = 1000,
	canfight = false,
	canguard = false,
	canhover = true,
	canmove = true,
	canpatrol = false,
	canrepeat = false,
	canselfdestruct = true,
	canstop = false,
	cantbetransported = false,
	capturable = true,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "32 32 32",
	collisionvolumetype = "box",
	energymake = 400,
	explodeas = "lootboxExplosion1",
	floater = true,
	footprintx = 2,
	footprintz = 2,
	icontype = "lootbox",
	idleautoheal = 10,
	idletime = 1800,
	levelground = false,
	mass = 4000,
	health = 33500,
	maxslope = 10,
	speed = 0.03,
	maxwaterdepth = 0,
	metalmake = 20,
	movementclass = "HOVER3",
	movestate = 0,
	noautofire = false,
	objectname = "lootboxes/lootboxv2_bronze.s3o",
	script = "lootboxes/lootboxv2.cob",
	seismicsignature = 0,
	selfdestructas = "lootboxExplosion1",
	selfdestructcountdown = 9,
	sightdistance = 96,
	transportbyenemy = true,
	turninplace = false,
	turnrate = 0,
	unitname = "lootboxbronze",
	upright = true,
	usebuildinggrounddecal = false,
	--waterline = 0,
	yardmap = "oo oo",
	reclaimable = false,
	customparams = {
		unitgroup = 'energy',
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "other/lootboxes",
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:LootboxLightGold",
			[2] = "custom:LootboxBeaconBronze",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
},



	 -- Alternative Energy ----------------


-- Tier 1 Alternative Energy Geo

armgeo = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 2048,
	energycost = 13000,
	metalcost = 560,
	buildpic = "ARMGEO.DDS",
	buildtime = 13100,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 -4 0",
	collisionvolumescales = "60 70 60",
	collisionvolumetype = "Box",
	corpse = "dead",
	energymake = 300,
	energystorage = 1000,
	explodeas = "geo",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 1940,
	maxslope = 20,
	maxwaterdepth = 5,
	objectname = "Units/ARMGEO.s3o",
	script = "Units/ARMGEO.cob",
	seismicsignature = 0,
	selfdestructas = "geo",
	sightdistance = 273,
	yardmap = "h cbobbobc boboobob obbggbbo bogbbgob bogbbgob obbggbbo boboobob cbobbobc",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armgeo_aoplane.dds",
		buildinggrounddecalsizey = 6,
		buildinggrounddecalsizex = 6,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		cvbuildable = true,
		geothermal = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 70 60",
			collisionvolumetype = "Box",
			damage = 1050,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 40,
			hitdensity = 100,
			metal = 338,
			object = "Units/armgeo_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 525,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 4,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 135,
			object = "Units/arm4X4B.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "geothrm1",
		},
	},
},


-- Tier 2 Alternative - Safe Geo

armgmm = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 16384,
	energycost = 25000,
	metalcost = 1150,
	buildpic = "ARMGMM.DDS",
	buildtime = 41500,
	canrepeat = false,
	category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 6 0",
	collisionvolumescales = "72 33 72",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energymake = 750,
	energystorage = 1500,
	explodeas = "largeBuildingExplosionGeneric",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 13900,
	maxslope = 10,
	maxwaterdepth = 0,
	objectname = "Units/ARMGMM.s3o",
	script = "Units/ARMGMM.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "h cysyysoc osbssbsy sbbjjbbs ysjbbjsy ysjbbjsy sbbjjbbs ysbssbso cosyysyc",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armgmm_aoplane.dds",
		buildinggrounddecalsizey = 8,
		buildinggrounddecalsizex = 8,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		cvbuildable = true,
		geothermal = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.420112609863 0.0956184448242 -0.353080749512",
			collisionvolumescales = "72 33 72",
			collisionvolumetype = "CylY",
			damage = 7000,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 40,
			hitdensity = 100,
			metal = 600,
			object = "Units/armgmm_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 2000,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 5,
			height = 4,
			hitdensity = 100,
			metal = 300,
			object = "Units/arm5X5A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "geothrm1",
		},
	},
},




-- Tier 3 Alternative Adv Geo

armageo = {
	maxacc = 0,
	activatewhenbuilt = true,
	maxdec = 0,
	buildangle = 0,
	energycost = 27000,
	metalcost = 1600,
	buildpic = "ARMAGEO.DDS",
	buildtime = 33300,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "107 77 107",
	collisionvolumetype = "CylY",
	energymake = 1250,
	energystorage = 12000,
	explodeas = "advancedFusionExplosion",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 3600,
	maxslope = 15,
	maxwaterdepth = 5,
	objectname = "Units/ARMAGEO.s3o",
	script = "Units/ARMAGEO.cob",
	seismicsignature = 0,
	selfdestructas = "advgeo",
	sightdistance = 273,
	yardmap = "h cysoosyc ysbssbsy sbbjjbbs osjbbjso osjbbjso sbbjjbbs ysbssbsy cysoosyc",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armageo_aoplane.dds",
		buildinggrounddecalsizey = 11,
		buildinggrounddecalsizex = 11,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		cvbuildable = true,
		geothermal = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "armbuildings/landeconomy",
		techlevel = 2,
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "geothrm1",
		},
	},
},


-- Tier 4 Adv Core Afus

corafus = {
	maxacc = 0,
	maxdec = 0,
	buildangle = 4096,
	energycost = 48000,
	metalcost = 9700,
	buildpic = "CORAFUS.DDS",
	buildtime = 329200,
	canrepeat = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "84 95 84",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	damagemodifier = 0.95,
	energymake = 3000,
	energystorage = 9000,
	explodeas = "advancedFusionExplosion",
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	health = 9400,
	maxslope = 13,
	maxwaterdepth = 0,
	objectname = "Units/CORAFUS.s3o",
	script = "Units/CORAFUS.cob",
	seismicsignature = 0,
	selfdestructas = "advancedFusionExplosionSelfd",
	sightdistance = 273,
	yardmap = "oooooooooooooooooooooooooooooooooooo",
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/corafus_aoplane.dds",
		buildinggrounddecalsizey = 9,
		buildinggrounddecalsizex = 9,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'energy',
		model_author = "Cremuss",
		normaltex = "unittextures/cor_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "corbuildings/landeconomy",
		techlevel = 2,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "-5.1672668457 -0.194635522461 -0.799919128418",
			collisionvolumescales = "114.264892578 89.6709289551 97.8311309814",
			collisionvolumetype = "Box",
			damage = 17100,
			energy = 0,
			featuredead = "HEAP",
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 20,
			hitdensity = 100,
			metal = 6440,
			object = "Units/corafus_dead.s3o",
			reclaimable = true,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 8550,
			energy = 0,
			featurereclamate = "SMUDGE01",
			footprintx = 5,
			footprintz = 4,
			height = 4,
			hitdensity = 100,
			metal = 2576,
			object = "Units/cor4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
			seqnamereclamate = "TREE1RECLAMATE",
			world = "All Worlds",
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "fusion2",
		},
	},
},



