-- Arm long range, moderate power, low health
-- Core Short range, high power, high health


armnanotc = {
	maxacc = 0,
	maxdec = 4.5,
	energycost = 3200,
	metalcost = 210,
	builddistance = 400,
	builder = true,
	buildpic = "ARMNANOTC.DDS",
	buildtime = 5300,
	canassist = true,
	canfight = true,
	canguard = true,
	canpatrol = true,
	canreclaim = true,
	canrepeat = false,
	canstop = true,
	cantbetransported = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "31 32 31",
	collisionvolumetype = "CylY",
	energyupkeep = 30,
	explodeas = "nanoboom",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 700,
	health = 560,
	maxslope = 10,
	maxwaterdepth = 0,
	movementclass = "NANO",
	objectname = "Units/ARMNANOTC.s3o",
	script = "Units/ARMNANOTC.cob",
	seismicsignature = 0,
	selfdestructas = "nanoselfd",
	sightdistance = 380,
	terraformspeed = 1000,
	turnrate = 1,
	upright = true,
	workertime = 200,
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armnanotc_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'builder',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		subfolder = "armbuildings/landutil",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2-builder",
			[2] = "deathceg3-builder",
			[3] = "deathceg4-builder",
		},
	},
	sounds = {
		build = "nanlath1",
		canceldestruct = "cancel2",
		repair = "repair1",
		underattack = "warning1",
		working = "reclaim1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "varmmove",
		},
		select = {
			[1] = "varmsel",
		},
	},
},



cornanotc = {
	maxacc = 0,
	maxdec = 4.5,
	energycost = 3200,
	metalcost = 210,
	builddistance = 400,
	builder = true,
	buildpic = "CORNANOTC.DDS",
	buildtime = 5300,
	canassist = true,
	canfight = true,
	canguard = true,
	canpatrol = true,
	canreclaim = true,
	canrepeat = false,
	canstop = true,
	cantbetransported = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "31 32 31",
	collisionvolumetype = "CylY",
	energyupkeep = 30,
	explodeas = "nanoboom",
	footprintx = 3,
	footprintz = 3,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 700,
	health = 560,
	maxslope = 10,
	maxwaterdepth = 0,
	movementclass = "NANO",
	objectname = "Units/CORNANOTC.s3o",
	script = "Units/CORNANOTC.cob",
	seismicsignature = 0,
	selfdestructas = "nanoselfd",
	sightdistance = 380,
	terraformspeed = 1000,
	turnrate = 1,
	upright = true,
	workertime = 200,
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cornanotc_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'builder',
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "corbuildings/landutil",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2-builder",
			[2] = "deathceg3-builder",
			[3] = "deathceg4-builder",
		},
	},
	sounds = {
		build = "nanlath2",
		canceldestruct = "cancel2",
		capture = "capture1",
		repair = "repair2",
		underattack = "warning1",
		working = "reclaim1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "vcormove",
		},
		select = {
			[1] = "vcorsel",
		},
	},
},




armnanotct2 = {
	maxacc = 0,
	maxdec = 4.5,
	energycost = 12800,
	metalcost = 840,
	builddistance = 500,
	builder = true,
	buildpic = "ARMNANOTC.DDS",
	buildtime = 21000,
	canassist = true,
	canfight = true,
	canguard = true,
	canpatrol = true,
	canreclaim = true,
	canrepeat = false,
	canstop = true,
	cantbetransported = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "46 80 46",
	collisionvolumetype = "CylY",
	energyupkeep = 30,
	explodeas = "nanoboom",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 5100,
	health = 2200,
	maxslope = 10,
	maxwaterdepth = 0,
	movementclass = "NANO",
	objectname = "Units/ARMNANOT2.s3o",
	script = "Units/ARMNANOT2.cob",
	seismicsignature = 0,
	selfdestructas = "nanoselfd",
	sightdistance = 500,
	terraformspeed = 3000,
	turnrate = 1,
	upright = true,
	workertime = 600,
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/armnanotc_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'builder',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		subfolder = "armbuildings/landutil",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2-builder",
			[2] = "deathceg3-builder",
			[3] = "deathceg4-builder",
		},
	},
	sounds = {
		build = "nanlath1",
		canceldestruct = "cancel2",
		repair = "repair1",
		underattack = "warning1",
		working = "reclaim1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "varmmove",
		},
		select = {
			[1] = "varmsel",
		},
	},
},




cornanotct2 = {
	maxacc = 0,
	maxdec = 4.5,
	energycost = 12800,
	metalcost = 840,
	builddistance = 500,
	builder = true,
	buildpic = "CORNANOTC.DDS",
	buildtime = 21000,
	canassist = true,
	canfight = true,
	canguard = true,
	canpatrol = true,
	canreclaim = true,
	canrepeat = false,
	canstop = true,
	cantbetransported = false,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "46 80 46",
	collisionvolumetype = "CylY",
	energyupkeep = 30,
	explodeas = "nanoboom",
	footprintx = 4,
	footprintz = 4,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 5100,
	health = 2200,
	maxslope = 10,
	maxwaterdepth = 0,
	movementclass = "NANO",
	objectname = "Units/CORNANOT2.s3o",
	script = "Units/CORNANOT2.cob",
	seismicsignature = 0,
	selfdestructas = "nanoselfd",
	sightdistance = 500,
	terraformspeed = 3000,
	turnrate = 1,
	upright = true,
	workertime = 600,
	customparams = {
		usebuildinggrounddecal = true,
		buildinggrounddecaltype = "decals/cornanotc_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'builder',
		model_author = "Beherith",
		normaltex = "unittextures/Cor_normal.dds",
		subfolder = "corbuildings/landutil",
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2-builder",
			[2] = "deathceg3-builder",
			[3] = "deathceg4-builder",
		},
	},
	sounds = {
		build = "nanlath1",
		canceldestruct = "cancel2",
		repair = "repair1",
		underattack = "warning1",
		working = "reclaim1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "varmmove",
		},
		select = {
			[1] = "varmsel",
		},
	},
},




armrespawn = {
	maxacc = 0,
	maxdec = 4.5,
	energycost = 1,
	metalcost = 1,
	builddistance = range,
	builder = true,
	buildpic = "ARMNANOTCPLAT.DDS",
	buildtime = 20000,
	canassist = true,
	canfight = true,
	canguard = true,
	canpatrol = true,
	canreclaim = true,
	canrepeat = false,
	canstop = true,
	cantbetransported = true,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "31 50 31",
	collisionvolumetype = "CylY",
	explodeas = "commanderExplosion",
	floater = true,
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 700,
	health = 20000,
	maxslope = 10,
	maxwaterdepth = 50000000,
	minwaterdepth = 12,
	movementclass = "NANO",
	objectname = "Units/ARMRESPAWN.s3o",
	script = "Units/ARMNANOT2.cob",
	seismicsignature = 0,
	selfdestructas = "commanderExplosion",
	sightdistance = range,
	terraformspeed = 1000,
	turnrate = 1,
	upright = true,
	workertime = Spring.GetModOptions().commanderbuildersbuildpower,
	-- buildoptions = {
	-- 	"armcom",
	-- 	"armassistdrone",
	-- },
	customparams = {
		usebuildinggrounddecal = false,
		buildinggrounddecaltype = "decals/armnanotc_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'builder',
		model_author = "Beherith",
		normaltex = "unittextures/Arm_normal.dds",
		subfolder = "armbuildings/seautil",
		--iscommander = true,
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2-builder",
			[2] = "deathceg3-builder",
			[3] = "deathceg4-builder",
		},
	},
	sounds = {
		build = "nanlath1",
		canceldestruct = "cancel2",
		repair = "repair1",
		underattack = "warning1",
		working = "reclaim1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "varmmove",
		},
		select = {
			[1] = "varmsel",
		},
	},
},





correspawn = {
	maxacc = 0,
	maxdec = 4.5,
	energycost = 1,
	metalcost = 1,
	builddistance = range,
	builder = true,
	buildpic = "CORNANOTCPLAT.DDS",
	buildtime = 20000,
	canassist = true,
	canfight = true,
	canguard = true,
	canpatrol = true,
	canreclaim = true,
	canrepeat = false,
	canstop = true,
	cantbetransported = true,
	category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE EMPABLE",
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "31 50 31",
	collisionvolumetype = "CylY",
	explodeas = "commanderExplosion",
	floater = true,
	footprintx = 6,
	footprintz = 6,
	icontype = "building",
	idleautoheal = 5,
	idletime = 1800,
	mass = 700,
	health = 20000,
	maxslope = 10,
	maxwaterdepth = 50000000,
	minwaterdepth = 12,
	movementclass = "NANO",
	objectname = "Units/CORRESPAWN.s3o",
	script = "Units/CORNANOT2.cob",
	seismicsignature = 0,
	selfdestructas = "commanderExplosion",
	sightdistance = range,
	terraformspeed = 1000,
	turnrate = 1,
	upright = true,
	workertime = Spring.GetModOptions().commanderbuildersbuildpower,
	-- buildoptions = {
	-- 	"corcom",
	-- 	"corassistdrone",
	-- },
	customparams = {
		usebuildinggrounddecal = false,
		buildinggrounddecaltype = "decals/cornanotc_aoplane.dds",
		buildinggrounddecalsizey = 5,
		buildinggrounddecalsizex = 5,
		buildinggrounddecaldecayspeed = 30,
		unitgroup = 'builder',
		model_author = "Beherith",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "corbuildings/seautil",
		--iscommander = true,
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2-builder",
			[2] = "deathceg3-builder",
			[3] = "deathceg4-builder",
		},
	},
	sounds = {
		build = "nanlath2",
		canceldestruct = "cancel2",
		capture = "capture1",
		repair = "repair2",
		underattack = "warning1",
		working = "reclaim1",
		cant = {
			[1] = "cantdo4",
		},
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		ok = {
			[1] = "vcormove",
		},
		select = {
			[1] = "vcorsel",
		},
	},
},